<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"xml:lang=""><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-132829179-1"></script><script>function gtag(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[],gtag("js",new Date),gtag("config","UA-132829179-1")</script><meta charset="utf-8"><meta http-equiv="X-UA-Compatible"content="IE=edge"><title>19. ANOVA ir jos analogai | Biostatistika</title><meta name="description"content="19. ANOVA ir jos analogai | Biostatistika"><meta name="generator"content="bookdown  and GitBook 2.6.7"><meta property="og:title"content="19. ANOVA ir jos analogai | Biostatistika"><meta property="og:type"content="book"><meta name="twitter:card"content="summary"><meta name="twitter:title"content="19. ANOVA ir jos analogai | Biostatistika"><meta name="author"content="Vilmantas Gėgžna"><meta name="viewport"content="width=device-width,initial-scale=1"><meta name="apple-mobile-web-app-capable"content="yes"><meta name="apple-mobile-web-app-status-bar-style"content="black"><link rel="prev"href="ht-padetis.html"><link rel="next"href="rysys-tarp-kintamuju.html"><script src="libs/jquery-2.2.3/jquery.min.js"></script><link href="libs/gitbook-2.6.7/css/style.css"rel="stylesheet"><link href="libs/gitbook-2.6.7/css/plugin-table.css"rel="stylesheet"><link href="libs/gitbook-2.6.7/css/plugin-bookdown.css"rel="stylesheet"><link href="libs/gitbook-2.6.7/css/plugin-highlight.css"rel="stylesheet"><link href="libs/gitbook-2.6.7/css/plugin-search.css"rel="stylesheet"><link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css"rel="stylesheet"><link href="libs/font-awesome-5.3.1/css/fontawesome-all.min.css"rel="stylesheet"><script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script><link href="libs/datatables-css-0.0.0/datatables-crosstalk.css"rel="stylesheet"><script src="libs/datatables-binding-0.5/datatables.js"></script><link href="libs/dt-core-1.10.16/css/jquery.dataTables.min.css"rel="stylesheet"><link href="libs/dt-core-1.10.16/css/jquery.dataTables.extra.css"rel="stylesheet"><script src="libs/dt-core-1.10.16/js/jquery.dataTables.min.js"></script><link href="libs/dt-plugin-searchhighlight-1.10.16/dataTables.searchHighlight.css"rel="stylesheet"><script src="libs/dt-plugin-searchhighlight-1.10.16/dataTables.searchHighlight.min.js"></script><script src="libs/dt-plugin-searchhighlight-1.10.16/jquery.highlight.js"></script><link href="libs/crosstalk-1.0.0/css/crosstalk.css"rel="stylesheet"><script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script><style type="text/css">a.sourceLine{display:inline-block;line-height:1.25}a.sourceLine{pointer-events:none;color:inherit;text-decoration:inherit}a.sourceLine:empty{height:1.2em}.sourceCode{overflow:visible}code.sourceCode{white-space:pre;position:relative}div.sourceCode{margin:1em 0}pre.sourceCode{margin:0}@media screen{div.sourceCode{overflow:auto}}@media print{code.sourceCode{white-space:pre-wrap}a.sourceLine{text-indent:-1em;padding-left:1em}}pre.numberSource a.sourceLine{position:relative;left:-4em}pre.numberSource a.sourceLine::before{content:attr(title);position:relative;left:-1em;text-align:right;vertical-align:baseline;border:none;pointer-events:all;display:inline-block;-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;padding:0 4px;width:4em;background-color:#2a211c;color:#bdae9d}pre.numberSource{margin-left:3em;border-left:1px solid #bdae9d;padding-left:4px}div.sourceCode{color:#bdae9d;background-color:#2a211c}@media screen{a.sourceLine::before{text-decoration:underline}}code span.al{color:#ff0}code span.an{color:#06f;font-weight:700;font-style:italic}code span.bn{color:#44aa43}code span.cf{color:#43a8ed;font-weight:700}code span.ch{color:#049b0a}code span.co{color:#06f;font-weight:700;font-style:italic}code span.do{color:#06f;font-style:italic}code span.dt{text-decoration:underline}code span.dv{color:#44aa43}code span.er{color:#ff0;font-weight:700}code span.fl{color:#44aa43}code span.fu{color:#ff9358;font-weight:700}code span.in{color:#06f;font-weight:700;font-style:italic}code span.kw{color:#43a8ed;font-weight:700}code span.pp{font-weight:700}code span.sc{color:#049b0a}code span.ss{color:#049b0a}code span.st{color:#049b0a}code span.vs{color:#049b0a}code span.wa{color:#ff0;font-weight:700}</style><link rel="stylesheet"href="style.css"type="text/css"><link rel="stylesheet"href="kbd.css"type="text/css"><link rel="icon"href="fig/icons/favicon.png"></head><body><div class="book without-animation with-summary font-size-2 font-family-1"data-basepath="."><div class="book-summary"><nav role="navigation"><ul class="summary"><li><a href="../">Mokymai (pagrindinis)</a></li><li class="divider"></li><li class="chapter"data-level=""data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Pradžia</a></li><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html"><i class="fa fa-check"></i>Apie</a><ul><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#apie-sia-svetaine"><i class="fa fa-check"></i>Apie šią svetainę</a><ul><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#svetaines-valdymas-klavisais"><i class="fa fa-check"></i>Svetainės valdymas klavišais</a></li><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#pastabos-apie"><i class="fa fa-check"></i>Pastabos</a></li><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#dezuciu-reiksmes"><i class="fa fa-check"></i>Dėžučių reikšmės</a></li></ul></li><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#reikalavimai"><i class="fa fa-check"></i>Reikalavimai studentui</a><ul><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#igudziai"><i class="fa fa-check"></i>Įgūdžiai</a></li><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#reikmenys-pratyboms"><i class="fa fa-check"></i>Reikmenys pratyboms</a></li><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#reikmenys-paskaitoms"><i class="fa fa-check"></i>Reikmenys paskaitoms</a></li></ul></li></ul></li><li class="part"><span><b>Pagrindai</b></span></li><li class="chapter"data-level="1"data-path="diegimas.html"><a href="diegimas.html"><i class="fa fa-check"></i><b>1</b> Programų diegimas ir nustatymai</a><ul><li class="chapter"data-level="1.1"data-path="diegimas.html"><a href="diegimas.html#apie-r"><i class="fa fa-check"></i><b>1.1</b> Apie programą <strong><em>R</em></strong></a></li><li class="chapter"data-level="1.2"data-path="diegimas.html"><a href="diegimas.html#pastabos-pries-diegiant"><i class="fa fa-check"></i><b>1.2</b> Pastabos prieš diegiant</a></li><li class="chapter"data-level="1.3"data-path="diegimas.html"><a href="diegimas.html#pagrindines-programos"><i class="fa fa-check"></i><b>1.3</b> Pagrindinės programos</a><ul><li class="chapter"data-level="1.3.1"data-path="diegimas.html"><a href="diegimas.html#diegti-r"><i class="fa fa-check"></i><b>1.3.1</b> Programa <strong><em>R</em></strong></a></li><li class="chapter"data-level="1.3.2"data-path="diegimas.html"><a href="diegimas.html#diegti-rstudio"><i class="fa fa-check"></i><b>1.3.2</b> Programa <strong><em>RStudio</em></strong></a></li><li class="chapter"data-level="1.3.3"data-path="diegimas.html"><a href="diegimas.html#mac-naudotojams"><i class="fa fa-check"></i><b>1.3.3</b> <em>Mac</em> naudotojams</a></li></ul></li><li class="chapter"data-level="1.4"data-path="diegimas.html"><a href="diegimas.html#diegti-r-paketus"><i class="fa fa-check"></i><b>1.4</b> <strong><em>R</em></strong> paketų diegimas</a><ul><li class="chapter"data-level="1.4.1"data-path="diegimas.html"><a href="diegimas.html#diegti-r-sprendimai"><i class="fa fa-check"></i><b>1.4.1</b> Kilus problemų dėl paketų diegimo…</a></li></ul></li><li class="chapter"data-level="1.5"data-path="diegimas.html"><a href="diegimas.html#konfig"><i class="fa fa-check"></i><b>1.5</b> Programų konfigūravimas</a><ul><li class="chapter"data-level="1.5.1"data-path="diegimas.html"><a href="diegimas.html#spartusis-veikimas"><i class="fa fa-check"></i><b>1.5.1</b> Sparčiojo veikimo režimas</a><ul><li><a href="diegimas.html#win10-power-opts"><strong><em>Windows 10</em></strong></a></li></ul></li><li class="chapter"data-level="1.5.2"data-path="diegimas.html"><a href="diegimas.html#rs-config-utf8"><i class="fa fa-check"></i><b>1.5.2</b> <strong><em>RStudio</em></strong>: <strong>UTF-8</strong> koduotė dokumentams</a></li><li class="chapter"data-level="1.5.3"data-path="diegimas.html"><a href="diegimas.html#rs-config"><i class="fa fa-check"></i><b>1.5.3</b> <strong><em>RStudio</em></strong>: kiti nustatymai</a></li></ul></li><li class="chapter"data-level="1.6"data-path="diegimas.html"><a href="diegimas.html#diegti-papildoma"><i class="fa fa-check"></i><b>1.6</b> Papildomos instrukcijos</a></li><li class="chapter"data-level="1.7"data-path="diegimas.html"><a href="diegimas.html#paskyros"><i class="fa fa-check"></i><b>1.7</b> Paskyros</a><ul><li class="chapter"data-level="1.7.1"data-path="diegimas.html"><a href="diegimas.html#emokymai_paskyra"><i class="fa fa-check"></i><b>1.7.1</b> „Emokymai“ sistema</a></li><li class="chapter"data-level="1.7.2"data-path="diegimas.html"><a href="diegimas.html#datacamp_paskyra"><i class="fa fa-check"></i><b>1.7.2</b> „Data Camp“ paskyra</a></li><li class="chapter"data-level="1.7.3"data-path="diegimas.html"><a href="diegimas.html#github-paskyra"><i class="fa fa-check"></i><b>1.7.3</b> „GitHub“ paskyra</a></li></ul></li><li class="chapter"data-level=""data-path="diegimas.html"><a href="diegimas.html#diegimas-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="2"data-path="pradines-savokos.html"><a href="pradines-savokos.html"><i class="fa fa-check"></i><b>2</b> Pradinės duomenų analizės sąvokos (teorija)</a><ul><li class="chapter"data-level="2.1"data-path="pradines-savokos.html"><a href="pradines-savokos.html#statistinio-tyrimo-ciklas"><i class="fa fa-check"></i><b>2.1</b> Statistinio tyrimo ciklas</a></li><li class="chapter"data-level="2.2"data-path="pradines-savokos.html"><a href="pradines-savokos.html#svarbiausia-analizes-dalis-klausimas"><i class="fa fa-check"></i><b>2.2</b> Svarbiausia analizės dalis – klausimas</a></li><li class="chapter"data-level="2.3"data-path="pradines-savokos.html"><a href="pradines-savokos.html#generaline-aibe-imtis-ir-duomenys"><i class="fa fa-check"></i><b>2.3</b> Generalinė aibė, imtis ir duomenys</a></li><li class="chapter"data-level="2.4"data-path="pradines-savokos.html"><a href="pradines-savokos.html#statistikos-mokslas-ir-jo-dalys"><i class="fa fa-check"></i><b>2.4</b> Statistikos mokslas ir jo dalys</a></li><li class="chapter"data-level="2.5"data-path="pradines-savokos.html"><a href="pradines-savokos.html#stat-kintamuju-tipai"><i class="fa fa-check"></i><b>2.5</b> Kintamųjų tipai statistikoje</a><ul><li class="chapter"data-level=""data-path="pradines-savokos.html"><a href="pradines-savokos.html#veiksmai-su-kintamaisiais"><i class="fa fa-check"></i>Kokius veiksmus galima atlikti su skirtingų tipų kintamųjų reikšmėmis?</a></li><li class="chapter"data-level=""data-path="pradines-savokos.html"><a href="pradines-savokos.html#apsimeteteliai"><i class="fa fa-check"></i>Kokie kintamieji atrodo kaip skaitiniai (kiekybiniai), bet iš tiesų yra kategoriniai?</a></li></ul></li><li class="chapter"data-level="2.6"data-path="pradines-savokos.html"><a href="pradines-savokos.html#duomenu-strukturos-statistikoje"><i class="fa fa-check"></i><b>2.6</b> Duomenų saugojimo formos</a></li><li class="chapter"data-level="2.7"data-path="pradines-savokos.html"><a href="pradines-savokos.html#duomenu-eilutes"><i class="fa fa-check"></i><b>2.7</b> Duomenų eilutės</a></li><li class="chapter"data-level="2.8"data-path="pradines-savokos.html"><a href="pradines-savokos.html#duomenu-lenteles"><i class="fa fa-check"></i><b>2.8</b> Duomenų lentelės</a></li><li class="chapter"data-level=""data-path="pradines-savokos.html"><a href="pradines-savokos.html#pradines-savokos-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="3"data-path="rstudio.html"><a href="rstudio.html"><i class="fa fa-check"></i><b>3</b> Programa <strong><em>RStudio</em></strong></a><ul><li class="chapter"data-level="3.1"data-path="rstudio.html"><a href="rstudio.html#rs-intro"><i class="fa fa-check"></i><b>3.1</b> <strong><em>RStudio</em></strong></a></li><li class="chapter"data-level="3.2"data-path="rstudio.html"><a href="rstudio.html#rstudio-langu-isdestymas"><i class="fa fa-check"></i><b>3.2</b> <strong><em>RStudio</em></strong> langų išdėstymas</a></li><li class="chapter"data-level="3.3"data-path="rstudio.html"><a href="rstudio.html#komandu-langas"><i class="fa fa-check"></i><b>3.3</b> Komandų langas</a></li><li class="chapter"data-level="3.4"data-path="rstudio.html"><a href="rstudio.html#redaktoriaus-langas"><i class="fa fa-check"></i><b>3.4</b> Redaktoriaus langas</a></li><li class="chapter"data-level="3.5"data-path="rstudio.html"><a href="rstudio.html#rs-paketai"><i class="fa fa-check"></i><b>3.5</b> Paketų valdymo langas</a></li><li class="chapter"data-level="3.6"data-path="rstudio.html"><a href="rstudio.html#rs-help"><i class="fa fa-check"></i><b>3.6</b> Pagalbos langas</a></li><li class="chapter"data-level="3.7"data-path="rstudio.html"><a href="rstudio.html#rs-projektai"><i class="fa fa-check"></i><b>3.7</b> <strong><em>RStudio</em></strong> projektai</a></li><li class="chapter"data-level=""data-path="rstudio.html"><a href="rstudio.html#rstudio-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="4"data-path="r-pradmenys.html"><a href="r-pradmenys.html"><i class="fa fa-check"></i><b>4</b> Programos <strong><em>R</em></strong> pradmenys</a><ul><li class="chapter"data-level="4.1"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-sintakse-intro"><i class="fa fa-check"></i><b>4.1</b> Pirmieji <strong><em>R</em></strong> kodo elementai</a><ul><li class="chapter"data-level="4.1.1"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-kodo-komentarai"><i class="fa fa-check"></i><b>4.1.1</b> <strong><em>R</em></strong> kodo komentarai (<code>#</code>)</a></li><li class="chapter"data-level="4.1.2"data-path="r-pradmenys.html"><a href="r-pradmenys.html#rezultatu-zenklinimas"><i class="fa fa-check"></i><b>4.1.2</b> Rezultatų ženklinimas (<code>##</code>)</a></li><li class="chapter"data-level="4.1.3"data-path="r-pradmenys.html"><a href="r-pradmenys.html#elementu-eiles-numeriu-zymejimas"><i class="fa fa-check"></i><b>4.1.3</b> Elementų eilės numerių žymėjimas: <code>[ ]</code></a></li><li class="chapter"data-level="4.1.4"data-path="r-pradmenys.html"><a href="r-pradmenys.html#kitu-elementu-spalvinis-zymejimas"><i class="fa fa-check"></i><b>4.1.4</b> Kitų elementų spalvinis žymėjimas</a></li><li class="chapter"data-level="4.1.5"data-path="r-pradmenys.html"><a href="r-pradmenys.html#programos-kodas-blokais-ir-tekste"><i class="fa fa-check"></i><b>4.1.5</b> Programos kodas: blokais ir tekste</a></li></ul></li><li class="chapter"data-level="4.2"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-funkcijos-ir-operatoriai"><i class="fa fa-check"></i><b>4.2</b> <strong><em>R</em></strong> funkcijos</a><ul><li class="chapter"data-level="4.2.1"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-funkcijos"><i class="fa fa-check"></i><b>4.2.1</b> Įprastinės funkcijos ir jų argumentai</a></li><li class="chapter"data-level="4.2.2"data-path="r-pradmenys.html"><a href="r-pradmenys.html#operatoriai"><i class="fa fa-check"></i><b>4.2.2</b> Operatoriai</a></li></ul></li><li class="chapter"data-level="4.3"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-objektai"><i class="fa fa-check"></i><b>4.3</b> <strong><em>R</em></strong> objektai</a><ul><li class="chapter"data-level="4.3.1"data-path="r-pradmenys.html"><a href="r-pradmenys.html#objektu-kurimas"><i class="fa fa-check"></i><b>4.3.1</b> Objektų kūrimas</a></li><li class="chapter"data-level="4.3.2"data-path="r-pradmenys.html"><a href="r-pradmenys.html#workspace"><i class="fa fa-check"></i><b>4.3.2</b> Darbinė erdvė</a></li><li class="chapter"data-level="4.3.3"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-objektu-pavadinimai"><i class="fa fa-check"></i><b>4.3.3</b> Objektų pavadinimai</a><ul><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#leistini-simboliai-pavadinimuose"><i class="fa fa-check"></i>Leistini simboliai pavadinimuose</a></li><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#ar-didziosios-ir-mazosios-raides-svarbu"><i class="fa fa-check"></i>Ar didžiosios ir mažosios raidės – svarbu?</a></li><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#pavadinimu-rasymo-stilius-rekomendacijos"><i class="fa fa-check"></i>Pavadinimų rašymo stilius (rekomendacijos)</a></li><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#netaisyklingi-pavadinimai"><i class="fa fa-check"></i>Netaisyklingi pavadinimai</a></li></ul></li></ul></li><li class="chapter"data-level="4.4"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-duomenu-tipai"><i class="fa fa-check"></i><b>4.4</b> Svarbiausi <strong><em>R</em></strong> duomenų tipai</a><ul><li class="chapter"data-level="4.4.1"data-path="r-pradmenys.html"><a href="r-pradmenys.html#skaitiniai-kintamieji"><i class="fa fa-check"></i><b>4.4.1</b> Skaitiniai kintamieji</a><ul><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-numeric"><i class="fa fa-check"></i>Klasė „numeric“</a></li><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-integer"><i class="fa fa-check"></i>Klasė „integer“</a></li></ul></li><li class="chapter"data-level="4.4.2"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-logical"><i class="fa fa-check"></i><b>4.4.2</b> Loginės reikšmės</a></li><li class="chapter"data-level="4.4.3"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-character"><i class="fa fa-check"></i><b>4.4.3</b> Tekstiniai kintamieji</a></li><li class="chapter"data-level="4.4.4"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-kategoriniai"><i class="fa fa-check"></i><b>4.4.4</b> Faktoriai – kategoriniai kintamieji</a><ul><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#nominalieji-duomenys"><i class="fa fa-check"></i>Nominalieji duomenys</a></li><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#ranginiai-duomenys"><i class="fa fa-check"></i>Ranginiai duomenys</a></li></ul></li></ul></li><li class="chapter"data-level="4.5"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-duomenu-strukturos"><i class="fa fa-check"></i><b>4.5</b> <strong><em>R</em></strong> duomenų struktūros</a></li><li class="chapter"data-level="4.6"data-path="r-pradmenys.html"><a href="r-pradmenys.html#klausimai-r-ivadas"><i class="fa fa-check"></i><b>4.6</b> Klausimai savikontrolei</a></li><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-pradmenys-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="5"data-path="r-paketai.html"><a href="r-paketai.html"><i class="fa fa-check"></i><b>5</b> <strong><em>R</em></strong> paketai</a><ul><li class="chapter"data-level="5.1"data-path="r-paketai.html"><a href="r-paketai.html#pkg-diegimas-uzkroviumas"><i class="fa fa-check"></i><b>5.1</b> Paketų užkrovimas</a></li><li class="chapter"data-level="5.2"data-path="r-paketai.html"><a href="r-paketai.html#rs-packages"><i class="fa fa-check"></i><b>5.2</b> <strong><em>RStudio</em></strong> langas <em>Packages</em></a></li><li class="chapter"data-level="5.3"data-path="r-paketai.html"><a href="r-paketai.html#r-paketu-saugyklos"><i class="fa fa-check"></i><b>5.3</b> <strong>R</strong> paketų saugyklos</a></li><li class="chapter"data-level="5.4"data-path="r-paketai.html"><a href="r-paketai.html#apie-paketu-diegima"><i class="fa fa-check"></i><b>5.4</b> Apie paketų diegimą</a><ul><li class="chapter"data-level="5.4.1"data-path="r-paketai.html"><a href="r-paketai.html#diegimas-is-cran"><i class="fa fa-check"></i><b>5.4.1</b> Diegimas iš <em>CRAN</em></a></li><li class="chapter"data-level="5.4.2"data-path="r-paketai.html"><a href="r-paketai.html#diegimas-is-github"><i class="fa fa-check"></i><b>5.4.2</b> Diegimas iš <em>GitHub</em></a></li></ul></li><li class="chapter"data-level="5.5"data-path="r-paketai.html"><a href="r-paketai.html#funkciju-naudojimas-neuzkrovus-paketu"><i class="fa fa-check"></i><b>5.5</b> Funkcijų naudojimas neužkrovus paketų</a></li><li class="chapter"data-level="5.6"data-path="r-paketai.html"><a href="r-paketai.html#placiau-apie-paketus"><i class="fa fa-check"></i><b>5.6</b> Plačiau apie paketus</a></li><li class="chapter"data-level=""data-path="r-paketai.html"><a href="r-paketai.html#r-paketai-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="6"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html"><i class="fa fa-check"></i><b>6</b> Skaitinės suvestinės (teorija)</a><ul><li class="chapter"data-level="6.1"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#aprasomoji-statistika"><i class="fa fa-check"></i><b>6.1</b> Aprašomoji statistika</a></li><li class="chapter"data-level="6.2"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#ga-parametrai-ir-imties-statistikos"><i class="fa fa-check"></i><b>6.2</b> GA parametrai ir imties statistikos</a></li><li class="chapter"data-level="6.3"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#suvestines-1"><i class="fa fa-check"></i><b>6.3</b> Aprašomosios statistikos</a></li><li class="chapter"data-level="6.4"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#imties-dydis--privaloma"><i class="fa fa-check"></i><b>6.4</b> Imties dydis – jį privaloma pateikti ataskaitoje</a></li><li class="chapter"data-level="6.5"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#kintamojo-aprasymas"><i class="fa fa-check"></i><b>6.5</b> Kaip statistiškai aprašyti vieno kintamojo reikšmes?</a></li><li class="chapter"data-level="6.6"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#kaip-pasirinkti-tolydiesiems-duomenims-tinkamas-suvestines"><i class="fa fa-check"></i><b>6.6</b> Kaip pasirinkti tolydiesiems duomenims tinkamas suvestines?</a></li><li class="chapter"data-level="6.7"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#kvantiliai-ir-kvartiliai"><i class="fa fa-check"></i><b>6.7</b> Kvantiliai ir kvartiliai</a></li><li class="chapter"data-level="6.8"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#statistinis-daznis-ir-dazniu-lenteles"><i class="fa fa-check"></i><b>6.8</b> Statistinis dažnis ir dažnių lentelės</a></li><li class="chapter"data-level=""data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#teorija-skaitines-suvestines-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="7"data-path="r-vektoriai.html"><a href="r-vektoriai.html"><i class="fa fa-check"></i><b>7</b> Darbas su duomenų sekomis</a><ul><li class="chapter"data-level="7.1"data-path="r-vektoriai.html"><a href="r-vektoriai.html#specialiosios-paskirties-zodziai"><i class="fa fa-check"></i><b>7.1</b> Specialiosios paskirties žodžiai</a></li><li class="chapter"data-level="7.2"data-path="r-vektoriai.html"><a href="r-vektoriai.html#bendrieji-darbo-su-vektoriais-principai"><i class="fa fa-check"></i><b>7.2</b> Bendrieji darbo su vektoriais principai</a><ul><li class="chapter"data-level="7.2.1"data-path="r-vektoriai.html"><a href="r-vektoriai.html#vektoriaus-kurimas"><i class="fa fa-check"></i><b>7.2.1</b> Vektoriaus kūrimas</a><ul><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#skirtingu-tipu-duomenys-vienoje-sekoje"><i class="fa fa-check"></i>Skirtingų tipų duomenys vienoje sekoje?</a></li></ul></li><li class="chapter"data-level="7.2.2"data-path="r-vektoriai.html"><a href="r-vektoriai.html#vektoriaus-savybiu-tikrinimas"><i class="fa fa-check"></i><b>7.2.2</b> Vektoriaus savybių tikrinimas</a></li><li class="chapter"data-level="7.2.3"data-path="r-vektoriai.html"><a href="r-vektoriai.html#vektoriaus-elementu-pasirinkimas"><i class="fa fa-check"></i><b>7.2.3</b> Vektoriaus elementų pasirinkimas</a><ul><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#pasirinkimas-pagal-elemento-pavadinima"><i class="fa fa-check"></i>Pasirinkimas pagal elemento pavadinimą</a></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#teigiami-skaitiniai-indeksai"><i class="fa fa-check"></i>Teigiami skaitiniai indeksai</a></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#neigiami-skaitiniai-indeksai"><i class="fa fa-check"></i>Neigiami skaitiniai indeksai</a></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#pasirinkimas-pagal-salygas-logini-indeksa"><i class="fa fa-check"></i>Pasirinkimas pagal sąlygas (loginį indeksą)</a></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#specializuotos-funkcijos-elementams-pasirinkti"><i class="fa fa-check"></i>Specializuotos funkcijos elementams pasirinkti</a></li></ul></li><li class="chapter"data-level="7.2.4"data-path="r-vektoriai.html"><a href="r-vektoriai.html#vektoriaus-elementu-reiksmiu-pakeitimas"><i class="fa fa-check"></i><b>7.2.4</b> Vektoriaus elementų reikšmių pakeitimas</a></li><li class="chapter"data-level="7.2.5"data-path="r-vektoriai.html"><a href="r-vektoriai.html#vektorizacija"><i class="fa fa-check"></i><b>7.2.5</b> Vektorizuotos operacijos</a></li></ul></li><li class="chapter"data-level="7.3"data-path="r-vektoriai.html"><a href="r-vektoriai.html#r-tekstiniai-kintamieji"><i class="fa fa-check"></i><b>7.3</b> Darbas su tekstiniais kintamaisiais</a></li><li class="chapter"data-level="7.4"data-path="r-vektoriai.html"><a href="r-vektoriai.html#r-kategoriniu-reiksmiu-sekos"><i class="fa fa-check"></i><b>7.4</b> Darbas su kategoriniais kintamaisiais</a><ul><li class="chapter"data-level="7.4.1"data-path="r-vektoriai.html"><a href="r-vektoriai.html#faktoriu-kurimas"><i class="fa fa-check"></i><b>7.4.1</b> Faktorių kūrimas</a></li><li class="chapter"data-level="7.4.2"data-path="r-vektoriai.html"><a href="r-vektoriai.html#faktoriu-analize"><i class="fa fa-check"></i><b>7.4.2</b> Faktorių pertvarkymas ir analizė</a></li></ul></li><li class="chapter"data-level="7.5"data-path="r-vektoriai.html"><a href="r-vektoriai.html#r-skaiciu-sekos"><i class="fa fa-check"></i><b>7.5</b> Darbas su skaitiniais kintamaisiais</a><ul><li class="chapter"data-level="7.5.1"data-path="r-vektoriai.html"><a href="r-vektoriai.html#skaiciu-seku-kurimas"><i class="fa fa-check"></i><b>7.5.1</b> Skaičių sekų kūrimas</a><ul><li><a href="r-vektoriai.html#operatorius">Operatorius <code>:</code></a></li><li><a href="r-vektoriai.html#funkcija-seq">Funkcija <strong><em>seq()</em></strong></a></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#atsitiktines-sekos-is-galimu-reiksmiu-aibes"><i class="fa fa-check"></i>Atsitiktinės sekos iš galimų reikšmių aibės</a></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#atsitiktiniu-skaiciu-sekos-statistiniai-desniai"><i class="fa fa-check"></i>Atsitiktinių skaičių sekos: statistiniai dėsniai</a></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#atkartojamas-atsitiktinumas"><i class="fa fa-check"></i>Atkartojamas atsitiktinumas</a></li></ul></li><li class="chapter"data-level="7.5.2"data-path="r-vektoriai.html"><a href="r-vektoriai.html#r-aritmetika"><i class="fa fa-check"></i><b>7.5.2</b> <strong><em>R</em></strong> kaip kalkuliatorius</a><ul><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#pavyzdziai-num"><i class="fa fa-check"></i>Pavyzdžiai</a></li></ul></li><li class="chapter"data-level="7.5.3"data-path="r-vektoriai.html"><a href="r-vektoriai.html#suvestines-skaiciams"><i class="fa fa-check"></i><b>7.5.3</b> Skaitinių kintamųjų suvestinės</a></li><li class="chapter"data-level="7.5.4"data-path="r-vektoriai.html"><a href="r-vektoriai.html#skaiciu-kategorizavimas"><i class="fa fa-check"></i><b>7.5.4</b> Skaitinio kintamojo reikšmių kategorizavimas</a></li><li class="chapter"data-level="7.5.5"data-path="r-vektoriai.html"><a href="r-vektoriai.html#skaiciu-formatavimas"><i class="fa fa-check"></i><b>7.5.5</b> Skaičių formatavimas</a></li></ul></li><li class="chapter"data-level="7.6"data-path="r-vektoriai.html"><a href="r-vektoriai.html#r-loginiu-reiksmiu-sekos"><i class="fa fa-check"></i><b>7.6</b> Darbas su loginiais kintamaisiais</a><ul><li class="chapter"data-level="7.6.1"data-path="r-vektoriai.html"><a href="r-vektoriai.html#palyginimas"><i class="fa fa-check"></i><b>7.6.1</b> Palyginimo operacijos</a></li><li class="chapter"data-level="7.6.2"data-path="r-vektoriai.html"><a href="r-vektoriai.html#logines-operacijos"><i class="fa fa-check"></i><b>7.6.2</b> Loginės operacijos</a></li><li class="chapter"data-level="7.6.3"data-path="r-vektoriai.html"><a href="r-vektoriai.html#lgl_to_num"><i class="fa fa-check"></i><b>7.6.3</b> Loginiai kintamieji kaip skaičiai</a></li></ul></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#r-vektoriai-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="8"data-path="teorija-grafikai.html"><a href="teorija-grafikai.html"><i class="fa fa-check"></i><b>8</b> Grafikai (teorija)</a><ul><li class="chapter"data-level="8.1"data-path="teorija-grafikai.html"><a href="teorija-grafikai.html#grafikai-vieno-kintamojo-apibendrinimui"><i class="fa fa-check"></i><b>8.1</b> Grafikai vieno kintamojo apibendrinimui</a><ul><li class="chapter"data-level="8.1.1"data-path="teorija-grafikai.html"><a href="teorija-grafikai.html#kategoriniams-duomenims"><i class="fa fa-check"></i><b>8.1.1</b> Kategoriniams duomenims</a></li><li class="chapter"data-level="8.1.2"data-path="teorija-grafikai.html"><a href="teorija-grafikai.html#tolydiesiems-duomenims"><i class="fa fa-check"></i><b>8.1.2</b> Tolydiesiems duomenims</a></li></ul></li><li class="chapter"data-level="8.2"data-path="teorija-grafikai.html"><a href="teorija-grafikai.html#diagramu-palyginimas"><i class="fa fa-check"></i><b>8.2</b> Diagramų palyginimas</a></li><li class="chapter"data-level=""data-path="teorija-grafikai.html"><a href="teorija-grafikai.html#teorija-grafikai-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="9"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html"><i class="fa fa-check"></i><b>9</b> <strong><em>R Commander</em></strong>: pagrindai ir aprašomoji statistika</a><ul><li class="chapter"data-level="9.1"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#r-commander-diegimas-ir-ijungimas"><i class="fa fa-check"></i><b>9.1</b> <strong><em>R Commander</em></strong> diegimas ir įjungimas</a></li><li class="chapter"data-level="9.2"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#r-commander-konfiguravimas"><i class="fa fa-check"></i><b>9.2</b> <strong><em>R Commander</em></strong> konfigūravimas</a></li><li class="chapter"data-level="9.3"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#duomenu-ikelimas-i-r"><i class="fa fa-check"></i><b>9.3</b> Duomenų įkėlimas į <strong><em>R</em></strong></a><ul><li class="chapter"data-level="9.3.1"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#r-objektu-pavadinimai-2"><i class="fa fa-check"></i><b>9.3.1</b> <strong><em>R</em></strong> objektų pavadinimai</a></li><li class="chapter"data-level="9.3.2"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#delim-duomenys"><i class="fa fa-check"></i><b>9.3.2</b> Skirtukais atskirtų reikšmių (SAR) formatas</a></li><li class="chapter"data-level="9.3.3"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#pastabos-apie-programos-r-formatu-duomenis"><i class="fa fa-check"></i><b>9.3.3</b> Pastabos apie programos <strong><em>R</em></strong> formatų duomenis</a></li></ul></li><li class="chapter"data-level="9.4"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#duomenu-perziura"><i class="fa fa-check"></i><b>9.4</b> Duomenų lentelės peržiūra</a><ul><li class="chapter"data-level="9.4.1"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#duomenys-kuriuos-naudosime"><i class="fa fa-check"></i><b>9.4.1</b> Duomenys, kuriuos naudosime</a></li><li class="chapter"data-level="9.4.2"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#pagrindines-perziuros-funkcijos"><i class="fa fa-check"></i><b>9.4.2</b> Pagrindinės peržiūros funkcijos</a></li><li class="chapter"data-level="9.4.3"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#kaip-atpazinti-stulpeliuose-esanciu-duomenu-klases"><i class="fa fa-check"></i><b>9.4.3</b> Kaip atpažinti stulpeliuose esančių duomenų klases?</a></li><li class="chapter"data-level="9.4.4"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#teorinis-duomenu-tipas-ir-jam-tinkama-r-klase"><i class="fa fa-check"></i><b>9.4.4</b> Teorinis duomenų tipas ir jam tinkama <strong><em>R</em></strong> klasė</a></li></ul></li><li class="chapter"data-level="9.5"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#kintamuju-klases-keitimas"><i class="fa fa-check"></i><b>9.5</b> Kintamųjų klasės keitimas</a></li><li class="chapter"data-level="9.6"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#reiksmiu-perskaiciavimas-ar-perkodavimas"><i class="fa fa-check"></i><b>9.6</b> Reikšmių perskaičiavimas ar perkodavimas</a></li><li class="chapter"data-level="9.7"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#rcmdr-grafikai"><i class="fa fa-check"></i><b>9.7</b> Grafikai</a><ul><li class="chapter"data-level="9.7.1"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#grafiku-issaugojimas-redaguojamu-formatu"><i class="fa fa-check"></i><b>9.7.1</b> Grafikų išsaugojimas redaguojamu formatu</a></li></ul></li><li class="chapter"data-level="9.8"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#programos-kodo-elementai"><i class="fa fa-check"></i><b>9.8</b> Programos kodo elementai</a><ul><li class="chapter"data-level="9.8.1"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#duomenu-lenteliu-sudarymas-is-vektoriu"><i class="fa fa-check"></i><b>9.8.1</b> Duomenų lentelių sudarymas iš vektorių</a></li><li class="chapter"data-level="9.8.2"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#duomenu-lenteles-stulpeliu-vertimas-vektoriais"><i class="fa fa-check"></i><b>9.8.2</b> Duomenų lentelės stulpelių vertimas vektoriais</a></li><li class="chapter"data-level="9.8.3"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#jungimo-operatorius"><i class="fa fa-check"></i><b>9.8.3</b> Jungimo operatorius <code>%&gt;%</code></a></li></ul></li></ul></li><li class="part"><span><b>Analizė</b></span></li><li class="chapter"data-level="10"data-path="skirstiniai.html"><a href="skirstiniai.html"><i class="fa fa-check"></i><b>10</b> Atsitiktiniai dydžiai ir skirstiniai</a><ul><li class="chapter"data-level="10.1"data-path="skirstiniai.html"><a href="skirstiniai.html#apie-pratybas"><i class="fa fa-check"></i><b>10.1</b> Apie pratybas</a></li><li class="chapter"data-level="10.2"data-path="skirstiniai.html"><a href="skirstiniai.html#tikimybiu-teorijos-elementai"><i class="fa fa-check"></i><b>10.2</b> Tikimybių teorijos elementai</a><ul><li class="chapter"data-level="10.2.1"data-path="skirstiniai.html"><a href="skirstiniai.html#tikimybiniai-eksperimentai-ir-ivykiai"><i class="fa fa-check"></i><b>10.2.1</b> Tikimybiniai eksperimentai ir įvykiai</a></li><li class="chapter"data-level="10.2.2"data-path="skirstiniai.html"><a href="skirstiniai.html#atsitiktinis-dydis"><i class="fa fa-check"></i><b>10.2.2</b> Atsitiktinis dydis</a></li><li class="chapter"data-level="10.2.3"data-path="skirstiniai.html"><a href="skirstiniai.html#tikimybe"><i class="fa fa-check"></i><b>10.2.3</b> Tikimybė</a></li><li class="chapter"data-level="10.2.4"data-path="skirstiniai.html"><a href="skirstiniai.html#skirstiniai-1"><i class="fa fa-check"></i><b>10.2.4</b> Skirstiniai</a></li></ul></li><li class="chapter"data-level="10.3"data-path="skirstiniai.html"><a href="skirstiniai.html#tikimybiniai-atsitiktiniu-dydziu-modeliai"><i class="fa fa-check"></i><b>10.3</b> Tikimybiniai atsitiktinių dydžių modeliai</a><ul><li class="chapter"data-level="10.3.1"data-path="skirstiniai.html"><a href="skirstiniai.html#binominis"><i class="fa fa-check"></i><b>10.3.1</b> Binominis skirstinys</a></li><li class="chapter"data-level="10.3.2"data-path="skirstiniai.html"><a href="skirstiniai.html#puasono"><i class="fa fa-check"></i><b>10.3.2</b> Puasono skirstinys</a></li><li class="chapter"data-level="10.3.3"data-path="skirstiniai.html"><a href="skirstiniai.html#binominio-skirstinio-aproksimacija-puasono-skirstiniu"><i class="fa fa-check"></i><b>10.3.3</b> Binominio skirstinio aproksimacija Puasono skirstiniu</a></li><li class="chapter"data-level="10.3.4"data-path="skirstiniai.html"><a href="skirstiniai.html#geometrinis"><i class="fa fa-check"></i><b>10.3.4</b> Geometrinis skirstinys</a></li><li class="chapter"data-level="10.3.5"data-path="skirstiniai.html"><a href="skirstiniai.html#neig-binominis"><i class="fa fa-check"></i><b>10.3.5</b> Neigiamas binominis skirstinys</a></li><li class="chapter"data-level="10.3.6"data-path="skirstiniai.html"><a href="skirstiniai.html#normalusis"><i class="fa fa-check"></i><b>10.3.6</b> Normalusis skirstinys</a></li><li class="chapter"data-level="10.3.7"data-path="skirstiniai.html"><a href="skirstiniai.html#log-normalusis"><i class="fa fa-check"></i><b>10.3.7</b> Log-normalusis skirstinys</a></li></ul></li><li class="chapter"data-level="10.4"data-path="skirstiniai.html"><a href="skirstiniai.html#skirstiniai-r"><i class="fa fa-check"></i><b>10.4</b> Skirstiniai programoje <em>R</em></a><ul><li class="chapter"data-level="10.4.1"data-path="skirstiniai.html"><a href="skirstiniai.html#tikimybės-rcmdr"><i class="fa fa-check"></i><b>10.4.1</b> <em>R Commander</em> tikimybių skaičiuoklės</a></li></ul></li><li class="chapter"data-level="10.5"data-path="skirstiniai.html"><a href="skirstiniai.html#tikimybes-geogebra"><i class="fa fa-check"></i><b>10.5</b> Programos <em>GeoGebra</em> tikimybių skaičiuoklė</a></li><li class="chapter"data-level="10.6"data-path="skirstiniai.html"><a href="skirstiniai.html#skirstiniai-ir-tikimybiniai-uzdaviniai"><i class="fa fa-check"></i><b>10.6</b> Skirstiniai ir tikimybiniai uždaviniai</a><ul><li class="chapter"data-level="10.6.1"data-path="skirstiniai.html"><a href="skirstiniai.html#zinome-tikimybe-kaip-rasti-kvantili"><i class="fa fa-check"></i><b>10.6.1</b> Žinome tikimybę, kaip rasti kvantilį?</a></li><li class="chapter"data-level="10.6.2"data-path="skirstiniai.html"><a href="skirstiniai.html#zinome-kvantili-kaip-rasti-tikimybe"><i class="fa fa-check"></i><b>10.6.2</b> Žinome kvantilį, kaip rasti tikimybę?</a></li><li class="chapter"data-level="10.6.3"data-path="skirstiniai.html"><a href="skirstiniai.html#zinome-reiksme-kaip-rasti-jos-igijimo-tikimybetikimybes-tanki"><i class="fa fa-check"></i><b>10.6.3</b> Žinome reikšmę, kaip rasti jos įgijimo tikimybę/tikimybės tankį?</a></li><li class="chapter"data-level="10.6.4"data-path="skirstiniai.html"><a href="skirstiniai.html#tikimybiniu-uzdaviniu-pavyzdziai"><i class="fa fa-check"></i><b>10.6.4</b> Tikimybinių uždavinių pavyzdžiai</a></li></ul></li></ul></li><li class="chapter"data-level="11"data-path="skirstinio-parinkimas.html"><a href="skirstinio-parinkimas.html"><i class="fa fa-check"></i><b>11</b> Skirstinio parinkimas duomenims</a><ul><li class="chapter"data-level="11.1"data-path="skirstinio-parinkimas.html"><a href="skirstinio-parinkimas.html#gof-statistikos"><i class="fa fa-check"></i><b>11.1</b> Skaitiniai būdai modelio ir duomenų suderinamumui vertinti</a></li><li class="chapter"data-level="11.2"data-path="skirstinio-parinkimas.html"><a href="skirstinio-parinkimas.html#paketas-fitdistrplus-teoriniam-modeliui-parinkti"><i class="fa fa-check"></i><b>11.2</b> Paketas <strong><em>fitdistrplus</em></strong> teoriniam modeliui parinkti</a></li><li class="chapter"data-level="11.3"data-path="skirstinio-parinkimas.html"><a href="skirstinio-parinkimas.html#keliu-modeliu-palyginimas-paketas-fitdistrplus"><i class="fa fa-check"></i><b>11.3</b> Kelių modelių palyginimas (paketas <strong><em>fitdistrplus</em></strong>)</a><ul><li class="chapter"data-level=""data-path="skirstinio-parinkimas.html"><a href="skirstinio-parinkimas.html#palyginimas-grafiskai"><i class="fa fa-check"></i>Palyginimas grafiškai</a></li><li class="chapter"data-level=""data-path="skirstinio-parinkimas.html"><a href="skirstinio-parinkimas.html#gofstat"><i class="fa fa-check"></i>Palyginimas naudojant skaitines statistikas</a></li></ul></li><li class="chapter"data-level="11.4"data-path="skirstinio-parinkimas.html"><a href="skirstinio-parinkimas.html#jei-dazniu-lentele-fitdistrplus"><i class="fa fa-check"></i><b>11.4</b> Jei duomenys pateikti kaip dažnių lentelė (<strong><em>fitdistrplus</em></strong>)</a></li></ul></li><li class="chapter"data-level="12"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html"><i class="fa fa-check"></i><b>12</b> Pasikliautinieji intervalai (PI) klasikiniais metodais</a><ul><li class="chapter"data-level="12.1"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#paketas-desctools"><i class="fa fa-check"></i><b>12.1</b> Paketas <strong><em>DescTools</em></strong></a></li><li class="chapter"data-level="12.2"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#pi-braizymas"><i class="fa fa-check"></i><b>12.2</b> Nubraižyti lentele pateiktus PI</a></li><li class="chapter"data-level="12.3"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#klasikiniai-metodai-pi-skaiciuoti"><i class="fa fa-check"></i><b>12.3</b> Klasikiniai metodai PI skaičiuoti</a></li><li class="chapter"data-level="12.4"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#vidurkio-pi"><i class="fa fa-check"></i><b>12.4</b> Vidurkio PI</a><ul><li class="chapter"data-level="12.4.1"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#z-formule"><i class="fa fa-check"></i><b>12.4.1</b> Vidurkio PI, kai GA dispersija žinoma</a></li><li class="chapter"data-level="12.4.2"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#t-formule"><i class="fa fa-check"></i><b>12.4.2</b> Vidurkio PI, kai GA dispersija nežinoma</a><ul><li><a href="pi-klasikiniai.html#rcmdr-vidurkio-pi-skaiciavimui"><strong><em>Rcmdr</em></strong> vidurkio PI skaičiavimui</a></li></ul></li><li class="chapter"data-level="12.4.3"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#n-from-z-formula"><i class="fa fa-check"></i><b>12.4.3</b> Imties dydžio skaičiavimas norimam vidurkio PI ilgiui</a></li></ul></li><li class="chapter"data-level="12.5"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#pi-proporcijai"><i class="fa fa-check"></i><b>12.5</b> Proporcijos PI</a><ul><li class="chapter"data-level="12.5.1"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#pavyzdys-1-triusiai"><i class="fa fa-check"></i><b>12.5.1</b> Pavyzdys 1: triušiai</a></li><li class="chapter"data-level="12.5.2"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#pavyzdys-2-rasine-ivairove"><i class="fa fa-check"></i><b>12.5.2</b> Pavyzdys 2: rasinė įvairovė</a></li><li class="chapter"data-level="12.5.3"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#pavyzdys-3-grupes-pagal-ugi"><i class="fa fa-check"></i><b>12.5.3</b> Pavyzdys 3: grupės pagal ūgį</a></li></ul></li></ul></li><li class="chapter"data-level="13"data-path="pi-saviranka.html"><a href="pi-saviranka.html"><i class="fa fa-check"></i><b>13</b> Pasikliautinieji intervalai savirankos metodais</a><ul><li class="chapter"data-level="13.1"data-path="pi-saviranka.html"><a href="pi-saviranka.html#paketas-desctools-1"><i class="fa fa-check"></i><b>13.1</b> Paketas <strong><em>DescTools</em></strong></a></li><li class="chapter"data-level="13.2"data-path="pi-saviranka.html"><a href="pi-saviranka.html#savirankos-metodai"><i class="fa fa-check"></i><b>13.2</b> Savirankos metodai</a></li><li class="chapter"data-level="13.3"data-path="pi-saviranka.html"><a href="pi-saviranka.html#teorine-medziaga"><i class="fa fa-check"></i><b>13.3</b> Teorinė medžiaga</a></li><li class="chapter"data-level="13.4"data-path="pi-saviranka.html"><a href="pi-saviranka.html#savirankos-metodai-ir-imties-dydis"><i class="fa fa-check"></i><b>13.4</b> Savirankos metodai ir imties dydis</a></li><li class="chapter"data-level="13.5"data-path="pi-saviranka.html"><a href="pi-saviranka.html#baziniai-principai"><i class="fa fa-check"></i><b>13.5</b> Baziniai principai</a><ul><li class="chapter"data-level="13.5.1"data-path="pi-saviranka.html"><a href="pi-saviranka.html#analize-i-etapas"><i class="fa fa-check"></i><b>13.5.1</b> Analizė: I etapas</a></li><li class="chapter"data-level="13.5.2"data-path="pi-saviranka.html"><a href="pi-saviranka.html#analize-ii-etapas"><i class="fa fa-check"></i><b>13.5.2</b> Analizė: II etapas</a></li><li class="chapter"data-level="13.5.3"data-path="pi-saviranka.html"><a href="pi-saviranka.html#analize-iii-etapas"><i class="fa fa-check"></i><b>13.5.3</b> Analizė: III etapas</a></li></ul></li><li class="chapter"data-level="13.6"data-path="pi-saviranka.html"><a href="pi-saviranka.html#paketas-boot"><i class="fa fa-check"></i><b>13.6</b> Paketas „<strong>boot</strong>“</a><ul><li class="chapter"data-level="13.6.1"data-path="pi-saviranka.html"><a href="pi-saviranka.html#pavyzdys-vidurkio-pi"><i class="fa fa-check"></i><b>13.6.1</b> Pavyzdys: vidurkio PI</a></li><li class="chapter"data-level="13.6.2"data-path="pi-saviranka.html"><a href="pi-saviranka.html#pavyzdys-medianos-pi"><i class="fa fa-check"></i><b>13.6.2</b> Pavyzdys: medianos PI</a></li><li class="chapter"data-level="13.6.3"data-path="pi-saviranka.html"><a href="pi-saviranka.html#pavyzdys-koreliacijos-koeficiento-pi"><i class="fa fa-check"></i><b>13.6.3</b> Pavyzdys: koreliacijos koeficiento PI</a></li></ul></li></ul></li><li class="chapter"data-level="14"data-path="ht-ivadas.html"><a href="ht-ivadas.html"><i class="fa fa-check"></i><b>14</b> Hipotezių tikrinimas: įvadas</a><ul><li class="chapter"data-level="14.1"data-path="ht-ivadas.html"><a href="ht-ivadas.html#svarbiausios-savokos"><i class="fa fa-check"></i><b>14.1</b> Svarbiausios sąvokos</a></li><li class="chapter"data-level="14.2"data-path="ht-ivadas.html"><a href="ht-ivadas.html#prielaidos-ir-reikalavimai"><i class="fa fa-check"></i><b>14.2</b> Prielaidos ir reikalavimai</a></li><li class="chapter"data-level="14.3"data-path="ht-ivadas.html"><a href="ht-ivadas.html#parametriniai-vs-neparametriniai"><i class="fa fa-check"></i><b>14.3</b> Parametriniai ir neparametriniai kriterijai</a></li><li class="chapter"data-level="14.4"data-path="ht-ivadas.html"><a href="ht-ivadas.html#rekomendacija-kaip-atlikti-statistiniu-hipoteziu-tikrinima"><i class="fa fa-check"></i><b>14.4</b> Rekomendacija, kaip atlikti statistinių hipotezių tikrinimą</a></li><li class="chapter"data-level="14.5"data-path="ht-ivadas.html"><a href="ht-ivadas.html#schemos-metodams-pasirinkti"><i class="fa fa-check"></i><b>14.5</b> Schemos metodams pasirinkti</a></li><li class="chapter"data-level="14.6"data-path="ht-ivadas.html"><a href="ht-ivadas.html#praktiniai-patarimai"><i class="fa fa-check"></i><b>14.6</b> Praktiniai patarimai</a><ul><li class="chapter"data-level="14.6.1"data-path="ht-ivadas.html"><a href="ht-ivadas.html#teisingas-duomenu-nuskaitymas"><i class="fa fa-check"></i><b>14.6.1</b> Teisingas duomenų nuskaitymas</a></li></ul></li></ul></li><li class="chapter"data-level="15"data-path="ht-suderinamumas-ir-proporcijos.html"><a href="ht-suderinamumas-ir-proporcijos.html"><i class="fa fa-check"></i><b>15</b> Suderinamumo ir proporcijų homogeniškumo tikrinimas</a><ul><li class="chapter"data-level="15.1"data-path="ht-suderinamumas-ir-proporcijos.html"><a href="ht-suderinamumas-ir-proporcijos.html#suderinamumo-uzdavinys"><i class="fa fa-check"></i><b>15.1</b> Suderinamumo uždavinys</a></li><li class="chapter"data-level="15.2"data-path="ht-suderinamumas-ir-proporcijos.html"><a href="ht-suderinamumas-ir-proporcijos.html#proporciju-homogeniskumo-tikrinimas"><i class="fa fa-check"></i><b>15.2</b> Proporcijų homogeniškumo tikrinimas</a></li></ul></li><li class="chapter"data-level="16"data-path="ht-normalumas.html"><a href="ht-normalumas.html"><i class="fa fa-check"></i><b>16</b> Normalumo tikrinimas</a><ul><li class="chapter"data-level="16.1"data-path="ht-normalumas.html"><a href="ht-normalumas.html#normalumo-tikrinimas"><i class="fa fa-check"></i><b>16.1</b> Pasirinkimų schema</a></li><li class="chapter"data-level="16.2"data-path="ht-normalumas.html"><a href="ht-normalumas.html#statistiniai-kriterijai-normalumui-tikrinti"><i class="fa fa-check"></i><b>16.2</b> Statistiniai kriterijai normalumui tikrinti</a><ul><li class="chapter"data-level="16.2.1"data-path="ht-normalumas.html"><a href="ht-normalumas.html#statistines-hipotezes-tikrinant-normaluma"><i class="fa fa-check"></i><b>16.2.1</b> Statistinės hipotezės tikrinant normalumą</a></li></ul></li><li class="chapter"data-level="16.3"data-path="ht-normalumas.html"><a href="ht-normalumas.html#gof-grafikai"><i class="fa fa-check"></i><b>16.3</b> Grafiniai būdai normalumui tikrinti</a><ul><li class="chapter"data-level="16.3.1"data-path="ht-normalumas.html"><a href="ht-normalumas.html#qq-diagrama"><i class="fa fa-check"></i><b>16.3.1</b> Kvantilių palyginimo (qq) diagrama</a></li><li class="chapter"data-level="16.3.2"data-path="ht-normalumas.html"><a href="ht-normalumas.html#tikimybiu-palyginimo-pp-diagrama"><i class="fa fa-check"></i><b>16.3.2</b> Tikimybių palyginimo (pp) diagrama</a></li><li class="chapter"data-level="16.3.3"data-path="ht-normalumas.html"><a href="ht-normalumas.html#kitu-tipu-grafikai"><i class="fa fa-check"></i><b>16.3.3</b> Kitų tipų grafikai</a></li></ul></li><li class="chapter"data-level="16.4"data-path="ht-normalumas.html"><a href="ht-normalumas.html#kaip-atlikti-kompiuteriu"><i class="fa fa-check"></i><b>16.4</b> Kaip atlikti kompiuteriu?</a><ul><li class="chapter"data-level="16.4.1"data-path="ht-normalumas.html"><a href="ht-normalumas.html#programos-kodas-normalumui-tikrinti"><i class="fa fa-check"></i><b>16.4.1</b> Programos kodas normalumui tikrinti</a></li><li class="chapter"data-level="16.4.2"data-path="ht-normalumas.html"><a href="ht-normalumas.html#r-commander-normalumui-tikrinti"><i class="fa fa-check"></i><b>16.4.2</b> <strong><em>R Commander</em></strong> normalumui tikrinti</a></li><li class="chapter"data-level="16.4.3"data-path="ht-normalumas.html"><a href="ht-normalumas.html#rcmdrplugin.biostat-normalumui-tikrinti"><i class="fa fa-check"></i><b>16.4.3</b> <strong><em>RcmdrPlugin.biostat</em></strong> normalumui tikrinti</a></li></ul></li></ul></li><li class="chapter"data-level="17"data-path="ht-sklaida.html"><a href="ht-sklaida.html"><i class="fa fa-check"></i><b>17</b> Sklaidos lyginimas</a><ul><li class="chapter"data-level="17.1"data-path="ht-sklaida.html"><a href="ht-sklaida.html#dispersiju-lyginimas"><i class="fa fa-check"></i><b>17.1</b> Dispersijų lyginimas</a></li><li class="chapter"data-level="17.2"data-path="ht-sklaida.html"><a href="ht-sklaida.html#dispersiju-lyginimas"><i class="fa fa-check"></i><b>17.2</b> Kriterijai dispersijoms lyginti</a></li><li class="chapter"data-level="17.3"data-path="ht-sklaida.html"><a href="ht-sklaida.html#pasirinkimu-schema"><i class="fa fa-check"></i><b>17.3</b> Pasirinkimų schema</a></li><li class="chapter"data-level="17.4"data-path="ht-sklaida.html"><a href="ht-sklaida.html#statistines-hipotezes"><i class="fa fa-check"></i><b>17.4</b> Statistinės hipotezės</a></li><li class="chapter"data-level="17.5"data-path="ht-sklaida.html"><a href="ht-sklaida.html#kaip-atlikti-kompiuteriu-1"><i class="fa fa-check"></i><b>17.5</b> Kaip atlikti kompiuteriu?</a><ul><li class="chapter"data-level="17.5.1"data-path="ht-sklaida.html"><a href="ht-sklaida.html#programos-kodas-dispersijoms-lyginti"><i class="fa fa-check"></i><b>17.5.1</b> Programos kodas dispersijoms lyginti</a><ul><li class="chapter"data-level="17.5.1.1"data-path="ht-sklaida.html"><a href="ht-sklaida.html#chi-kvadratu-kriterijus-vienos-imties-dispersijai-lyginti-su-reiksme"><i class="fa fa-check"></i><b>17.5.1.1</b> Chi-kvadratu kriterijus vienos imties dispersijai lyginti su reikšme</a></li><li class="chapter"data-level="17.5.1.2"data-path="ht-sklaida.html"><a href="ht-sklaida.html#f-kriterijus-dvieju-imciu-dispersijoms-lyginti"><i class="fa fa-check"></i><b>17.5.1.2</b> <em>F</em> kriterijus dviejų imčių dispersijoms lyginti</a></li><li class="chapter"data-level="17.5.1.3"data-path="ht-sklaida.html"><a href="ht-sklaida.html#bartlett-kriterijus-keliu-imciu-dispersijoms-lyginti"><i class="fa fa-check"></i><b>17.5.1.3</b> Bartlett kriterijus kelių imčių dispersijoms lyginti</a></li><li class="chapter"data-level="17.5.1.4"data-path="ht-sklaida.html"><a href="ht-sklaida.html#levene-ir-brown-forsythe-kriterijai-keliu-imciu-dispersijoms-lyginti"><i class="fa fa-check"></i><b>17.5.1.4</b> Levene ir Brown-Forsythe kriterijai kelių imčių dispersijoms lyginti</a></li></ul></li><li class="chapter"data-level="17.5.2"data-path="ht-sklaida.html"><a href="ht-sklaida.html#r-commander-dispersijoms-lyginti"><i class="fa fa-check"></i><b>17.5.2</b> <strong><em>R Commander</em></strong> dispersijoms lyginti</a></li></ul></li></ul></li><li class="chapter"data-level="18"data-path="ht-padetis.html"><a href="ht-padetis.html"><i class="fa fa-check"></i><b>18</b> Skirstinių padėties lyginimas (1-2 imtims)</a><ul><li class="chapter"data-level="18.1"data-path="ht-padetis.html"><a href="ht-padetis.html#centro-padeties-lyginimas-1"><i class="fa fa-check"></i><b>18.1</b> Kriterijai (centro) padėčiai lyginti</a></li><li class="chapter"data-level="18.2"data-path="ht-padetis.html"><a href="ht-padetis.html#statistines-hipotezes-parametriniai-kriterijai"><i class="fa fa-check"></i><b>18.2</b> Statistinės hipotezės: parametriniai kriterijai</a></li><li class="chapter"data-level="18.3"data-path="ht-padetis.html"><a href="ht-padetis.html#statistines-hipotezes-neparametriniai-kriterijai"><i class="fa fa-check"></i><b>18.3</b> Statistinės hipotezės: neparametriniai kriterijai</a></li><li class="chapter"data-level="18.4"data-path="ht-padetis.html"><a href="ht-padetis.html#pasirinkimu-schema-1"><i class="fa fa-check"></i><b>18.4</b> Pasirinkimų schema</a></li><li class="chapter"data-level="18.5"data-path="ht-padetis.html"><a href="ht-padetis.html#kaip-atlikti"><i class="fa fa-check"></i><b>18.5</b> Kaip atlikti?</a></li><li class="chapter"data-level="18.6"data-path="ht-padetis.html"><a href="ht-padetis.html#kaip-aprasyti-rezultatus"><i class="fa fa-check"></i><b>18.6</b> Kaip aprašyti rezultatus?</a></li></ul></li><li class="chapter"data-level="19"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html"><i class="fa fa-check"></i><b>19</b> ANOVA ir jos analogai</a><ul><li class="chapter"data-level="19.1"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#kas-yra-anova"><i class="fa fa-check"></i><b>19.1</b> Kas yra ANOVA?</a><ul><li class="chapter"data-level="19.1.1"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#ANOVA-ir-analogai"><i class="fa fa-check"></i><b>19.1.1</b> Kurį vienfaktorės ANOVA variantą ar analogą pasirinkti?</a></li></ul></li><li class="chapter"data-level="19.2"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#issamios-ANOVA-aspektai"><i class="fa fa-check"></i><b>19.2</b> Išsamios ANOVA analizės aspektai</a><ul><li class="chapter"data-level="19.2.1"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#eiga"><i class="fa fa-check"></i><b>19.2.1</b> Eiga</a></li><li class="chapter"data-level="19.2.2"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#klausimas"><i class="fa fa-check"></i><b>19.2.2</b> Klausimas</a></li><li class="chapter"data-level="19.2.3"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#duomenys"><i class="fa fa-check"></i><b>19.2.3</b> Duomenys</a></li><li class="chapter"data-level="19.2.4"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#duomenu-suvestines"><i class="fa fa-check"></i><b>19.2.4</b> Duomenų suvestinės</a></li><li class="chapter"data-level="19.2.5"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#duomenu-formatas-ilgasis"><i class="fa fa-check"></i><b>19.2.5</b> Duomenų formatas: ilgasis</a></li><li class="chapter"data-level="19.2.6"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#modelio-formule"><i class="fa fa-check"></i><b>19.2.6</b> Modelio formulė</a></li><li class="chapter"data-level="19.2.7"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#grafikai"><i class="fa fa-check"></i><b>19.2.7</b> Grafikai</a></li><li class="chapter"data-level="19.2.8"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#duomenu-pasiskirstymo-normalumo-tikrinimas-grupems"><i class="fa fa-check"></i><b>19.2.8</b> Duomenų pasiskirstymo normalumo tikrinimas grupėms</a></li><li class="chapter"data-level="19.2.9"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#dispersiju-homogeniskumo-tikrinimas"><i class="fa fa-check"></i><b>19.2.9</b> Dispersijų homogeniškumo tikrinimas</a></li><li class="chapter"data-level="19.2.10"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#tinkamo-anova-varianto-ar-analogo-pasirinkimas"><i class="fa fa-check"></i><b>19.2.10</b> Tinkamo ANOVA varianto ar analogo pasirinkimas</a></li><li class="chapter"data-level="19.2.11"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#cld"><i class="fa fa-check"></i><b>19.2.11</b> Kompaktiškas raidinis žymėjimas (<em>cld</em>)</a></li><li class="chapter"data-level="19.2.12"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#ANOVA-rezultatu-aprasymas"><i class="fa fa-check"></i><b>19.2.12</b> Rezultatų aprašymas</a><ul><li class="chapter"data-level=""data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#anova-rezultatai"><i class="fa fa-check"></i>ANOVA rezultatai</a></li><li class="chapter"data-level=""data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#welch-anova-rezultatai"><i class="fa fa-check"></i>Welch ANOVA rezultatai</a></li><li class="chapter"data-level=""data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#kruskal-wallis-analizes-rezultatai"><i class="fa fa-check"></i>Kruskal-Wallis analizės rezultatai</a></li><li><a href="ht-anova-ir-analogai.html#post-hoc-analizes-rezultatai"><em>Post-hoc</em> analizės rezultatai</a></li></ul></li></ul></li><li class="chapter"data-level="19.3"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#programos-kodai-analizei"><i class="fa fa-check"></i><b>19.3</b> Programos kodai analizei</a><ul><li class="chapter"data-level="19.3.1"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#anova"><i class="fa fa-check"></i><b>19.3.1</b> ANOVA</a></li><li class="chapter"data-level="19.3.2"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#Welch-F-pvz"><i class="fa fa-check"></i><b>19.3.2</b> Welch ANOVA (Welch F kriterijus)</a></li><li class="chapter"data-level="19.3.3"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#kruskal-wallis-kriterijus"><i class="fa fa-check"></i><b>19.3.3</b> Kruskal-Wallis kriterijus</a></li><li class="chapter"data-level="19.3.4"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#post-hoc-tukey-hsd-kriterijus"><i class="fa fa-check"></i><b>19.3.4</b> <em>Post-hoc:</em> Tukey HSD kriterijus</a></li><li class="chapter"data-level="19.3.5"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#post-hoc-games-howell-kriterijus"><i class="fa fa-check"></i><b>19.3.5</b> <em>Post-hoc:</em> Games-Howell kriterijus</a></li><li class="chapter"data-level="19.3.6"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#post-hoc-conover-iman-kriterijus"><i class="fa fa-check"></i><b>19.3.6</b> <em>Post-hoc:</em> Conover-Iman kriterijus</a></li></ul></li><li class="chapter"data-level="19.4"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#pavyzdys-1-kai-duomenys-normalieji-ir-dispersijos-lygios"><i class="fa fa-check"></i><b>19.4</b> Pavyzdys 1: kai duomenys normalieji ir dispersijos lygios</a><ul><li class="chapter"data-level="19.4.1"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#ANOVA-pvz"><i class="fa fa-check"></i><b>19.4.1</b> ANOVA (pagrindinė analizė)</a></li><li class="chapter"data-level="19.4.2"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#tukey-hsd-1"><i class="fa fa-check"></i><b>19.4.2</b> Tukey kriterijus (<em>post-hoc</em> analizė)</a></li></ul></li><li class="chapter"data-level="19.5"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#pavyzdys-2-kai-duomenys-normalieji-bet-dispersijos-nera-lygios"><i class="fa fa-check"></i><b>19.5</b> Pavyzdys 2: kai duomenys normalieji, bet dispersijos nėra lygios</a><ul><li class="chapter"data-level="19.5.1"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#welch-anova-pagrindine-analize"><i class="fa fa-check"></i><b>19.5.1</b> Welch ANOVA (pagrindinė analizė)</a></li><li class="chapter"data-level="19.5.2"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#games-howell-kriterijus-post-hoc-analize"><i class="fa fa-check"></i><b>19.5.2</b> Games-Howell kriterijus (<em>post-hoc</em> analizė)</a></li></ul></li><li class="chapter"data-level="19.6"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#pavyzdys-3-neparametrinis-kriterijus-2-ir-daugiau-grupems-lyginti"><i class="fa fa-check"></i><b>19.6</b> Pavyzdys 3: neparametrinis kriterijus 2 ir daugiau grupėms lyginti</a><ul><li class="chapter"data-level="19.6.1"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#kw-pvz"><i class="fa fa-check"></i><b>19.6.1</b> Kruskal-Wallis kriterijus (pagrindinė analizė)</a></li><li class="chapter"data-level="19.6.2"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#conover-iman-kriterijus-post-hoc-analize"><i class="fa fa-check"></i><b>19.6.2</b> Conover-Iman kriterijus (<em>post-hoc</em> analizė)</a></li></ul></li><li class="chapter"data-level="19.7"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#ANOVA-tipo-analize"><i class="fa fa-check"></i><b>19.7</b> Video pavyzdys</a></li></ul></li><li class="chapter"data-level="20"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html"><i class="fa fa-check"></i><b>20</b> Ryšys tarp kintamųjų</a><ul><li class="chapter"data-level="20.1"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#bendrieji-principai"><i class="fa fa-check"></i><b>20.1</b> Bendrieji principai</a><ul><li class="chapter"data-level="20.1.1"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#sasaja-neparodo-priezastingumo"><i class="fa fa-check"></i><b>20.1.1</b> Sąsaja neparodo priežastingumo</a></li><li class="chapter"data-level="20.1.2"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#statistinis-sasajos-reiksmingumas"><i class="fa fa-check"></i><b>20.1.2</b> Statistinis sąsajos reikšmingumas</a></li><li class="chapter"data-level="20.1.3"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#sasajos-stiprumas"><i class="fa fa-check"></i><b>20.1.3</b> Sąsajos stiprumas</a></li></ul></li><li class="chapter"data-level="20.2"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#koreliacine-analize"><i class="fa fa-check"></i><b>20.2</b> Koreliacinė analizė</a><ul><li class="chapter"data-level="20.2.1"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#kuri-koreliacijos-varianta-pasirinkti"><i class="fa fa-check"></i><b>20.2.1</b> Kurį koreliacijos variantą pasirinkti?</a></li><li class="chapter"data-level="20.2.2"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#prielaidu-ir-kitu-reikalavimu-tikrinimas"><i class="fa fa-check"></i><b>20.2.2</b> Prielaidų ir kitų reikalavimų tikrinimas</a><ul><li class="chapter"data-level=""data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#tiesiskumo-prielaida"><i class="fa fa-check"></i>Tiesiškumo prielaida</a></li><li class="chapter"data-level="20.2.2.1"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#isskirtys"><i class="fa fa-check"></i><b>20.2.2.1</b> Išskirtys</a></li><li class="chapter"data-level=""data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#kor--normalumo-tikrinimas"><i class="fa fa-check"></i>Normaliojo pasiskirstymo prielaida</a></li></ul></li><li class="chapter"data-level="20.2.3"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#rezultatu-aprasymas-koreliacine-analize"><i class="fa fa-check"></i><b>20.2.3</b> Rezultatų aprašymas: koreliacinė analizė</a></li><li class="chapter"data-level="20.2.4"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#simuliacija-pirsono-koreliacija"><i class="fa fa-check"></i><b>20.2.4</b> Simuliacija: Pirsono koreliacijos koeficientas</a></li><li class="chapter"data-level="20.2.5"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#koreliacija-pvz"><i class="fa fa-check"></i><b>20.2.5</b> Pavyzdžiai</a><ul><li class="chapter"data-level=""data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#pavyzdys-1"><i class="fa fa-check"></i>Pavyzdys 1</a></li><li class="chapter"data-level=""data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#pavyzdys-2"><i class="fa fa-check"></i>Pavyzdys 2</a></li></ul></li><li class="chapter"data-level="20.2.6"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#rekomenduojami-informacijos-saltiniai"><i class="fa fa-check"></i><b>20.2.6</b> Rekomenduojami informacijos šaltiniai</a></li></ul></li><li class="chapter"data-level="20.3"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#sasaja-tarp-kategoriniu-kintamuju-reiksmiu"><i class="fa fa-check"></i><b>20.3</b> Sąsaja tarp kategorinių kintamųjų reikšmių</a><ul><li class="chapter"data-level="20.3.1"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#pozymiu-nepriklausomumo-tikrinimas"><i class="fa fa-check"></i><b>20.3.1</b> Požymių nepriklausomumo tikrinimas</a></li><li class="chapter"data-level="20.3.2"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#kategoriniu-kintamuju-rysio-stiprumas"><i class="fa fa-check"></i><b>20.3.2</b> Kategorinių kintamųjų ryšio stiprumas</a></li><li class="chapter"data-level="20.3.3"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#programos-kodai"><i class="fa fa-check"></i><b>20.3.3</b> Programos kodai</a></li><li class="chapter"data-level="20.3.4"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#rekomenduojami-informacijos-saltiniai-1"><i class="fa fa-check"></i><b>20.3.4</b> Rekomenduojami informacijos šaltiniai</a></li></ul></li><li class="chapter"data-level="20.4"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#rysio-tarp-kintamuju-analize-naudojant-r-commander"><i class="fa fa-check"></i><b>20.4</b> Ryšio tarp kintamųjų analizė naudojant <strong><em>R Commander</em></strong></a></li></ul></li><li class="chapter"data-level="21"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html"><i class="fa fa-check"></i><b>21</b> Tiesinė regresija</a><ul><li class="chapter"data-level="21.1"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#regresija"><i class="fa fa-check"></i><b>21.1</b> Regresinė analizė</a><ul><li class="chapter"data-level="21.1.1"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#regresines-analizes-eiga"><i class="fa fa-check"></i><b>21.1.1</b> Regresinės analizės eiga</a></li><li class="chapter"data-level="21.1.2"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#tinkamos-ties-regr-redikliai"><i class="fa fa-check"></i><b>21.1.2</b> Tinkamo tiesinės regresijos modelio rodikliai</a></li><li class="chapter"data-level="21.1.3"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#regresijos-modelio-grafikas-ggplot2-sistema"><i class="fa fa-check"></i><b>21.1.3</b> Regresijos modelio grafikas <em>ggplot2</em> sistema</a></li><li class="chapter"data-level="21.1.4"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#rezultatu-aprasymas-regresija"><i class="fa fa-check"></i><b>21.1.4</b> Rezultatų aprašymas: tiesinė regresinė analizė</a></li></ul></li><li class="chapter"data-level="21.2"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#saltiniai-regresija"><i class="fa fa-check"></i><b>21.2</b> Informacijos šaltiniai</a></li><li class="chapter"data-level="21.3"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#regresine-analize-naudojant-r-commander"><i class="fa fa-check"></i><b>21.3</b> Regresinė analizė naudojant <em>R Commander</em></a><ul><li class="chapter"data-level="21.3.1"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#ties-regr-paprastoji-rcmdr"><i class="fa fa-check"></i><b>21.3.1</b> Paprastoji tiesinė regresija</a><ul><li class="chapter"data-level=""data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#klaibracijos-uzdavinys"><i class="fa fa-check"></i>Kalibracijos uždavinio sprendimas</a></li></ul></li><li class="chapter"data-level="21.3.2"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#ties-regr-daugialype-rcmdr"><i class="fa fa-check"></i><b>21.3.2</b> Daugialypė tiesinė regresija</a></li><li class="chapter"data-level="21.3.3"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#modelio-tobulinimas"><i class="fa fa-check"></i><b>21.3.3</b> Modelio tobulinimas</a></li></ul></li><li class="chapter"data-level="21.4"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#regresijos-pvz-R"><i class="fa fa-check"></i><b>21.4</b> Išsamios tiesinės regresinės analizės pavyzdys</a><ul><li class="chapter"data-level="21.4.1"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#klausimas-problema"><i class="fa fa-check"></i><b>21.4.1</b> Klausimas / Problema</a></li><li class="chapter"data-level="21.4.2"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#duomenys-1"><i class="fa fa-check"></i><b>21.4.2</b> Duomenys</a></li><li class="chapter"data-level="21.4.3"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#nusibraizome-kintamuosius"><i class="fa fa-check"></i><b>21.4.3</b> Nusibraižome kintamuosius</a></li><li class="chapter"data-level="21.4.4"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#ivertiname-koreliacija-tarp-kintamuju"><i class="fa fa-check"></i><b>21.4.4</b> Įvertiname koreliaciją tarp kintamųjų</a></li><li class="chapter"data-level="21.4.5"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#regresijos-lygties-sudarymas"><i class="fa fa-check"></i><b>21.4.5</b> Regresijos lygties sudarymas</a></li><li class="chapter"data-level="21.4.6"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#modelio-suvestine"><i class="fa fa-check"></i><b>21.4.6</b> Modelio suvestinė</a></li><li class="chapter"data-level="21.4.7"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#standartizuotieji-koeficientai"><i class="fa fa-check"></i><b>21.4.7</b> Standartizuotieji koeficientai</a></li><li class="chapter"data-level="21.4.8"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#liekamuju-paklaidu-analize"><i class="fa fa-check"></i><b>21.4.8</b> Liekamųjų paklaidų analizė</a><ul><li class="chapter"data-level=""data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#isskirciu-paieska"><i class="fa fa-check"></i>1. Išskirčių paieška</a></li><li class="chapter"data-level=""data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#paklaidu-normalumo-prielaidos-tikrinimas"><i class="fa fa-check"></i>2. Paklaidų normalumo prielaidos tikrinimas</a></li><li class="chapter"data-level=""data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#prielaidos-kad-paklaidu-vidurkis-lygus-nuliui-tikrinimas"><i class="fa fa-check"></i>3. Prielaidos, kad paklaidų vidurkis lygus nuliui, tikrinimas</a></li><li class="chapter"data-level=""data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#homoskedastiskumo-prielaidos-tikrinimas"><i class="fa fa-check"></i>4. Homoskedastiškumo prielaidos tikrinimas</a></li></ul></li><li class="chapter"data-level="21.4.9"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#tikrinimas-del-multikolinearumo"><i class="fa fa-check"></i><b>21.4.9</b> Tikrinimas dėl multikolinearumo</a></li><li class="chapter"data-level="21.4.10"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#prognozavimas"><i class="fa fa-check"></i><b>21.4.10</b> Prognozavimas</a></li></ul></li></ul></li><li class="appendix"><span><b>Priedai</b></span></li><li class="chapter"data-level="A"data-path="zodynai.html"><a href="zodynai.html"><i class="fa fa-check"></i><b>A</b> Žodynėliai</a><ul><li class="chapter"data-level="A.1"data-path="zodynai.html"><a href="zodynai.html#terminai-komp"><i class="fa fa-check"></i><b>A.1</b> Kompiuterijos terminai</a></li><li class="chapter"data-level="A.2"data-path="zodynai.html"><a href="zodynai.html#terminai-komp-mat"><i class="fa fa-check"></i><b>A.2</b> Programavimo ir matematikos terminai (anglų-lietuvių)</a></li><li class="chapter"data-level="A.3"data-path="zodynai.html"><a href="zodynai.html#terminai-simbpliai"><i class="fa fa-check"></i><b>A.3</b> Simbolių pavadinimai (anglų-lietuvių)</a></li><li class="chapter"data-level="A.4"data-path="zodynai.html"><a href="zodynai.html#terminai-stat"><i class="fa fa-check"></i><b>A.4</b> Statistikos terminai (aiškinamasis žodynas)</a></li><li class="chapter"data-level="A.5"data-path="zodynai.html"><a href="zodynai.html#terminai-stat-en-lt"><i class="fa fa-check"></i><b>A.5</b> Statistikos terminai (anglų-lietuvių)</a></li><li class="chapter"data-level=""data-path="zodynai.html"><a href="zodynai.html#zodynai-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="B"data-path="priedas-r-sesijos-info.html"><a href="priedas-r-sesijos-info.html"><i class="fa fa-check"></i><b>B</b> <strong><em>R</em></strong> sesijos informacija</a></li><li class="chapter"data-level=""data-path="saltiniai.html"><a href="saltiniai.html"><i class="fa fa-check"></i>Informacijos šaltiniai</a></li></ul></nav></div><div class="book-body"><div class="body-inner"><div class="book-header"role="navigation"><h1><i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Biostatistika</a></h1></div><div class="page-wrapper"tabindex="-1"role="main"><div class="page-inner"><section class="normal"id="section-"><div id="ht-anova-ir-analogai"class="section level1"><h1><span class="header-section-number">19. </span>ANOVA ir jos analogai</h1><p><br></p><div class="avoid"><p><br><br><font color="red"size="5">Šio skyriaus medžiaga vis dar rengiama arba neatnaujinta šių metų kursui, todėl kol kas jos <b>nenagrinėkite</b>.</font></p><p><br><br></p></div><p><br></p><p><br></p><div class="info"><p>Užsiėmimo <strong>tikslas</strong> – susipažinti su statistinių hipotezių tikrinimo būdais dviems ar daugiau imčių taikant dispersinę analizę (ANOVA) ar jai analogiškus statistinius kriterijus.</p></div><p><br></p><p>Atsisiųskite naujausią paketo <strong><em>biostat</em></strong> versiją:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="st">&quot;devtools&quot;</span>) 

<span class="co"># Atsisiųskite iš saugyklos „GitHub“:</span>
devtools<span class="op">::</span><span class="kw">install_github</span>(<span class="st">&quot;GegznaV/biostat&quot;</span>)             
devtools<span class="op">::</span><span class="kw">install_github</span>(<span class="st">&quot;GegznaV/RcmdrPlugin.biostat&quot;</span>, <span class="dt">ref =</span> <span class="st">&quot;biostat18&quot;</span>) 

<span class="co"># Bei iš saugykols „CRAN“:</span>
<span class="kw">install.packages</span>(<span class="st">&quot;PMCMR&quot;</span>)
<span class="kw">install.packages</span>(<span class="st">&quot;DescTools&quot;</span>)</code></pre><p>Šio darbo metu reikalingi <strong>R</strong> paketai:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Manipuliacija su duomenimis</span>
<span class="kw">library</span>(tidyverse)

<span class="co"># Analizės ir grafikų braižymo funkcijos</span>
<span class="kw">library</span>(Rcmdr)
<span class="kw">library</span>(biostat)
<span class="kw">library</span>(DescTools)

<span class="co"># Grafikams</span>
<span class="kw">library</span>(ggplot2)

<span class="co"># Neparametriniai post-hoc kriterijai</span>
<span class="kw">library</span>(PMCMR)</code></pre><div id="kas-yra-anova"class="section level2"><h2><span class="header-section-number">19.1</span> Kas yra ANOVA?</h2><p>ANOVA yra trumpasis <strong>dispersinės analizės</strong> (angl. <em>ANalysis Of VAriance</em>) pavadinimas. ANOVA – tai t kriterijaus analogas, kai norima palyginti dviejų ar daugiau nepriklausomų imčių (grupių) vidurkius.</p><p>Sakykime, kad lyginame <span class="math inline">\(k\)</span> grupių. Nulinė analizės hipotezė teigia, kad visų grupių vidurkiai lygūs, o jos alternatyva – bent dviejų grupių (kurių tiksliai – pasakyti negalima) vidurkiai skiriasi:<br><br><img src="fig/pic/10/10-h-anova.png"width="547"style="display:block;margin:auto"></p><p>Čia <span class="math inline">\(i\)</span> ir <span class="math inline">\(j\)</span> – lyginamų grupių numeriai.</p><div class="note"><p>Atlikdami <strong>ANOVA</strong> pagal dispersijas tikriname, ar skirtumai tarp vidurkių yra statistiškai reikšmingi.</p><p>Jei norime patikrinti, ar skirtumai tarp dispersijų yra reikšmingi, naudojame <strong>Levene</strong> (Livyno) kriterijų.</p></div><p><br></p><p>Praktiškai žiūrint, ši analizė taikoma norint atsakyti į tokius klausimus: ar kelių skirtingų irisų rūšių vidutiniai žiedlapių dydžiai skiriasi, ar kelių gydymo metodų efektyvumas skiriasi, ar ląstelės, auginamos keliose skirtingose terpėse, yra linkusios būti skirtingo dydžio.</p><p>Atkreipkite dėmesį, kad yra keli ANOVA variantai. Kai lyginimas atliekamas pagal vieną kategorinį kintamąjį (t. y., pagal vieną faktorių), ANOVA vadinama <strong>vienfaktore</strong>. Jei pagal du – dvifaktorė ir t.t. Yra ir specialių ANOVA variantų, skirtų priklausomoms imtims, pvz., blokuotųjų duomenų ANOVA, bei neparametrinių variantų, pvz., Kruskal-Wallis kriterijus. Šių pratybų metu mokysimės taikyti tik vienfaktorės ANOVA modelį, skirtą nepriklausomoms duomenų imtims, bei šio modelio analogus, kai pažeidžiamos klasikinio vienfaktorės ANOVA modelio prielaidos.</p><div id="ANOVA-ir-analogai"class="section level3"><h3><span class="header-section-number">19.1.1</span> Kurį vienfaktorės ANOVA variantą ar analogą pasirinkti?</h3><p>Vienfaktorė ANOVA analizė grindžiama šiomis prielaidomis:</p><ol style="list-style-type:decimal"><li>Grupių duomenys yra nepriklausomi;</li><li>Kiekvienos grupės kintamieji pasiskirstę normaliai (<span class="math inline">\(X_{gr} \sim \mathcal{N}(\mu_{gr},\sigma^2_{gr})\)</span>);</li><li>Grupių dispersijos yra lygios.</li></ol><p>Tad prieš atliekant ANOVA, reikia patikrinti duomenims keliamas prielaidas ir pasirinkti tinkamą analizės variantą ar neparametrinį jos analogą (pav. <a href="ht-anova-ir-analogai.html#fig:choose-anova">19.1</a>). Kai duomenų grupės yra nepriklausomos ir jų yra bent 3, įprastai renkamasi tarp klasikinės vienfaktorės ANOVA analizės, Welch F (<em>Velčo F</em>) kriterijaus (dar vadinamo Welch ANOVA), kai pažeidžiama lygių dispersijų prielaida, ir Kruskal-Wallis (<em>Kruskalo-Voliso</em>) kriterijaus, kai smarkiai pažeidžiama normalumo prielaida.</p><p>Parametriniai metodai – klasikinė ANOVA ir Walch F kriterijus – lygina duomenų vidurkius (vidurkis yra normaliojo skirstinio parametras), todėl aprašant šios analizės rezultatus reikia nurodyti grupių <strong>vidurkius</strong>. Tuo tarpu Kruskal-Wallis kriterijaus yra neparametrinis, bendresnis ir lygina, ar duomenų skirstiniai pagal savo padėtį skiriasi, t. y., ar bent viena grupė yra linkusi būti mažesnė arba didesnė už kitas. Aprašant Kruskal-Wallis analizės rezultatus nurodomos visų grupių <strong>medianos</strong>.</p><div class="avoid"><p>Schema yra supaprastinta ir tik rekomendacinio pobūdžio. Jos tikslas – būti „atspirties tašku“ renkantis analizės metodą. Konkrečiu atveju gali būti išlygų, papildomų sąlygų arba pasirinkimo variantų, kurie schemoje nepažymėti.</p></div><div class="figure"style="text-align:center"><span id="fig:choose-anova"></span> <img src="fig/pic/10/10-choose-anova.png"alt="Centro padėties lyginimas kelioms imtims. Schema, padedanti išsirinkti reikiamą vienfaktorės nepriklausomų imčių (grupių) ANOVA variantą ar jos analogą. Apatinėje dalyje pateikiami keli galimi *post-hoc* analizės variantai, skirti grupes lyginti poromis. Skaičiais pažymėtų schemos dalių paaiškinimas pateiktas tekste žemiau.  "width="1150"><p class="caption">Pav. 19.1: Centro padėties lyginimas kelioms imtims. Schema, padedanti išsirinkti reikiamą vienfaktorės nepriklausomų imčių (grupių) ANOVA variantą ar jos analogą. Apatinėje dalyje pateikiami keli galimi <em>post-hoc</em> analizės variantai, skirti grupes lyginti poromis. Skaičiais pažymėtų schemos dalių paaiškinimas pateiktas tekste žemiau.</p></div><p>Skaičiais pažymėtų <a href="ht-anova-ir-analogai.html#fig:choose-anova">19.1</a> schemos dalių paaiškinimai:</p><ol style="list-style-type:decimal"><li>Jei imčių dydžiai vienodi arba panašūs, ANOVA atspari mažiems ir net vidutiniams normalumo ir lygių dispersijų prielaidų pažeidimams.<br></li><li>Sprendžiant „iš akies“, dispersijos (ne standartiniai nuokrypiai) neturėtų skirtis daugiau kaip 3 kartus.<br></li><li>„Vienodos formos“ reiškia, kad visų grupių skirstinių asimetrija (jei yra) – vienos krypties, o sklaida (dispersijos) – daugmaž vienoda.<br></li><li>Jei <em>visų</em> grupių skirstinių forma vienoda ir skiriasi tik poslinkio parametru, t. y., skiriasi skirstinio padėtis (tokiems duomenims ir rekomenduojamas Kruskal-Wallis kriterijus), tada galime daryti išvadas apie grupių medianas. Šiuo atveju analizės rezultatai informatyvesni nei <em>5</em> punkto atveju.<br></li><li>Jei lyginamų grupių skirstinių forma skirtinga (skiriasi dispersijos, būdinga skirtingos krypties asimetrija), išvadas darome tik apie tai, kad bent viena grupė yra linkusi būti kitokia (arba didesnė, arba mažesnė) nei kitos. Techniškai kalbant, išvadas darome tik apie vidutinius rangus, bet ne medianas. Todėl šie rezultatai mažiau informatyvūs nei <em>4</em> punkto atveju.<br></li><li>Apie galimus ANOVA <em>post-hoc</em> analizės variantus:<ul><li><em>Tukey HSD</em> (angl. <em>honestly significant difference</em>) kriterijaus taikymui duomenys turi būti normalieji, dispersijos lygios, o imties dydžiai vienodi;<br></li><li><em>Games-Howell</em> kriterijaus taikymui duomenys turi būti normalieji, tačiau lygių dispersijų ir vienodų imties dydžių nereikalaujama. Kiekvienoje lyginamoje imtyje turi būti bent 6 nariai;<br></li><li>Galima atlikti keletą nepriklausomų imčių (Stjudento ar Welch) t kriterijaus taikymo procedūrų, bet būtina naudoti daugybinių lyginimų <strong><em>p</em> reikšmių korekcijos</strong> metodus (Holm, Bonferroni ar kitą procedūrą, kuri gali būti atlikta naudojant funkciją <code class="sourceCode r"><span class="kw">p.adjust</span>()</code>);</li><li>Yra ir kitų čia nepaminėtų <em>post-hoc</em> kriterijų.</li></ul></li><li>Apie galimus Welch ANOVA <em>post-hoc</em> analizės variantus:<ul><li><em>Games-Howell</em> kriterijui duomenys turi būti normalieji, tačiau lygių dispersijų ir vienodų imties dydžių nereikalaujama. Kiekvienoje lyginamoje imtyje turi būti bent 6 nariai;<br></li><li>Galima keletą kartų taikyti Welch t kriterijų grupių poroms, bet būtina naudoti daugybinių lyginimų <strong><em>p</em> reikšmių korekcijos</strong> metodus (Holm, Bonferroni ar kitą procedūrą, kuri gali būti atlikta naudojant funkciją <code class="sourceCode r"><span class="kw">p.adjust</span>()</code>);</li><li>Yra kitų čia nepaminėtų kriterijų. Šie kriterijai privalo nereikalauti lygių dispersijų prielaidos.</li></ul></li><li>Apie galimus Kruskal-Wallis kriterijaus <em>post-hoc</em> analizės variantus:<ul><li>Galima taikyti arba <em>Conover-Iman</em>, arba <em>Dunn</em> kriterijų. Tačiau <em>Conover-Iman</em> kriterijus yra galingesnis. Bet kuriuo atveju gautoms <em>p</em> reikšmėms reikia atlikti Holm ar kitą daugybinių lyginimų <em>p</em> reikšmių korekciją (šiame skyrelyje nurodytas metodas tokią korekciją atlieka automatiškai).</li><li>Galima keletą kartų grupių poroms taikyti nepriklausomų imčių Mann-Whitney-Wilcoxon kriterijų, bet tokiu atveju būtina naudoti <strong><em>p</em> reikšmių korekcijos</strong> metodus (Holm, Bonferroni ar kitą procedūrą, kuri gali būti atlikta naudojant, funkciją <code class="sourceCode r"><span class="kw">p.adjust</span>()</code>);</li><li>Yra kitų čia nepaminėtų kriterijų. Jie privalo būti neparametriniai ir tikti nenormaliesiems duomenims.<br></li></ul></li><li>Tai schema <a href="ht-padetis.html#fig:09-testai-05">18.2</a>.</li></ol><div class="note"><p><strong>Jei imčių didumai yra vienodi (arba panašūs)</strong>, vienfaktorė ANOVA yra ganėtinai atspari nedideliems ir netgi vidutiniams nuokrypiams nuo pasiskirstymo normalumo ir lygių dispersijų (dispersijų homogeniškumo) prielaidų.</p></div></div></div><div id="issamios-ANOVA-aspektai"class="section level2"><h2><span class="header-section-number">19.2</span> Išsamios ANOVA analizės aspektai</h2><p>Šiame skyriuje bus pateikti atskiri vienfaktorės ANOVA ar į ją panašios analizės aspektai.</p><div id="eiga"class="section level3"><h3><span class="header-section-number">19.2.1</span> Eiga</h3><p>Jei reikia atlikti ANOVA ar į ją panašią analizę, rekomenduojama tokia eiga:</p><ol style="list-style-type:decimal"><li>tiksliai apsibrėžiamas klausimas;</li><li>atliekama duomenų suvestinė ir nubraižomas grafikas, galintis padėti atsakyti į iškeltą klausimą;</li><li>patikrinamos analizės prielaidos:<ol style="list-style-type:lower-alpha"><li>ar duomenų imtys/grupės <strong>nepriklausomos</strong>:<ul><li>sprendžiame pagal tai, kaip buvo suplanuotas ir atliktas eksperimentas.</li></ul></li><li>ar duomenų <strong>pakankamai daug</strong>:<ul><li>geriausia, kai <strong>kiekvienoje grupėje</strong> bent po 15, jei grupių daug – bent po 20 atvejų;</li><li>kitu atveju duomenys privalo skirstytis idealiai normaliai, grupių dispersijos tik nežymiai skirtis;</li><li>jei duomenų per mažai, negalime patikimai patikrinti parametriniams kriterijams keliamų prielaidų:<ul><li><strong>mažoms imtims</strong>/grupėms statistiniai kriterijai linkę rodyti, kad skirtumai yra statistiškai nereikšmingi net esant dideliems skirtumams;</li><li><strong>didelėms imtims</strong>/grupėms net maži skirtumai bus pripažįstami statistiškai reikšmingais.</li></ul></li><li><strong>mažoms imtims</strong> geriau taikyti <strong>neparametrinius</strong> kriterijus;</li></ul></li><li>kiekvienos imties/grupės pasiskirstymo <strong>normalumo</strong> prielaida:<ul><li><strong>ir</strong> į vieną liniją išsidėstę qq diagramos taškai, <strong>ir</strong> Shapiro-Wilk kriterijaus <span class="math inline">\(p\ge0,05\)</span> rodo, kad normalumo prielaida tenkinama;</li><li>gali būti, kad šių dvejų metodų rezultatai nesutaps:<ul><li><strong>mažoms imtims</strong> statistiniai kriterijai yra linkę rodyti, kad nuokrypis nuo normalumo yra statistiškai nereikšmingas, net kai jis yra didelis, <strong>didelėms imtims</strong> net ir nedidelis nuokrypis nuo normalumo yra pripažįstamas statistiškai reikšmingas.</li></ul></li><li>prielaidos tikrinimą atliekame kiekvienai grupei atskirai (qq grafikai braižomi ir Shapiro-Wilk kriterijus atliekamas tiek kartų, kiek yra lyginamų grupių)..</li></ul></li><li><strong>lygių dispersijų</strong> prielaida:<ul><li>jei <strong>ir</strong> Levene/Brown-Forsythe kriterijaus <span class="math inline">\(p\ge0,05\)</span>, <strong>ir</strong> mažiausia bei didžiausia grupių dispersijos skiriasi mažiau nei 3 kartus, lygių dispersijų prielaida tenkinama;</li><li><strong>pastaba:</strong><ul><li><strong>mažoms grupėms</strong> statistiniai kriterijai bus linkę rodyti, kad dispersijų skirtumai (net labai dideli) nėra statistiškai reikšmingi;</li><li><strong>didelėms grupėms</strong> net ir menkiausi skirtumai bus pripažįstami statistiškai reikšmingais;</li></ul></li><li>dispersijas apskaičiuojame kiekvienai grupei atskirai, <strong>bet</strong> Levene/Brown-Forsythe kriterijų taikome tik vieną kartą, nes jis lygina visų grupių dispersijas iš karto.</li></ul></li></ol></li><li>teisingai pasirenkama ir atliekama pagrindinė analizė;</li><li>jei rezultatas statistiškai reikšmingas (rodo, kad bent viena grupė nuo kitų skiriasi statistiškai reikšmingai), atliekama papildoma <em>post-hoc</em> analizė (poriniai palyginimai norint išsiaiškinti, kurios konkrečiai grupės skiriasi).</li><li>rezultatai aprašomi.</li></ol></div><div id="klausimas"class="section level3"><h3><span class="header-section-number">19.2.2</span> Klausimas</h3><p>Sakykime, kad tiriame augalus auginami tam trimis skirtingomis sąlygomis. Pradžioje formuluojame <strong>tyrimo klausimą:</strong> <em>ar sausa augalo masė priklauso nuo auginimo sąlygų?</em> Po to klausimą performuluojame į formuluotę, kuri panašesnė į statistines hipotezes: <em>ar vidutinė sausa augalo masė skiriasi priklausomai nuo to, kokiomis sąlygomis augalas buvo augintas?</em> Matematiškai klausimą galime išgryninti iki tokios formuluotės: <em>ar skaitinio kintamojo reikšmės didumas priklauso nuo kategorinio kintamojo reikšmių?</em></p><p>Atkreipkite dėmesį, kad ANOVA (ir kiti statistiniai kriterijai) gali padėti atsakyti į klausimą „<strong>Ar?</strong>“ (ar skirtumas statistiškai reikšmingas?), bet norint atsakyti į klausimą „<strong>Kiek?</strong>“ (kokio dydžio šis skirtumas?) reikia papildomos analizės.</p></div><div id="duomenys"class="section level3"><h3><span class="header-section-number">19.2.3</span> Duomenys</h3><p>Pasirenkame ir užkrauname duomenis. Pavyzdžiuose duomenis užkrausime iš <em>R</em> paketų naudodami funkciją <code class="sourceCode r"><span class="kw">data</span>()</code>. (Duomenų aprašymas atidaromas naudojant kodą <code>?PlantGrowth</code>).</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(PlantGrowth)</code></pre><p>Savo tyrime duomenis užsikrausime ne naudodami funkciją <del><code class="sourceCode r"><span class="kw">data</span>()</code></del>, o <em>RStudio</em> ar <em>R Commander</em> langus arba duomenų bylų nuskaitymui skirtus kodus, nes duomenys bus pateikti tekstinėse (<em>.txt</em>, <em>.csv</em>, <em>.dat</em>), <em>Excel</em>’io (<em>.xls</em>, <em>xlsx</em>), <em>R</em> (<em>.rds</em>, <em>.RData</em>) ar kitokio tipo bylose.</p></div><div id="duomenu-suvestines"class="section level3"><h3><span class="header-section-number">19.2.4</span> Duomenų suvestinės</h3><p>Įsikėlę duomenis būtinai pasižiūrime į duomenų struktūrą, viršutines ir apatines eilutes, palyginame, ar teoriniai duomenų tipai (kategiriniai ir t.t.) atitinka <em>R</em> duomenų klases (pvz., <em>factor</em>). Jei neatitinka, atliekame korekcijas. Po to atliekamos duomenų suvestinės. Jas galima atlikti papildiniu <em>R Commander</em>. Šiuo atveju pateikti programos kodai.</p><pre class="sourceCode r"><code class="sourceCode r">dplyr<span class="op">::</span><span class="kw">glimpse</span>(PlantGrowth)
<span>## Observations: 30</span>
<span>## Variables: 2</span>
<span>## $ weight &lt;dbl&gt; 4.17, 5.58, 5.18, 6.11, 4.50, 4.61, 5.17, 4.53, 5.33, 5...</span>
<span>## $ group  &lt;fct&gt; ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, c...</span></code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(PlantGrowth)
<span>##      weight       group   </span>
<span>##  Min.   :3.590   ctrl:10  </span>
<span>##  1st Qu.:4.550   trt1:10  </span>
<span>##  Median :5.155   trt2:10  </span>
<span>##  Mean   :5.073            </span>
<span>##  3rd Qu.:5.530            </span>
<span>##  Max.   :6.310</span></code></pre><p>Suvestinė pogrupiams (gali būti, kad jums lengviau ją atlikti naudojant <em>R Commander</em>).</p><pre class="sourceCode r"><code class="sourceCode r">PlantGrowth <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">group_by</span>(group) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">summarize</span>(<span class="dt">n =</span> <span class="kw">n</span>(),
              <span class="dt">vidurkis         =</span> <span class="kw">mean</span>(weight)   <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(<span class="dv">1</span>),
              <span class="dt">nupjautinis_vid  =</span> <span class="kw">mean</span>(weight, <span class="dt">trim =</span> <span class="fl">0.1</span>)   <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(<span class="dv">1</span>),
              <span class="dt">mediana          =</span> <span class="kw">median</span>(weight) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(<span class="dv">1</span>),
              <span class="dt">dispersija       =</span> <span class="kw">var</span>(weight)    <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(<span class="dv">2</span>),
              <span class="dt">sd               =</span> <span class="kw">sd</span>(weight)     <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(<span class="dv">1</span>),
              <span class="dt">mad              =</span> <span class="kw">mad</span>(weight)    <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(<span class="dv">1</span>),
              <span class="dt">min              =</span> <span class="kw">min</span>(weight)    <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(<span class="dv">1</span>),
              <span class="dt">max              =</span> <span class="kw">max</span>(weight)    <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(<span class="dv">1</span>))
<span>## # A tibble: 3 x 10</span>
<span>##   group     n vidurkis nupjautinis_vid mediana dispersija    sd   mad   min</span>
<span>##   &lt;fct&gt; &lt;int&gt;    &lt;dbl&gt;           &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;</span>
<span>## 1 ctrl     10      5               5       5.2       0.34   0.6   0.7   4.2</span>
<span>## 2 trt1     10      4.7             4.6     4.6       0.63   0.8   0.5   3.6</span>
<span>## 3 trt2     10      5.5             5.5     5.4       0.2    0.4   0.4   4.9</span>
<span>## # ... with 1 more variable: max &lt;dbl&gt;</span></code></pre><p>Matome, kad yra 2 kintamieji: skaitinis ir kategorinis. Yra 3 skirtingos kategorijos. Duomenys yra nepriklausomi, nes tas pats augalas negali būti auginamas iš karto keliomis skirtingomis sąlygomis. Yra daugiau nei 2 grupės, pagal kurias norima lyginti skaitinį kintamąjį, vadinasi, tinka kažkuris ANOVA variantas arba analogiškas kriterijus.</p></div><div id="duomenu-formatas-ilgasis"class="section level3"><h3><span class="header-section-number">19.2.5</span> Duomenų formatas: ilgasis</h3><p>Vienfaktorei ANOVA analizei, kaip ir kitoms nepriklausomų imčių analizėms, duomenys turi būti pateikti ilguoju formatu . Jei turime ilgojo formato duomenis, juos pertvarkome naudodami funkciją <code class="sourceCode r"><span class="kw">gather</span>()</code> iš paketo <strong><em>dplyr</em></strong> arba naudodami <em>R Commander</em> meniu (pav. <a href="ht-anova-ir-analogai.html#fig:10-wide-to-long-02">19.2</a> bei pav. <a href="ht-anova-ir-analogai.html#fig:10-wide-to-long-03">19.3</a>).</p><div class="figure"style="text-align:center"><span id="fig:10-wide-to-long-02"></span> <img src="fig/pic/10/10-wide-to-long-02.png"alt="Duomenų vertimas iš plačiojo formato į ilgąjį naudojant standartinį *R Commander* meniu.  "width="962"><p class="caption">Pav. 19.2: Duomenų vertimas iš plačiojo formato į ilgąjį naudojant standartinį <em>R Commander</em> meniu.</p></div><p><br></p><div class="figure"style="text-align:center"><span id="fig:10-wide-to-long-03"></span> <img src="fig/pic/10/10-wide-to-long-03.png"alt="Duomenų vertimas iš plačiojo formato į ilgąjį naudojant *R Commander* meniu „BioStat'18“. Šis būdas išlaiko visus kintamuosius, kurie nėra pertvarkomi, yra labiau automatizuotas, turi daugiau parinkčių nei pav. \@ref(fig:10-wide-to-long-02).  "width="930"><p class="caption">Pav. 19.3: Duomenų vertimas iš plačiojo formato į ilgąjį naudojant <em>R Commander</em> meniu „BioStat’18“. Šis būdas išlaiko visus kintamuosius, kurie nėra pertvarkomi, yra labiau automatizuotas, turi daugiau parinkčių nei pav. <a href="ht-anova-ir-analogai.html#fig:10-wide-to-long-02">19.2</a>.</p></div></div><div id="modelio-formule"class="section level3"><h3><span class="header-section-number">19.2.6</span> Modelio formulė</h3><p>Kai kurioms funkcijoms – ypač toms, kurios vykdo statistinę analizę – duomenis galime pateikti naudodami <strong>modelio formulę</strong>. Modelio formulę sudaro užrašas, kuriame naudojama bangelė, ir kokios dalys (pavyzdys): <code>y ~ grupe, data = duomenys</code>, kur <code>duomenys</code> yra duomenų lentelės pavadinimas, <code>y</code> ir <code>grupe</code> – toje lentelėje esančių kintamųjų pavadinimai (be kabučių). Užrašą <code>y ~ grupe</code> reiktų skaityti „<code>y</code> pagal <code>grupe</code>“. Pilnas užrašymas:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">funkcija</span>(y <span class="op">~</span><span class="st"> </span>grupe, <span class="dt">data =</span> duomenys)</code></pre><p>Pavyzdys, kaip šiuo principu braižomi grafikai, pateiktas kitame skyrelyje: ten <code>y</code> tampa <code>weigth</code>, <code>grupe</code> → <code>group</code>, <code>duomenys</code> → <code>PlantGrowth</code>.</p></div><div id="grafikai"class="section level3"><h3><span class="header-section-number">19.2.7</span> Grafikai</h3><p>ANOVA analizei atvaizduojamas duomenų pasiskirstymas pogrupiais. Tam tinka stačiakampės, branduolių tankio, smuikinės ir kitos diagramos.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(biostat)</code></pre><p>Naudodamiesi modelio formule nubraižysime stačiakampę diagramą:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth)</code></pre><p><img src="10--01--ANOVA-ir-pan_files/figure-html/unnamed-chunk-16-1.png"width="384"style="display:block;margin:auto"></p><p>Pakete <strong><em>biostat</em></strong> yra analogiška funkcija, suteikianti daugiau informacijos.</p><pre class="sourceCode r"><code class="sourceCode r">biostat<span class="op">::</span><span class="kw">gg_boxplot_plus</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Grupė&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Svoris&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Sauso augalų svorio pasiskirstymas&quot;</span>)</code></pre><p><img src="10--01--ANOVA-ir-pan_files/figure-html/unnamed-chunk-17-1.png"width="384"style="display:block;margin:auto"></p><p>Funkcija <code class="sourceCode r"><span class="kw">gg_boxplot_plus</span>()</code> nubraižo grafiką, kuriame pažymėtas vidurkis su savirankos metodu apskaičiuotu pasikliauties intervalu, stačiakampė diagrama ir x ašyje pasklaidyti (vengiama persidengimo) duomenų taškai.</p><p>Grupes galima išdėlioti pagal grupių medianos dydį:</p><pre class="sourceCode r"><code class="sourceCode r">biostat<span class="op">::</span><span class="kw">gg_boxplot_plus</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth,
                         <span class="dt">sort_groups =</span> <span class="st">&quot;ascending&quot;</span>, <span class="dt">sort_fun =</span> median)
<span>## Warning: Some components of ... were not used: fun</span></code></pre><p><img src="10--01--ANOVA-ir-pan_files/figure-html/unnamed-chunk-18-1.png"width="384"style="display:block;margin:auto"></p></div><div id="duomenu-pasiskirstymo-normalumo-tikrinimas-grupems"class="section level3"><h3><span class="header-section-number">19.2.8</span> Duomenų pasiskirstymo normalumo tikrinimas grupėms</h3><p>Šiam tikslui siūlau naudoti iš karto 2 būdus – statistinį kriterijų ir grafinį metodą.</p><p>Shapiro-Wilk kriterijus:</p><pre class="sourceCode r"><code class="sourceCode r">biostat<span class="op">::</span><span class="kw">test_normality</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth,
                        <span class="dt">test =</span> <span class="st">&quot;Shapiro-Wilk&quot;</span>) 
<span>## </span>
<span>##  The results of Shapiro-Wilk normality test </span>
<span>## </span>
<span>##   group statistic p.value    </span>
<span>## 1  ctrl     0.957   0.747    </span>
<span>## 2  trt1     0.930   0.452    </span>
<span>## 3  trt2     0.941   0.564    </span>
<span>## </span>
<span>## *** - p &lt; 0.001, ** - p &lt; 0.01, * - p &lt; 0.05, . - p &lt; 0.1</span></code></pre><p>Įprastai, kai <span class="math inline">\(p \ge 0.05\)</span>, laikoma, kad normalumo prielaida tenkinama (nuokrypiai nuo normalumo nėra statistiškai reikšmingi).</p><p>QQ grafikų braižymas naudojant paketo <strong>biostat</strong> funkcijas:</p><pre class="sourceCode r"><code class="sourceCode r">biostat<span class="op">::</span><span class="kw">qq_plot</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth,
                 <span class="dt">use_colors =</span> <span class="ot">TRUE</span>)</code></pre><p><img src="10--01--ANOVA-ir-pan_files/figure-html/unnamed-chunk-20-1.png"width="384"style="display:block;margin:auto"></p><p>Įprastai, kai qq diagramos taškai išsidėstę į vieną tiesę arba nuo jos nukrypę nedaug, laikoma, kad normalumo prielaida tenkinama.</p><p>Daugiau informacijos apie normalumo tikrinimą skyriuje <a href="ht-normalumas.html#ht-normalumas">16</a>.</p></div><div id="dispersiju-homogeniskumo-tikrinimas"class="section level3"><h3><span class="header-section-number">19.2.9</span> Dispersijų homogeniškumo tikrinimas</h3><p><strong>Lygių dispersijų</strong> prielaida (dar vadinama dispersijų <em>homogeniškumu</em> ar <em>homoskedastiškumu</em>), kai grupių yra dvi ar daugiau, gali būti tikrinama Levene’o (Livyno) / Brown-Forsythe kriterijais (pirmu atveju centras – vidurkis, antru – mediana). Šiais kriterijais tikrinamos hipotezės:</p><p><img src="fig/pic/10/10-h-levene.png"width="547"style="display:block;margin:auto"></p><p>Kriterijaus taikymas programiškai:</p><pre class="sourceCode r"><code class="sourceCode r">car<span class="op">::</span><span class="kw">leveneTest</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth)
<span>## Levene&#39;s Test for Homogeneity of Variance (center = median)</span>
<span>##       Df F value Pr(&gt;F)</span>
<span>## group  2  1.1192 0.3412</span>
<span>##       27</span></code></pre><p>Levene’o / Brown-Forsythe kriterijaus rezultatų lentelėje labiausiai mus dominantis dalykas yra <em>p</em> reikšmė. Ji pateikta stulpelyje <code>Pr(&gt;F)</code> ir yra lygi 0.34 (suapvalinta). Šis rezultatas rodo, kad skirtumas tarp dispersijų nėra statistiškai reikšmingas.</p><br><div class="figure"style="text-align:center"><span id="fig:09-Levene-test-b"></span> <img src="fig/pic/10/09-Levene-test.png"alt="Levene ir Brown-Forsythe testai naudojant *R Commander*.  "><p class="caption">Pav. 19.4: Levene ir Brown-Forsythe testai naudojant <em>R Commander</em>.</p></div><p>Daugiau informacijos apie kriterijus dispersijų homogeniškumui tikrinti pateikta skyriuje <a href="ht-sklaida.html#dispersiju-lyginimas">17.1</a>.</p></div><div id="tinkamo-anova-varianto-ar-analogo-pasirinkimas"class="section level3"><h3><span class="header-section-number">19.2.10</span> Tinkamo ANOVA varianto ar analogo pasirinkimas</h3><p>Ši tema nagrinėjama <a href="ht-anova-ir-analogai.html#ANOVA-ir-analogai">19.1.1</a> skyriuje.</p></div><div id="cld"class="section level3"><h3><span class="header-section-number">19.2.11</span> Kompaktiškas raidinis žymėjimas (<em>cld</em>)</h3><p>Sakykime, kelias grupes lyginame poromis. Statistiškai reikšmingus rezultatus tarp grupių, kai lyginimų daug, galime pažymėti taip vadinamu <strong>kompaktišku raidiniu žymėjimu</strong> (angl., <em>compact letter display</em>, <em>cld</em>). Šio žymėjimo esmė: kiekvienai grupei suteikiama viena ar keletas raidžių. <strong>Interpretacija:</strong> su pasirinktu pasikliovimo lygmeniu <span class="math inline">\(\alpha\)</span> galime teigti, kad tarp grupių, kurios <strong>neturi</strong> bendros raidės, skirtumai yra statistiškai reikšmingi. Jei grupės turi bendrą raidę – skirtumai statistiškai nereikšmingi. Raidinis žymėjimas labai patogus, kai vienu metu poromis lyginame daug grupių.</p><center><table style="width:38%"><caption><span id="tab:cld-1">Lentelė 19.1: </span>Kompaktiško raidinio žymėjimo (cld) pavyzdys lyginant grupes <em>trt1</em>, <em>trt2</em>, <em>ctrl</em>.</caption><colgroup><col width="11%"><col width="8%"><col width="18%"></colgroup><thead><tr class="header"><th align="center">group</th><th align="center">cld</th><th align="center">spaced_cld</th></tr></thead><tbody><tr class="odd"><td align="center">ctrl</td><td align="center">ab</td><td align="center">ab</td></tr><tr class="even"><td align="center">trt1</td><td align="center">a</td><td align="center">a_</td></tr><tr class="odd"><td align="center">trt2</td><td align="center">b</td><td align="center">_b</td></tr></tbody></table></center><p><br></p><p>Lentelėje <a href="ht-anova-ir-analogai.html#tab:cld-1">19.1</a> rodoma, kad statistiškai reikšmingi skirtumai tik tarp grupių <em>trt1</em> ir <em>trt2</em>, nes jos neturi bendros raidės.</p><p><br>Pažymėjimą <em>cld</em> būdu galima atidėti grafikuose. Paketo <strong><em>biostat</em></strong> funkcija tai gali padaryti automatiškai:</p><pre class="sourceCode r"><code class="sourceCode r">rez_tukey &lt;-<span class="st"> </span>biostat<span class="op">::</span><span class="kw">posthoc_anova</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth,
                                    <span class="dt">method =</span> <span class="st">&quot;Tukey&quot;</span>)
cld_tukey &lt;-<span class="st"> </span>biostat<span class="op">::</span><span class="kw">make_cld</span>(rez_tukey)

<span class="co"># Įdedame „cld“ objektą</span>
biostat<span class="op">::</span><span class="kw">gg_boxplot_plus</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth,
                         <span class="dt">cld =</span> cld_tukey)</code></pre><p><img src="10--01--ANOVA-ir-pan_files/figure-html/unnamed-chunk-23-1.png"width="384"style="display:block;margin:auto"></p></div><div id="ANOVA-rezultatu-aprasymas"class="section level3"><h3><span class="header-section-number">19.2.12</span> Rezultatų aprašymas</h3><p>Aprašant ANOVA arba Welch ANOVA (Welch F kriterijaus) rezultatus įprasta nurodyti visų grupių <strong>vidurkius</strong>. Jei grupių daug – vidurkiai nurodomi lentele. Aprašant neparametrinio Kruskal-Wallis kriterijaus rezultatus nurodomos visų grupių <strong>medianos</strong>. Taip pat nurodomas kriterijaus pavadinimas, kriterijaus statistika, parametrai ir <em>p</em> reikšmė.</p><div id="anova-rezultatai"class="section level4 unnumbered"><h4>ANOVA rezultatai</h4><p>Taip pat pateikiamas taikytos analizės pavadinimas, kriterijaus statistika <em>F</em>, abu jos laisvės laipsniai (tiek skaitiklio, angl. <em>numerator</em>, tiek vardiklio, angl. <em>denominator</em>) ir <em>p</em> reikšmė 3-4 skaičių po kablelio tikslumu. Pvz., skyrelio <a href="ht-anova-ir-analogai.html#ANOVA-pvz">19.4.1</a> rezultatai:</p><pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  
## group        2  3.766  1.8832   4.846 0.0159 *
## Residuals   27 10.492  0.3886                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre><p>Stulpelyje <code>Df</code> pateikti laisvės laipsniai, <code>F value</code> – <em>F</em> statistika, <code>Pr(&gt;F)</code> – <em>p</em> reikšmė. Šių rezultatų aprašymo pavyzdys: „Skirtumai tarp grupių vidurkių buvo statistiškai reikšmingi (ANOVA, <em>F</em>(2, 27) = 4.846, <em>p</em> = 0.0159). Grupių vidurkiai pateikti lentelėje <em>/nurodome lentelės numerį/</em>“. Papildomai reiktų nurodyti grupių vidurkius ir, geriausia, pateikti grafiką su grupių palyginimu.</p></div><div id="welch-anova-rezultatai"class="section level4 unnumbered"><h4>Welch ANOVA rezultatai</h4><p>Welch ANOVA rezultatų pavyzdys ir <a href="ht-anova-ir-analogai.html#Welch-F-pvz">19.3.2</a> skyrelio:</p><pre><code>## 
##  One-way analysis of means (not assuming equal variances)
## 
## data:  fscore and fcategory
## F = 90.59, num df = 2.000, denom df = 25.563, p-value =
## 0.000000000002494</code></pre><p>Čia <code>F</code> – <em>F</em> statistika, <code>num df</code> – skaitiklio laisvės laipsniai, <code>denom df</code> – vardiklio laisvės laipsniai, <code>p-value</code> – <em>p</em> reikšmė. Tad analizės rezultatai turėtų būti apibūdinti taip: „(Welch <em>F</em> kriterijus, <em>F</em>(2, 25.563) = 90.59, <em>p</em> &lt; 0.0001)“.</p></div><div id="kruskal-wallis-analizes-rezultatai"class="section level4 unnumbered"><h4>Kruskal-Wallis analizės rezultatai</h4><p>Aprašant neparametrinio Kruskal-Wallis kriterijaus rezultatus pateikiamas kriterijaus pavadinimas, kriterijaus statistika <span class="math inline">\(\chi^2\)</span>, jos laisvės laipsniai bei <em>p</em> reikšmė bent 3 skaičių po kablelio tikslumu. Jei <em>p</em> reikšmė labai maža, tai ją rašome maždaug taip <em>p&lt;0.001</em> ar <em>p&lt;0.0001</em>. Pvz., skyrelio <a href="ht-anova-ir-analogai.html#kw-pvz">19.6.1</a> rezultatai, kuriuos programa <em>R</em> atspausdino taip:</p><pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  Ozone by Month
## Kruskal-Wallis chi-squared = 29.267, df = 4, p-value = 0.000006901</code></pre><p>Aprašymas turėtų atrodyti maždaug taip: „Skirtumai tarp grupių buvo statistiškai reikšmingi (Kruskal-Wallis kriterijus, <span class="math inline">\(\chi^2(4)\)</span> = 29.27, <em>p</em> &lt; 0.0001). Grupių pasiskirstymas vaizduojamas grafike <em>/nurodome grafiko numerį/</em>, skaitinės suvestinės pateiktos lentelėje <em>/nurodome lentelės numerį/</em>“. Reikšmė <code>chi-squared</code> nurodo <span class="math inline">\(\chi^2\)</span> statistiką, <code>df</code> – parametrą pavadinimu „laisvės laipsniai“, <code>p-value</code> – <em>p</em> reikšmę. Papildomai turėtų būti pateiktos visų grupių medianos ir, geriausia, grafikai.</p></div><div id="post-hoc-analizes-rezultatai"class="section level4 unnumbered"><h4><em>Post-hoc</em> analizės rezultatai</h4><p>Jei atlikta <em>post-hoc</em> analizė, jos rezultatai taip pat aprašomi ir tai daroma panašiai kaip ir t ar Wilcoxon kriterijų aprašymo atvejais. Tiksliai apibūdinamas ir analizės metodas, ir <em>p</em> reikšmių korekcijos metodas (jei jis taikytas). Nurodom, kurių būtent porų lyginimo rezultatas pateikiamas. Jei rezultatų daug – jie gali būti pateikiami lentele. Rekomenduoju naudoti <em>cld</em> žymėjimus (skyrelis <a href="ht-anova-ir-analogai.html#cld">19.2.11</a>) ir paaiškinti, ką tie žymėjimai reiškia.</p></div></div></div><div id="programos-kodai-analizei"class="section level2"><h2><span class="header-section-number">19.3</span> Programos kodai analizei</h2><p>Pateikti analizę atliekančių programos kodų pavyzdžiai. Juose esančius kodo elementus</p><pre class="sourceCode r"><code class="sourceCode r">y <span class="op">~</span><span class="st"> </span>group, data =<span class="st"> </span>my_data</code></pre><p>reikia pakeisti tinkamais savo duomenims:</p><ul><li><strong><code>my_data</code></strong> – duomenų lentelės pavadinimas (be kabučių);</li><li><strong><code>y</code></strong> – skaitinio kintamojo iš šios lentelės pavadinimas (be kabučių);</li><li><strong><code>group</code></strong> – kategorinio kintamojo iš šios lentelės pavadinimas (be kabučių).</li></ul><p>Sakykime, jei jūs tiriate ląstelių skaičiaus pasiskirstymą (kintamasis <code>skaičius</code>) ląsteles augindami skirtingose terpėse (kintamasis <code>terpė</code>), o duomenys įrašyti duomenų lentelėje <code>ląstelės</code>, tada vietoje</p><pre class="sourceCode r"><code class="sourceCode r">y <span class="op">~</span><span class="st"> </span>group, data =<span class="st"> </span>my_data </code></pre><p>turite rašyti</p><pre class="sourceCode r"><code class="sourceCode r">skaičius <span class="op">~</span><span class="st"> </span>terpė, data =<span class="st"> </span>ląstelės</code></pre><div id="anova"class="section level3"><h3><span class="header-section-number">19.3.1</span> ANOVA</h3><p>Pavyzdyje pateiktus kodo elementus <code>y ~ group, data = my_data</code> reikia pakeisti tinkamais savo duomenims.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Analizė </span>
model_anova &lt;-<span class="st"> </span><span class="kw">aov</span>(y <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> my_data)
model_anova_summary &lt;-<span class="st"> </span><span class="kw">summary</span>(model_anova)

<span class="co"># Rezultatų spausdinimas</span>
<span class="kw">print</span>(model_anova_summary)</code></pre></div><div id="Welch-F-pvz"class="section level3"><h3><span class="header-section-number">19.3.2</span> Welch ANOVA (Welch F kriterijus)</h3><p>Pavyzdyje pateiktus kodo elementus <code>y ~ group, data = my_data</code> reikia pakeisti tinkamais savo duomenims.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Analizė </span>
model_welch_anova &lt;-<span class="st"> </span><span class="kw">oneway.test</span>(y <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> my_data)

<span class="co"># Rezultatų spausdinimas</span>
<span class="kw">print</span>(model_welch_anova)</code></pre></div><div id="kruskal-wallis-kriterijus"class="section level3"><h3><span class="header-section-number">19.3.3</span> Kruskal-Wallis kriterijus</h3><p>Pavyzdyje pateiktus kodo elementus <code>y ~ group, data = my_data</code> reikia pakeisti tinkamais savo duomenims.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Analizė </span>
model_kw_test &lt;-<span class="st"> </span><span class="kw">kruskal.test</span>(y <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> my_data)

<span class="co"># Rezultatų spausdinimas</span>
<span class="kw">print</span>(model_kw_test)</code></pre></div><div id="post-hoc-tukey-hsd-kriterijus"class="section level3"><h3><span class="header-section-number">19.3.4</span> <em>Post-hoc:</em> Tukey HSD kriterijus</h3><p>Pavyzdyje pateiktus kodo elementus <code>y ~ group, data = my_data</code> reikia pakeisti tinkamais savo duomenims.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Paketai</span>
<span class="kw">library</span>(biostat)

<span class="co"># Analizė </span>
model_tukey &lt;-<span class="st"> </span><span class="kw">posthoc_anova</span>(y <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> my_data, 
                             <span class="dt">method =</span> <span class="st">&quot;Tukey&quot;</span>)

<span class="co"># Rezultatų apibendrinimas „cld“ žymėjimais</span>
cld_tukey &lt;-<span class="st"> </span><span class="kw">make_cld</span>(model_tukey)

<span class="co"># Rezultatų spausdinimas</span>
<span class="kw">print</span>(model_tukey)
<span class="kw">print</span>(cld_tukey)

<span class="co"># Grafikas su „cld“ žymėjimais</span>
<span class="kw">gg_boxplot_plus</span>(y <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> my_data,
                <span class="dt">cld =</span> cld_tukey)</code></pre></div><div id="post-hoc-games-howell-kriterijus"class="section level3"><h3><span class="header-section-number">19.3.5</span> <em>Post-hoc:</em> Games-Howell kriterijus</h3><p>Pavyzdyje pateiktus kodo elementus <code>y ~ group, data = my_data</code> reikia pakeisti tinkamais savo duomenims.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Paketai</span>
<span class="kw">library</span>(biostat)

<span class="co"># Analizė </span>
model_gh &lt;-<span class="st"> </span><span class="kw">posthoc_anova</span>(y <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> my_data,
                          <span class="dt">method =</span> <span class="st">&quot;Games-Howell&quot;</span>)

<span class="co"># Rezultatų apibendrinimas „cld“ žymėjimais</span>
cld_gh &lt;-<span class="st"> </span><span class="kw">make_cld</span>(model_gh)

<span class="co"># Rezultatų spausdinimas</span>
<span class="kw">print</span>(model_gh)

<span class="kw">print</span>(cld_gh)

<span class="co"># Grafikas su „cld“ žymėjimais</span>
<span class="kw">gg_boxplot_plus</span>(y <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> my_data,
                <span class="dt">cld =</span> cld_gh)</code></pre></div><div id="post-hoc-conover-iman-kriterijus"class="section level3"><h3><span class="header-section-number">19.3.6</span> <em>Post-hoc:</em> Conover-Iman kriterijus</h3><p>Pavyzdyje pateiktus kodo elementus <code>y ~ group, data = my_data</code> reikia pakeisti tinkamais savo duomenims.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Paketai</span>
<span class="kw">library</span>(biostat)
<span class="kw">library</span>(PMCMR)

<span class="co"># Analizė</span>
model_conover_iman &lt;-<span class="st"> </span><span class="kw">posthoc.kruskal.conover.test</span>(y <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> my_data)

<span class="co"># Rezultatų apibendrinimas „cld“ žymėjimais</span>
cld_conover_iman &lt;-<span class="st"> </span><span class="kw">make_cld</span>(model_conover_iman)

<span class="co"># Rezultatų spausdinimas</span>
<span class="kw">print</span>(model_conover_iman)
<span class="kw">print</span>(cld_conover_iman)

<span class="co"># Grafikas su „cld“ žymėjimais</span>
<span class="kw">gg_boxplot_plus</span>(y <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> my_data,
                <span class="dt">cld =</span> cld_conover_iman)</code></pre></div></div><div id="pavyzdys-1-kai-duomenys-normalieji-ir-dispersijos-lygios"class="section level2"><h2><span class="header-section-number">19.4</span> Pavyzdys 1: kai duomenys normalieji ir dispersijos lygios</h2><div id="ANOVA-pvz"class="section level3"><h3><span class="header-section-number">19.4.1</span> ANOVA (pagrindinė analizė)</h3><p>Pavyzdys:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)

<span class="kw">data</span>(PlantGrowth)

?PlantGrowth</code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">glimpse</span>(PlantGrowth)
<span>## Observations: 30</span>
<span>## Variables: 2</span>
<span>## $ weight &lt;dbl&gt; 4.17, 5.58, 5.18, 6.11, 4.50, 4.61, 5.17, 4.53, 5.33, 5...</span>
<span>## $ group  &lt;fct&gt; ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, c...</span></code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(PlantGrowth)
<span>##   weight group</span>
<span>## 1   4.17  ctrl</span>
<span>## 2   5.58  ctrl</span>
<span>## 3   5.18  ctrl</span>
<span>## 4   6.11  ctrl</span>
<span>## 5   4.50  ctrl</span>
<span>## 6   4.61  ctrl</span></code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(PlantGrowth)
<span>##      weight       group   </span>
<span>##  Min.   :3.590   ctrl:10  </span>
<span>##  1st Qu.:4.550   trt1:10  </span>
<span>##  Median :5.155   trt2:10  </span>
<span>##  Mean   :5.073            </span>
<span>##  3rd Qu.:5.530            </span>
<span>##  Max.   :6.310</span></code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth)</code></pre><p><img src="10--01--ANOVA-ir-pan_files/figure-html/unnamed-chunk-47-1.png"width="384"style="display:block;margin:auto"></p><p>Normalumo prielaidos tikrinimas. Tam geriausia naudoti kelis metodus:</p><pre class="sourceCode r"><code class="sourceCode r">biostat<span class="op">::</span><span class="kw">qq_plot</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth,
                 <span class="dt">use_colors =</span> <span class="ot">TRUE</span>)</code></pre><p><img src="10--01--ANOVA-ir-pan_files/figure-html/unnamed-chunk-48-1.png"width="384"style="display:block;margin:auto"></p><pre class="sourceCode r"><code class="sourceCode r">
biostat<span class="op">::</span><span class="kw">test_normality</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth) 
<span>## </span>
<span>##  The results of Shapiro-Wilk normality test </span>
<span>## </span>
<span>##   group statistic p.value    </span>
<span>## 1  ctrl     0.957   0.747    </span>
<span>## 2  trt1     0.930   0.452    </span>
<span>## 3  trt2     0.941   0.564    </span>
<span>## </span>
<span>## *** - p &lt; 0.001, ** - p &lt; 0.01, * - p &lt; 0.05, . - p &lt; 0.1</span></code></pre><p>Pagal qq diagramą grupėje „trt1“ yra keli nedaug nukrypę taškai. Bet pagal Shapiro-Wilk kriterijų nuokrypis nėra statistiškai reikšmingas. Tad, atrodo, normalumo prielaida tenkinama.</p><p>Dispersijų homogeniškumo prielaidos tikrinimas:</p><pre class="sourceCode r"><code class="sourceCode r">car<span class="op">::</span><span class="kw">leveneTest</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth)
<span>## Levene&#39;s Test for Homogeneity of Variance (center = median)</span>
<span>##       Df F value Pr(&gt;F)</span>
<span>## group  2  1.1192 0.3412</span>
<span>##       27</span></code></pre><p>Brown-Forsythe kirterijaus (Levene kriterijus, kai centras – mediana) rezultatai lygių dispersijų prielaidai neprieštarauja (p reikšmė <span class="math inline">\(Pr(&gt;F) = 0.34 \ge \alpha = 0.05\)</span>).</p><p>ANOVA analizė:</p><pre class="sourceCode r"><code class="sourceCode r">anova_modelis &lt;-<span class="st"> </span><span class="kw">aov</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth)

<span class="kw">summary</span>(anova_modelis)
<span>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  </span>
<span>## group        2  3.766  1.8832   4.846 0.0159 *</span>
<span>## Residuals   27 10.492  0.3886                 </span>
<span>## ---</span>
<span>## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></code></pre><p>ANOVA rodo, kad bent viena grupė nuo kitų statistiškai reikšmingai skiriasi <span class="math inline">\(p = 0.0159&lt;0.05\)</span> (šie ANOVA rezultatai aprašyti skyriuje <a href="ht-anova-ir-analogai.html#ANOVA-rezultatu-aprasymas">19.2.12</a>). Todėl verta atlikti porinius lyginimus.</p></div><div id="tukey-hsd-1"class="section level3"><h3><span class="header-section-number">19.4.2</span> Tukey kriterijus (<em>post-hoc</em> analizė)</h3><p>Jei duomenys normalieji, imčių dispersijos yra lygios, ir visų <strong>lyginamų grupių dydžiai (daugmaž) vienodi</strong>, <strong>Tukey HSD</strong> kriterijus yra tinkamas naudoti kaip <strong>ANOVA</strong> <em>post-hoc</em> analizė, kurios metu atliekami poriniai palyginimai.</p><pre class="sourceCode r"><code class="sourceCode r">rez_tukey &lt;-<span class="st"> </span>biostat<span class="op">::</span><span class="kw">posthoc_anova</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth,
                                    <span class="dt">method =</span> <span class="st">&quot;Tukey&quot;</span>)
rez_tukey
<span>## Tukey HSD test results (ANOVA post-hoc) </span>
<span>## </span>
<span>##      groups difference ci_lower ci_upper    t    df          p</span>
<span>## 1 trt1-ctrl     -0.371   -1.062    0.320 1.33 27.00  0.391    </span>
<span>## 2 trt2-ctrl      0.494   -0.197    1.185 1.77 27.00  0.198    </span>
<span>## 3 trt2-trt1      0.865    0.174    1.556 3.10 27.00  0.012 *  </span>
<span>## </span>
<span>##   group  n  mean variance    sd cld spaced_cld</span>
<span>## 1  ctrl 10 5.032    0.340 0.583  ab         ab</span>
<span>## 2  trt1 10 4.661    0.630 0.794   a         a_</span>
<span>## 3  trt2 10 5.526    0.196 0.443   b         _b</span></code></pre><p><br></p><p>Svarbiausi rezultatai:</p><p>groups – lyginamos grupės;</p><ol style="list-style-type:decimal"><li><code class="sourceCode r">difference</code> – skirtumai tarp vidurkių (pagal jį galime spręsti apie praktinę naudą);</li><li><code class="sourceCode r">ci_lower</code>, <code class="sourceCode r">ci_upper</code> – skirtumo pasikliautinasis intervalas;</li><li><code class="sourceCode r">t</code> – testo statistika;</li><li><code class="sourceCode r">df</code> – parametras;</li><li><code class="sourceCode r">p</code> – p reikšmė;</li><li><code class="sourceCode r">cld</code> – kompaktiškas raidinis žymėjimas.</li></ol><p><br></p><p>Kompaktiškas raidinis žymėjimas (cld) atidedamas grafike:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)

cld_tukey &lt;-<span class="st"> </span>biostat<span class="op">::</span><span class="kw">make_cld</span>(rez_tukey)
biostat<span class="op">::</span><span class="kw">gg_boxplot_plus</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth,
                         <span class="dt">cld =</span> cld_tukey,
                         <span class="dt">sort_groups =</span> <span class="st">&quot;ascending&quot;</span>,
                         <span class="dt">sort_fun =</span> mean) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Svorio pasiskirstymas grupėmis&quot;</span>,
         <span class="dt">subtitle =</span> <span class="st">&quot;Grupės išdėstytos vidurkių didėjimo tvarka&quot;</span>,
         <span class="dt">x =</span> <span class="st">&quot;Grupė&quot;</span>,
         <span class="dt">y =</span> <span class="st">&quot;Svoris&quot;</span>,
         <span class="co"># Spalvų legendos pavadinimas</span>
         <span class="dt">fill =</span> <span class="st">&quot;Grupė&quot;</span>,
         <span class="dt">color =</span> <span class="st">&quot;Grupė&quot;</span>)
<span>## Warning: Some components of ... were not used: fun</span></code></pre><p><img src="10--01--ANOVA-ir-pan_files/figure-html/unnamed-chunk-54-1.png"width="384"style="display:block;margin:auto"></p><p>Su pasirinktu reikšmingumo lygmeniu <span class="math inline">\(\alpha\)</span>, tarp grupių, kurios pažymėtos ta pačia raide, skirtumai nėra statistiškai patikimi. T. y. <em>trt1</em> ir <em>trt2</em> skiriasi statistiškai reikšmingai, o visi kiti skirtumai – nereikšmingi.</p></div></div><div id="pavyzdys-2-kai-duomenys-normalieji-bet-dispersijos-nera-lygios"class="section level2"><h2><span class="header-section-number">19.5</span> Pavyzdys 2: kai duomenys normalieji, bet dispersijos nėra lygios</h2><div id="welch-anova-pagrindine-analize"class="section level3"><h3><span class="header-section-number">19.5.1</span> Welch ANOVA (pagrindinė analizė)</h3><p>Pavyzdys:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">data</span>(Moore, <span class="dt">package =</span> <span class="st">&quot;carData&quot;</span>)

?Moore</code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">glimpse</span>(Moore)
<span>## Observations: 45</span>
<span>## Variables: 4</span>
<span>## $ partner.status &lt;fct&gt; low, low, low, low, low, low, low, low, low, lo...</span>
<span>## $ conformity     &lt;int&gt; 8, 4, 8, 7, 10, 6, 12, 4, 13, 12, 4, 13, 7, 9, ...</span>
<span>## $ fcategory      &lt;fct&gt; low, high, high, low, low, low, medium, medium,...</span>
<span>## $ fscore         &lt;int&gt; 37, 57, 65, 20, 36, 18, 51, 44, 31, 36, 42, 56,...</span></code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(Moore)
<span>##   partner.status conformity fcategory fscore</span>
<span>## 1            low          8       low     37</span>
<span>## 2            low          4      high     57</span>
<span>## 3            low          8      high     65</span>
<span>## 4            low          7       low     20</span>
<span>## 5            low         10       low     36</span>
<span>## 6            low          6       low     18</span></code></pre><p>Atliekame tik mus dominančių kintamųjų suvestinę:</p><pre class="sourceCode r"><code class="sourceCode r">Moore <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">select</span>(fscore, fcategory) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">summary</span>()
<span>##      fscore       fcategory </span>
<span>##  Min.   :15.00   high  :15  </span>
<span>##  1st Qu.:35.00   low   :15  </span>
<span>##  Median :43.00   medium:15  </span>
<span>##  Mean   :43.11              </span>
<span>##  3rd Qu.:55.00              </span>
<span>##  Max.   :68.00</span></code></pre><pre class="sourceCode r"><code class="sourceCode r">biostat<span class="op">::</span><span class="kw">gg_boxplot_plus</span>(fscore <span class="op">~</span><span class="st"> </span>fcategory, <span class="dt">data =</span> Moore)</code></pre><p><img src="10--01--ANOVA-ir-pan_files/figure-html/unnamed-chunk-59-1.png"width="384"style="display:block;margin:auto"></p><p>Iš grafiko galime matyti, kad grupių vidurkiai skiriasi, bet jų dispersijos nėra lygios, nes dėžutės skirtingo dydžio.</p><p>Tikrinam normalumo prielaidą. Tam geriausia naudoti kelis metodus:</p><pre class="sourceCode r"><code class="sourceCode r">biostat<span class="op">::</span><span class="kw">test_normality</span>(fscore <span class="op">~</span><span class="st"> </span>fcategory, <span class="dt">data =</span> Moore)
<span>## </span>
<span>##  The results of Shapiro-Wilk normality test </span>
<span>## </span>
<span>##   fcategory statistic p.value    </span>
<span>## 1      high     0.932   0.293    </span>
<span>## 2       low     0.884   0.055 .  </span>
<span>## 3    medium     0.890   0.067 .  </span>
<span>## </span>
<span>## *** - p &lt; 0.001, ** - p &lt; 0.01, * - p &lt; 0.05, . - p &lt; 0.1</span></code></pre><pre class="sourceCode r"><code class="sourceCode r">biostat<span class="op">::</span><span class="kw">qq_plot</span>(fscore <span class="op">~</span><span class="st"> </span>fcategory, <span class="dt">data =</span> Moore)</code></pre><p><img src="10--01--ANOVA-ir-pan_files/figure-html/unnamed-chunk-61-1.png"width="384"style="display:block;margin:auto"> Duomenys normalumo prielaidą tenkina, nors yra ir ne visiško normalumo požymių.</p><p><br></p><p>Tikrinam dispersijų homogeniškumo (t. y., lygių dispersijų) prielaidą:</p><pre class="sourceCode r"><code class="sourceCode r">car<span class="op">::</span><span class="kw">leveneTest</span>(fscore <span class="op">~</span><span class="st"> </span>fcategory, <span class="dt">data =</span> Moore)
<span>## Levene&#39;s Test for Homogeneity of Variance (center = median)</span>
<span>##       Df F value   Pr(&gt;F)   </span>
<span>## group  2  6.9845 0.002406 **</span>
<span>##       42                    </span>
<span>## ---</span>
<span>## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></code></pre><p>Lygių dispersijų prielaida aiškiai pažeista <span class="math inline">\(p = 0.002406&lt;0.05\)</span></p><p><br></p><p>Welch ANOVA analizė:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">oneway.test</span>(fscore <span class="op">~</span><span class="st"> </span>fcategory, <span class="dt">data =</span> Moore)  
<span>## </span>
<span>##  One-way analysis of means (not assuming equal variances)</span>
<span>## </span>
<span>## data:  fscore and fcategory</span>
<span>## F = 90.59, num df = 2.000, denom df = 25.563, p-value =</span>
<span>## 0.000000000002494</span></code></pre><p>Rezultatas – statistiškai reikšmingas skirtumas (<span class="math inline">\(p = 2.5 \cdot10^{-12} &lt; \alpha =0.05\)</span>). Todėl verta atlikti <em>post-hoc</em> analizę.</p></div><div id="games-howell-kriterijus-post-hoc-analize"class="section level3"><h3><span class="header-section-number">19.5.2</span> Games-Howell kriterijus (<em>post-hoc</em> analizė)</h3><p>Jei imčių dispersijos nėra lygios, bet duomenys yra daugmaž normalieji, <strong>Games-Howell</strong> kriterijus yra tinkamas atlikti <strong>Welch ANOVA</strong> <em>post-hoc</em> analizę (porinius palyginimus).</p><pre class="sourceCode r"><code class="sourceCode r">rez_games_howell &lt;-<span class="st"> </span>biostat<span class="op">::</span><span class="kw">posthoc_anova</span>(fscore <span class="op">~</span><span class="st"> </span>fcategory, <span class="dt">data =</span> Moore,
                                           <span class="dt">method =</span> <span class="st">&quot;Games-Howell&quot;</span>)
rez_games_howell
<span>## Games-Howell test results (ANOVA post-hoc) </span>
<span>## </span>
<span>##        groups difference ci_lower ci_upper     t    df          p</span>
<span>## 1    low-high    -31.600  -37.763  -25.437 12.85 22.85 &lt;0.001 ***</span>
<span>## 2 medium-high    -14.667  -18.493  -10.841  9.55 24.99 &lt;0.001 ***</span>
<span>## 3  medium-low     16.933   11.115   22.752  7.40 18.69 &lt;0.001 ***</span>
<span>## </span>
<span>##    group  n   mean variance    sd cld spaced_cld</span>
<span>## 1   high 15 58.533   23.838 4.882   a        a__</span>
<span>## 2    low 15 26.933   66.924 8.181   b        _b_</span>
<span>## 3 medium 15 43.867   11.552 3.399   c        __c</span></code></pre><p>Svarbiausių rezultatų aprašymas pateiktas skyriuje <a href="ht-anova-ir-analogai.html#tukey-hsd-1">19.4.2</a>. Matome, kad tarp visų grupių skirtumai yra statistiškai reikšmingi.</p><p>Kompaktiškas raidinis žymėjimas (<em>cld</em>) atidedamas grafike:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)

cld_gh &lt;-<span class="st"> </span>biostat<span class="op">::</span><span class="kw">make_cld</span>(rez_games_howell)
biostat<span class="op">::</span><span class="kw">gg_boxplot_plus</span>(fscore <span class="op">~</span><span class="st"> </span>fcategory, <span class="dt">data =</span> Moore,
                         <span class="dt">cld =</span> cld_gh,
                         <span class="dt">sort_groups =</span> <span class="st">&quot;ascending&quot;</span>) <span class="op">+</span>
<span class="st">    </span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Grupių palyginimo grafikas&quot;</span>,
         <span class="dt">subtitle =</span> <span class="st">&quot;Grupės išdėstytos medianų didėjimo tvarka&quot;</span>)
<span>## Warning: Some components of ... were not used: fun</span></code></pre><p><img src="10--01--ANOVA-ir-pan_files/figure-html/unnamed-chunk-65-1.png"width="384"style="display:block;margin:auto"></p><p>Kiekvienai lyginamai grupei priskirtos <em>cld</em> žymėjimo raidės skirtingos, vadinasi – skirtumai tarp visų lygintų grupių yra statistiškai reikšmingi.</p></div></div><div id="pavyzdys-3-neparametrinis-kriterijus-2-ir-daugiau-grupems-lyginti"class="section level2"><h2><span class="header-section-number">19.6</span> Pavyzdys 3: neparametrinis kriterijus 2 ir daugiau grupėms lyginti</h2><div id="kw-pvz"class="section level3"><h3><span class="header-section-number">19.6.1</span> Kruskal-Wallis kriterijus (pagrindinė analizė)</h3><p><strong>Kruskal-Wallis</strong> kriterijus – tai neparametrinis <strong>ANOVA</strong> analogas, skirtas ranginiams arba normalumo kriterijaus netenkinantiems duomenims lygini. Į šį kriterijų taip pat galima žiūrėti kaip į apibendrintą <strong>Mann-Whitney-Wilcoxon</strong> kriterijaus variantą, kai imčių daugiau negu dvi.</p><p>Pavyzdys:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(airquality)
<span class="kw">head</span>(airquality)
<span>##   Ozone Solar.R Wind Temp Month Day</span>
<span>## 1    41     190  7.4   67     5   1</span>
<span>## 2    36     118  8.0   72     5   2</span>
<span>## 3    12     149 12.6   74     5   3</span>
<span>## 4    18     313 11.5   62     5   4</span>
<span>## 5    NA      NA 14.3   56     5   5</span>
<span>## 6    28      NA 14.9   66     5   6</span></code></pre><pre class="sourceCode r"><code class="sourceCode r">biostat<span class="op">::</span><span class="kw">gg_boxplot_plus</span>(Ozone <span class="op">~</span><span class="st"> </span><span class="kw">factor</span>(Month), <span class="dt">data =</span> airquality, <span class="dt">add_mean_ci =</span> <span class="ot">FALSE</span>)
<span>## Warning: Removed 37 rows containing non-finite values (stat_boxplot).</span>
<span>## Warning: Removed 37 rows containing missing values (geom_point).</span></code></pre><p><img src="10--01--ANOVA-ir-pan_files/figure-html/unnamed-chunk-67-1.png"width="384"style="display:block;margin:auto"> Pašalinome vidurkių pasikliautinuosius intervalus (<code class="sourceCode r">add_mean_ci =<span class="st"> </span><span class="ot">FALSE</span></code>), nes analizė, kurią naudosime, nelygina vidurkių.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">kruskal.test</span>(Ozone <span class="op">~</span><span class="st"> </span>Month, <span class="dt">data =</span> airquality)
<span>## </span>
<span>##  Kruskal-Wallis rank sum test</span>
<span>## </span>
<span>## data:  Ozone by Month</span>
<span>## Kruskal-Wallis chi-squared = 29.267, df = 4, p-value = 0.000006901</span></code></pre><p>Skirtumas yra statistiškai reikšmingas (bent viena grupė skiriasi nuo kitų), nes <span class="math inline">\(p = 6.9\cdot10^{-6} &lt; 0.05\)</span>. Šie Kruskal-Wallis kriterijaus taikymo rezultatai aprašyti skyriuje <a href="ht-anova-ir-analogai.html#ANOVA-rezultatu-aprasymas">19.2.12</a>.</p><p>Atliekame <em>post-hoc</em> analizę.</p></div><div id="conover-iman-kriterijus-post-hoc-analize"class="section level3"><h3><span class="header-section-number">19.6.2</span> Conover-Iman kriterijus (<em>post-hoc</em> analizė)</h3><p><strong>Conover-Iman</strong> kriterijus naudojamas atlikti <strong>Kurskal-Wallis</strong> kriterijaus <em>post-hoc</em> analizę (porinius palyginimus).</p><br><div class="avoid"><p><strong>Conover-Iman</strong> kriterijų galima taikyti tada ir tik tada, kai <strong>Kurskal-Wallis</strong> kriterijaus taikymo rezultatai yra statistiškai reikšmingi.</p></div><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(PMCMR)
rez_conover &lt;-<span class="st"> </span><span class="kw">posthoc.kruskal.conover.test</span>(Ozone <span class="op">~</span><span class="st"> </span>Month, <span class="dt">data =</span> airquality)
<span>## Warning in posthoc.kruskal.conover.test.default(c(41L, 36L, 12L, 18L,</span>
<span>## 28L, : Ties are present. Quantiles were corrected for ties.</span>

rez_conover
<span>## </span>
<span>##  Pairwise comparisons using Conover&#39;s-test for multiple  </span>
<span>##                          comparisons of independent samples </span>
<span>## </span>
<span>## data:  Ozone by Month </span>
<span>## </span>
<span>##   5        6      7      8     </span>
<span>## 6 0.8843   -      -      -     </span>
<span>## 7 0.000019 0.0721 -      -     </span>
<span>## 8 0.000067 0.1109 1.0000 -     </span>
<span>## 9 0.5424   1.0000 0.0031 0.0084</span>
<span>## </span>
<span>## P value adjustment method: holm</span></code></pre><p>Rezultatų apibendrinimas kompaktišku žymėjimu.</p><pre class="sourceCode r"><code class="sourceCode r">cld_conover &lt;-<span class="st"> </span>biostat<span class="op">::</span><span class="kw">make_cld</span>(rez_conover)
cld_conover
<span>##   group cld spaced_cld</span>
<span>## 1     5   a         a_</span>
<span>## 2     6  ab         ab</span>
<span>## 3     7   b         _b</span>
<span>## 4     8   b         _b</span>
<span>## 5     9   a         a_</span></code></pre><p>Kompaktiškas raidinis žymėjimas (<em>cld</em>) gali būti pateiktas grafike.</p><pre class="sourceCode r"><code class="sourceCode r">biostat<span class="op">::</span><span class="kw">gg_boxplot_plus</span>(Ozone <span class="op">~</span><span class="st"> </span><span class="kw">factor</span>(Month), <span class="dt">data =</span> airquality,
                         <span class="dt">cld =</span> cld_conover,
                         <span class="dt">cld_color =</span> <span class="st">&quot;blue&quot;</span>,
                         <span class="dt">add_mean_ci =</span> <span class="ot">FALSE</span>)
<span>## Warning: Removed 37 rows containing non-finite values (stat_boxplot).</span>
<span>## Warning: Removed 37 rows containing missing values (geom_point).</span></code></pre><p><img src="10--01--ANOVA-ir-pan_files/figure-html/unnamed-chunk-72-1.png"width="384"style="display:block;margin:auto"></p></div></div><div id="ANOVA-tipo-analize"class="section level2"><h2><span class="header-section-number">19.7</span> Video pavyzdys</h2><p>Šio pavyzdžio analizė skirta atsakyti į klausimą, ar skirtingų organų vėžiu sergančių žmonių išgyvenimo trukmė skiriasi. Duomenis galite atsisiųsti iš čia: <a href="https://mokymai.github.io/pratybos/duomenys/isgyvenamumas_sergant_veziu.xlsx">duomenys <i class="fas fa-download"></i></a>.</p><p>Preliminarus video epizodo siužetas:</p><ol style="list-style-type:decimal"><li>Susiformuojame klausimą, į kurį norime atsakyti.</li><li>Duomenys jau yra parsiųsti ir įkelti į aplanką su <em>RStudio</em> projektu. Atsidarome projektą ir patikriname, ar jis tinkamai sukonfigūruotas. Atsidarome <em>Rcmdr</em> (reikalinga <em>RcmdrPlugin.biostat</em> versija <em>0.0.17</em> arba naujesnė).</li><li>Įsikeliame duomenis iš reikiamo <em>Excel</em> bylos lapo ir apžiūrime juos. Duomenyse yra viena visiškai tuščia eilutė (vien tik <code>NA</code> reikšmės).</li><li>Pašaliname tuščią eilutę.</li><li>Duomenys nepriklausomi (nes kiekvienoje grupėje vis kiti pacientai), bet pateikti plačiuoju formatu, todėl pasiverčiame į ilgąjį.</li><li>Išgyvenamumo trukmė pateikta dienomis. Ją pasiversime į metus padalindami iš 365 dienų metams.</li><li>Nusibraižome duomenis, atliekame skaitinę suvestinę.</li><li>Duomenų mažai, grupės skirtingo dydžio, duomenų pasiskirstymas nėra idealiai normalusis, todėl analizei pasirinktas neparametrinis Kruskal-Wallis (KW) kriterijus. Jis vykdomas nukopijuojant kodą iš pratybų tinklapio ir jį pritaikant savo reikmėms.</li><li>KW analizės rezultatas rodo, kad yra statistiškai reikšmingas skirtumas bent tarp dviejų grupių, todėl atliekame porinius lyginimus nukopijuodami reikiamos <em>post-hoc</em> analizės kodą ir jį pakeisdami.</li><li>Aprašome rezultatus (aprašymo pavyzdys pateiktas po video epizodu).</li></ol><br><center><iframe width="640"height="360"src="https://www.youtube.com/embed/obv6KqVuqHA?rel=0"frameborder="0"allow="autoplay; encrypted-media"allowfullscreen></iframe></center><div class="corollary"><span id="cor:anova-like"class="corollary"><strong>Video epizodas 19.1 </strong></span>Vienfaktorės ANOVA tipo analizės pavyzdys, kai duomenys nėra normalieji. Duomenys pateikti panašiu formatu kaip ir įskaitinėje užduotyje apie žirnius. <strong>Pastaba:</strong> epizode nėra komentarų bei pasakojimo.</div><p><br></p><p>Rezultatų aprašymas galėtų būti daugmaž toks:</p><p>„Tirta žmonių, sergančių bronchų, krutų, kiaušidžių, skrandžio, žarnų vėžiu, išgyvenimo trukmė. Atlikus statistinę analizę paaiškėjo, kad ši trukmė sergant skirtingų organų vėžiu statistiškai reikšmingai skiriasi (Kruskal-Wallis kriterijus, <span class="math inline">\(\chi^2\)</span>(4) = 14.95, <em>p</em> = 0.005). Poriniai lyginimai (Conover-Iman <em>post-hoc</em> kriterijus su Holm korekcija <em>p</em> reikšmėms) atskleidė, kad statistiškai reikšmingai skiriasi krutų ir bronchų (<em>p</em> = 0.006) bei krutų ir skrandžio (<em>p</em> = 0.014) vėžiu sergančių pacientų išgyvenamumo trukmė. Abiem paminėtais atvejais sergantys krutų vėžiu išgyveno ilgiau (lentelė … bei pav. …).“</p><p>(Porinių lyginimų <em>p</em> reikšmės paimtos iš lentelės-matricos, kurią sugeneravo Conover-Iman analizę vykdančios funkcijos).</p></div></div></section></div></div></div><a href="ht-padetis.html"class="navigation navigation-prev"aria-label="Previous page"><i class="fa fa-angle-left"></i></a> <a href="rysys-tarp-kintamuju.html"class="navigation navigation-next"aria-label="Next page"><i class="fa fa-angle-right"></i></a></div></div><script src="libs/gitbook-2.6.7/js/app.min.js"></script><script src="libs/gitbook-2.6.7/js/lunr.js"></script><script src="libs/gitbook-2.6.7/js/plugin-search.js"></script><script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script><script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script><script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script><script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script><script>gitbook.require(["gitbook"],function(t){t.start({sharing:!1,fontsettings:{theme:"sepia",family:"sans",size:2},edit:null,history:{link:null,text:null},download:null,toc:{collapse:"section",scroll_highlight:!0},toolbar:{position:"static"},search:!0})})</script><script>!function(){var t=document.createElement("script");t.type="text/javascript";var e="true";""!==e&&"true"!==e||(e="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML"),"file:"!==location.protocol&&/^https?:/.test(e)&&(e=e.replace(/^https?:/,"")),t.src=e,document.getElementsByTagName("head")[0].appendChild(t)}()</script></body></html>