<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"xml:lang=""><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-132829179-1"></script><script>function gtag(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[],gtag("js",new Date),gtag("config","UA-132829179-1")</script><meta charset="utf-8"><meta http-equiv="X-UA-Compatible"content="IE=edge"><title>12. Pasikliautinieji intervalai (PI) klasikiniais metodais | Biostatistika</title><meta name="description"content="12. Pasikliautinieji intervalai (PI) klasikiniais metodais | Biostatistika"><meta name="generator"content="bookdown  and GitBook 2.6.7"><meta property="og:title"content="12. Pasikliautinieji intervalai (PI) klasikiniais metodais | Biostatistika"><meta property="og:type"content="book"><meta name="twitter:card"content="summary"><meta name="twitter:title"content="12. Pasikliautinieji intervalai (PI) klasikiniais metodais | Biostatistika"><meta name="author"content="Vilmantas Gėgžna"><meta name="viewport"content="width=device-width,initial-scale=1"><meta name="apple-mobile-web-app-capable"content="yes"><meta name="apple-mobile-web-app-status-bar-style"content="black"><link rel="prev"href="skirstinio-parinkimas.html"><link rel="next"href="pi-saviranka.html"><script src="libs/jquery-2.2.3/jquery.min.js"></script><link href="libs/gitbook-2.6.7/css/style.css"rel="stylesheet"><link href="libs/gitbook-2.6.7/css/plugin-table.css"rel="stylesheet"><link href="libs/gitbook-2.6.7/css/plugin-bookdown.css"rel="stylesheet"><link href="libs/gitbook-2.6.7/css/plugin-highlight.css"rel="stylesheet"><link href="libs/gitbook-2.6.7/css/plugin-search.css"rel="stylesheet"><link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css"rel="stylesheet"><link href="libs/font-awesome-5.3.1/css/fontawesome-all.min.css"rel="stylesheet"><script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script><link href="libs/datatables-css-0.0.0/datatables-crosstalk.css"rel="stylesheet"><script src="libs/datatables-binding-0.5/datatables.js"></script><link href="libs/dt-core-1.10.16/css/jquery.dataTables.min.css"rel="stylesheet"><link href="libs/dt-core-1.10.16/css/jquery.dataTables.extra.css"rel="stylesheet"><script src="libs/dt-core-1.10.16/js/jquery.dataTables.min.js"></script><link href="libs/dt-plugin-searchhighlight-1.10.16/dataTables.searchHighlight.css"rel="stylesheet"><script src="libs/dt-plugin-searchhighlight-1.10.16/dataTables.searchHighlight.min.js"></script><script src="libs/dt-plugin-searchhighlight-1.10.16/jquery.highlight.js"></script><link href="libs/crosstalk-1.0.0/css/crosstalk.css"rel="stylesheet"><script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script><style type="text/css">a.sourceLine{display:inline-block;line-height:1.25}a.sourceLine{pointer-events:none;color:inherit;text-decoration:inherit}a.sourceLine:empty{height:1.2em}.sourceCode{overflow:visible}code.sourceCode{white-space:pre;position:relative}div.sourceCode{margin:1em 0}pre.sourceCode{margin:0}@media screen{div.sourceCode{overflow:auto}}@media print{code.sourceCode{white-space:pre-wrap}a.sourceLine{text-indent:-1em;padding-left:1em}}pre.numberSource a.sourceLine{position:relative;left:-4em}pre.numberSource a.sourceLine::before{content:attr(title);position:relative;left:-1em;text-align:right;vertical-align:baseline;border:none;pointer-events:all;display:inline-block;-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;padding:0 4px;width:4em;background-color:#2a211c;color:#bdae9d}pre.numberSource{margin-left:3em;border-left:1px solid #bdae9d;padding-left:4px}div.sourceCode{color:#bdae9d;background-color:#2a211c}@media screen{a.sourceLine::before{text-decoration:underline}}code span.al{color:#ff0}code span.an{color:#06f;font-weight:700;font-style:italic}code span.bn{color:#44aa43}code span.cf{color:#43a8ed;font-weight:700}code span.ch{color:#049b0a}code span.co{color:#06f;font-weight:700;font-style:italic}code span.do{color:#06f;font-style:italic}code span.dt{text-decoration:underline}code span.dv{color:#44aa43}code span.er{color:#ff0;font-weight:700}code span.fl{color:#44aa43}code span.fu{color:#ff9358;font-weight:700}code span.in{color:#06f;font-weight:700;font-style:italic}code span.kw{color:#43a8ed;font-weight:700}code span.pp{font-weight:700}code span.sc{color:#049b0a}code span.ss{color:#049b0a}code span.st{color:#049b0a}code span.vs{color:#049b0a}code span.wa{color:#ff0;font-weight:700}</style><link rel="stylesheet"href="style.css"type="text/css"><link rel="stylesheet"href="kbd.css"type="text/css"><link rel="icon"href="fig/icons/favicon.png"></head><body><div class="book without-animation with-summary font-size-2 font-family-1"data-basepath="."><div class="book-summary"><nav role="navigation"><ul class="summary"><li><a href="../">Mokymai (pagrindinis)</a></li><li class="divider"></li><li class="chapter"data-level=""data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Pradžia</a></li><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html"><i class="fa fa-check"></i>Apie</a><ul><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#apie-sia-svetaine"><i class="fa fa-check"></i>Apie šią svetainę</a><ul><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#svetaines-valdymas-klavisais"><i class="fa fa-check"></i>Svetainės valdymas klavišais</a></li><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#pastabos-apie"><i class="fa fa-check"></i>Pastabos</a></li><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#dezuciu-reiksmes"><i class="fa fa-check"></i>Dėžučių reikšmės</a></li></ul></li><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#reikalavimai"><i class="fa fa-check"></i>Reikalavimai studentui</a><ul><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#igudziai"><i class="fa fa-check"></i>Įgūdžiai</a></li><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#reikmenys-pratyboms"><i class="fa fa-check"></i>Reikmenys pratyboms</a></li><li class="chapter"data-level=""data-path="apie.html"><a href="apie.html#reikmenys-paskaitoms"><i class="fa fa-check"></i>Reikmenys paskaitoms</a></li></ul></li></ul></li><li class="part"><span><b>Pagrindai</b></span></li><li class="chapter"data-level="1"data-path="diegimas.html"><a href="diegimas.html"><i class="fa fa-check"></i><b>1</b> Programų diegimas ir nustatymai</a><ul><li class="chapter"data-level="1.1"data-path="diegimas.html"><a href="diegimas.html#apie-r"><i class="fa fa-check"></i><b>1.1</b> Apie programą <strong><em>R</em></strong></a></li><li class="chapter"data-level="1.2"data-path="diegimas.html"><a href="diegimas.html#pastabos-pries-diegiant"><i class="fa fa-check"></i><b>1.2</b> Pastabos prieš diegiant</a></li><li class="chapter"data-level="1.3"data-path="diegimas.html"><a href="diegimas.html#pagrindines-programos"><i class="fa fa-check"></i><b>1.3</b> Pagrindinės programos</a><ul><li class="chapter"data-level="1.3.1"data-path="diegimas.html"><a href="diegimas.html#diegti-r"><i class="fa fa-check"></i><b>1.3.1</b> Programa <strong><em>R</em></strong></a></li><li class="chapter"data-level="1.3.2"data-path="diegimas.html"><a href="diegimas.html#diegti-rstudio"><i class="fa fa-check"></i><b>1.3.2</b> Programa <strong><em>RStudio</em></strong></a></li><li class="chapter"data-level="1.3.3"data-path="diegimas.html"><a href="diegimas.html#mac-naudotojams"><i class="fa fa-check"></i><b>1.3.3</b> <em>Mac</em> naudotojams</a></li></ul></li><li class="chapter"data-level="1.4"data-path="diegimas.html"><a href="diegimas.html#diegti-r-paketus"><i class="fa fa-check"></i><b>1.4</b> <strong><em>R</em></strong> paketų diegimas</a><ul><li class="chapter"data-level="1.4.1"data-path="diegimas.html"><a href="diegimas.html#diegti-r-sprendimai"><i class="fa fa-check"></i><b>1.4.1</b> Kilus problemų dėl paketų diegimo…</a></li></ul></li><li class="chapter"data-level="1.5"data-path="diegimas.html"><a href="diegimas.html#konfig"><i class="fa fa-check"></i><b>1.5</b> Programų konfigūravimas</a><ul><li class="chapter"data-level="1.5.1"data-path="diegimas.html"><a href="diegimas.html#spartusis-veikimas"><i class="fa fa-check"></i><b>1.5.1</b> Sparčiojo veikimo režimas</a><ul><li><a href="diegimas.html#win10-power-opts"><strong><em>Windows 10</em></strong></a></li></ul></li><li class="chapter"data-level="1.5.2"data-path="diegimas.html"><a href="diegimas.html#rs-config-utf8"><i class="fa fa-check"></i><b>1.5.2</b> <strong><em>RStudio</em></strong>: <strong>UTF-8</strong> koduotė dokumentams</a></li><li class="chapter"data-level="1.5.3"data-path="diegimas.html"><a href="diegimas.html#rs-config"><i class="fa fa-check"></i><b>1.5.3</b> <strong><em>RStudio</em></strong>: kiti nustatymai</a></li></ul></li><li class="chapter"data-level="1.6"data-path="diegimas.html"><a href="diegimas.html#diegti-papildoma"><i class="fa fa-check"></i><b>1.6</b> Papildomos instrukcijos</a></li><li class="chapter"data-level="1.7"data-path="diegimas.html"><a href="diegimas.html#paskyros"><i class="fa fa-check"></i><b>1.7</b> Paskyros</a><ul><li class="chapter"data-level="1.7.1"data-path="diegimas.html"><a href="diegimas.html#emokymai_paskyra"><i class="fa fa-check"></i><b>1.7.1</b> „Emokymai“ sistema</a></li><li class="chapter"data-level="1.7.2"data-path="diegimas.html"><a href="diegimas.html#datacamp_paskyra"><i class="fa fa-check"></i><b>1.7.2</b> „Data Camp“ paskyra</a></li><li class="chapter"data-level="1.7.3"data-path="diegimas.html"><a href="diegimas.html#github-paskyra"><i class="fa fa-check"></i><b>1.7.3</b> „GitHub“ paskyra</a></li></ul></li><li class="chapter"data-level=""data-path="diegimas.html"><a href="diegimas.html#diegimas-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="2"data-path="pradines-savokos.html"><a href="pradines-savokos.html"><i class="fa fa-check"></i><b>2</b> Pradinės duomenų analizės sąvokos (teorija)</a><ul><li class="chapter"data-level="2.1"data-path="pradines-savokos.html"><a href="pradines-savokos.html#statistinio-tyrimo-ciklas"><i class="fa fa-check"></i><b>2.1</b> Statistinio tyrimo ciklas</a></li><li class="chapter"data-level="2.2"data-path="pradines-savokos.html"><a href="pradines-savokos.html#svarbiausia-analizes-dalis-klausimas"><i class="fa fa-check"></i><b>2.2</b> Svarbiausia analizės dalis – klausimas</a></li><li class="chapter"data-level="2.3"data-path="pradines-savokos.html"><a href="pradines-savokos.html#generaline-aibe-imtis-ir-duomenys"><i class="fa fa-check"></i><b>2.3</b> Generalinė aibė, imtis ir duomenys</a></li><li class="chapter"data-level="2.4"data-path="pradines-savokos.html"><a href="pradines-savokos.html#statistikos-mokslas-ir-jo-dalys"><i class="fa fa-check"></i><b>2.4</b> Statistikos mokslas ir jo dalys</a></li><li class="chapter"data-level="2.5"data-path="pradines-savokos.html"><a href="pradines-savokos.html#stat-kintamuju-tipai"><i class="fa fa-check"></i><b>2.5</b> Kintamųjų tipai statistikoje</a><ul><li class="chapter"data-level=""data-path="pradines-savokos.html"><a href="pradines-savokos.html#veiksmai-su-kintamaisiais"><i class="fa fa-check"></i>Kokius veiksmus galima atlikti su skirtingų tipų kintamųjų reikšmėmis?</a></li><li class="chapter"data-level=""data-path="pradines-savokos.html"><a href="pradines-savokos.html#apsimeteteliai"><i class="fa fa-check"></i>Kokie kintamieji atrodo kaip skaitiniai (kiekybiniai), bet iš tiesų yra kategoriniai?</a></li></ul></li><li class="chapter"data-level="2.6"data-path="pradines-savokos.html"><a href="pradines-savokos.html#duomenu-strukturos-statistikoje"><i class="fa fa-check"></i><b>2.6</b> Duomenų saugojimo formos</a></li><li class="chapter"data-level="2.7"data-path="pradines-savokos.html"><a href="pradines-savokos.html#duomenu-eilutes"><i class="fa fa-check"></i><b>2.7</b> Duomenų eilutės</a></li><li class="chapter"data-level="2.8"data-path="pradines-savokos.html"><a href="pradines-savokos.html#duomenu-lenteles"><i class="fa fa-check"></i><b>2.8</b> Duomenų lentelės</a></li><li class="chapter"data-level=""data-path="pradines-savokos.html"><a href="pradines-savokos.html#pradines-savokos-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="3"data-path="rstudio.html"><a href="rstudio.html"><i class="fa fa-check"></i><b>3</b> Programa <strong><em>RStudio</em></strong></a><ul><li class="chapter"data-level="3.1"data-path="rstudio.html"><a href="rstudio.html#rs-intro"><i class="fa fa-check"></i><b>3.1</b> <strong><em>RStudio</em></strong></a></li><li class="chapter"data-level="3.2"data-path="rstudio.html"><a href="rstudio.html#rstudio-langu-isdestymas"><i class="fa fa-check"></i><b>3.2</b> <strong><em>RStudio</em></strong> langų išdėstymas</a></li><li class="chapter"data-level="3.3"data-path="rstudio.html"><a href="rstudio.html#komandu-langas"><i class="fa fa-check"></i><b>3.3</b> Komandų langas</a></li><li class="chapter"data-level="3.4"data-path="rstudio.html"><a href="rstudio.html#redaktoriaus-langas"><i class="fa fa-check"></i><b>3.4</b> Redaktoriaus langas</a></li><li class="chapter"data-level="3.5"data-path="rstudio.html"><a href="rstudio.html#rs-paketai"><i class="fa fa-check"></i><b>3.5</b> Paketų valdymo langas</a></li><li class="chapter"data-level="3.6"data-path="rstudio.html"><a href="rstudio.html#rs-help"><i class="fa fa-check"></i><b>3.6</b> Pagalbos langas</a></li><li class="chapter"data-level="3.7"data-path="rstudio.html"><a href="rstudio.html#rs-projektai"><i class="fa fa-check"></i><b>3.7</b> <strong><em>RStudio</em></strong> projektai</a></li><li class="chapter"data-level=""data-path="rstudio.html"><a href="rstudio.html#rstudio-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="4"data-path="r-pradmenys.html"><a href="r-pradmenys.html"><i class="fa fa-check"></i><b>4</b> Programos <strong><em>R</em></strong> pradmenys</a><ul><li class="chapter"data-level="4.1"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-sintakse-intro"><i class="fa fa-check"></i><b>4.1</b> Pirmieji <strong><em>R</em></strong> kodo elementai</a><ul><li class="chapter"data-level="4.1.1"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-kodo-komentarai"><i class="fa fa-check"></i><b>4.1.1</b> <strong><em>R</em></strong> kodo komentarai (<code>#</code>)</a></li><li class="chapter"data-level="4.1.2"data-path="r-pradmenys.html"><a href="r-pradmenys.html#rezultatu-zenklinimas"><i class="fa fa-check"></i><b>4.1.2</b> Rezultatų ženklinimas (<code>##</code>)</a></li><li class="chapter"data-level="4.1.3"data-path="r-pradmenys.html"><a href="r-pradmenys.html#elementu-eiles-numeriu-zymejimas"><i class="fa fa-check"></i><b>4.1.3</b> Elementų eilės numerių žymėjimas: <code>[ ]</code></a></li><li class="chapter"data-level="4.1.4"data-path="r-pradmenys.html"><a href="r-pradmenys.html#kitu-elementu-spalvinis-zymejimas"><i class="fa fa-check"></i><b>4.1.4</b> Kitų elementų spalvinis žymėjimas</a></li><li class="chapter"data-level="4.1.5"data-path="r-pradmenys.html"><a href="r-pradmenys.html#programos-kodas-blokais-ir-tekste"><i class="fa fa-check"></i><b>4.1.5</b> Programos kodas: blokais ir tekste</a></li></ul></li><li class="chapter"data-level="4.2"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-funkcijos-ir-operatoriai"><i class="fa fa-check"></i><b>4.2</b> <strong><em>R</em></strong> funkcijos</a><ul><li class="chapter"data-level="4.2.1"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-funkcijos"><i class="fa fa-check"></i><b>4.2.1</b> Įprastinės funkcijos ir jų argumentai</a></li><li class="chapter"data-level="4.2.2"data-path="r-pradmenys.html"><a href="r-pradmenys.html#operatoriai"><i class="fa fa-check"></i><b>4.2.2</b> Operatoriai</a></li></ul></li><li class="chapter"data-level="4.3"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-objektai"><i class="fa fa-check"></i><b>4.3</b> <strong><em>R</em></strong> objektai</a><ul><li class="chapter"data-level="4.3.1"data-path="r-pradmenys.html"><a href="r-pradmenys.html#objektu-kurimas"><i class="fa fa-check"></i><b>4.3.1</b> Objektų kūrimas</a></li><li class="chapter"data-level="4.3.2"data-path="r-pradmenys.html"><a href="r-pradmenys.html#workspace"><i class="fa fa-check"></i><b>4.3.2</b> Darbinė erdvė</a></li><li class="chapter"data-level="4.3.3"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-objektu-pavadinimai"><i class="fa fa-check"></i><b>4.3.3</b> Objektų pavadinimai</a><ul><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#leistini-simboliai-pavadinimuose"><i class="fa fa-check"></i>Leistini simboliai pavadinimuose</a></li><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#ar-didziosios-ir-mazosios-raides-svarbu"><i class="fa fa-check"></i>Ar didžiosios ir mažosios raidės – svarbu?</a></li><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#pavadinimu-rasymo-stilius-rekomendacijos"><i class="fa fa-check"></i>Pavadinimų rašymo stilius (rekomendacijos)</a></li><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#netaisyklingi-pavadinimai"><i class="fa fa-check"></i>Netaisyklingi pavadinimai</a></li></ul></li></ul></li><li class="chapter"data-level="4.4"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-duomenu-tipai"><i class="fa fa-check"></i><b>4.4</b> Svarbiausi <strong><em>R</em></strong> duomenų tipai</a><ul><li class="chapter"data-level="4.4.1"data-path="r-pradmenys.html"><a href="r-pradmenys.html#skaitiniai-kintamieji"><i class="fa fa-check"></i><b>4.4.1</b> Skaitiniai kintamieji</a><ul><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-numeric"><i class="fa fa-check"></i>Klasė „numeric“</a></li><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-integer"><i class="fa fa-check"></i>Klasė „integer“</a></li></ul></li><li class="chapter"data-level="4.4.2"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-logical"><i class="fa fa-check"></i><b>4.4.2</b> Loginės reikšmės</a></li><li class="chapter"data-level="4.4.3"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-character"><i class="fa fa-check"></i><b>4.4.3</b> Tekstiniai kintamieji</a></li><li class="chapter"data-level="4.4.4"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-kategoriniai"><i class="fa fa-check"></i><b>4.4.4</b> Faktoriai – kategoriniai kintamieji</a><ul><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#nominalieji-duomenys"><i class="fa fa-check"></i>Nominalieji duomenys</a></li><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#ranginiai-duomenys"><i class="fa fa-check"></i>Ranginiai duomenys</a></li></ul></li></ul></li><li class="chapter"data-level="4.5"data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-duomenu-strukturos"><i class="fa fa-check"></i><b>4.5</b> <strong><em>R</em></strong> duomenų struktūros</a></li><li class="chapter"data-level="4.6"data-path="r-pradmenys.html"><a href="r-pradmenys.html#klausimai-r-ivadas"><i class="fa fa-check"></i><b>4.6</b> Klausimai savikontrolei</a></li><li class="chapter"data-level=""data-path="r-pradmenys.html"><a href="r-pradmenys.html#r-pradmenys-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="5"data-path="r-paketai.html"><a href="r-paketai.html"><i class="fa fa-check"></i><b>5</b> <strong><em>R</em></strong> paketai</a><ul><li class="chapter"data-level="5.1"data-path="r-paketai.html"><a href="r-paketai.html#pkg-diegimas-uzkroviumas"><i class="fa fa-check"></i><b>5.1</b> Paketų užkrovimas</a></li><li class="chapter"data-level="5.2"data-path="r-paketai.html"><a href="r-paketai.html#rs-packages"><i class="fa fa-check"></i><b>5.2</b> <strong><em>RStudio</em></strong> langas <em>Packages</em></a></li><li class="chapter"data-level="5.3"data-path="r-paketai.html"><a href="r-paketai.html#r-paketu-saugyklos"><i class="fa fa-check"></i><b>5.3</b> <strong>R</strong> paketų saugyklos</a></li><li class="chapter"data-level="5.4"data-path="r-paketai.html"><a href="r-paketai.html#apie-paketu-diegima"><i class="fa fa-check"></i><b>5.4</b> Apie paketų diegimą</a><ul><li class="chapter"data-level="5.4.1"data-path="r-paketai.html"><a href="r-paketai.html#diegimas-is-cran"><i class="fa fa-check"></i><b>5.4.1</b> Diegimas iš <em>CRAN</em></a></li><li class="chapter"data-level="5.4.2"data-path="r-paketai.html"><a href="r-paketai.html#diegimas-is-github"><i class="fa fa-check"></i><b>5.4.2</b> Diegimas iš <em>GitHub</em></a></li></ul></li><li class="chapter"data-level="5.5"data-path="r-paketai.html"><a href="r-paketai.html#funkciju-naudojimas-neuzkrovus-paketu"><i class="fa fa-check"></i><b>5.5</b> Funkcijų naudojimas neužkrovus paketų</a></li><li class="chapter"data-level="5.6"data-path="r-paketai.html"><a href="r-paketai.html#placiau-apie-paketus"><i class="fa fa-check"></i><b>5.6</b> Plačiau apie paketus</a></li><li class="chapter"data-level=""data-path="r-paketai.html"><a href="r-paketai.html#r-paketai-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="6"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html"><i class="fa fa-check"></i><b>6</b> Skaitinės suvestinės (teorija)</a><ul><li class="chapter"data-level="6.1"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#aprasomoji-statistika"><i class="fa fa-check"></i><b>6.1</b> Aprašomoji statistika</a></li><li class="chapter"data-level="6.2"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#ga-parametrai-ir-imties-statistikos"><i class="fa fa-check"></i><b>6.2</b> GA parametrai ir imties statistikos</a></li><li class="chapter"data-level="6.3"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#suvestines-1"><i class="fa fa-check"></i><b>6.3</b> Aprašomosios statistikos</a></li><li class="chapter"data-level="6.4"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#imties-dydis--privaloma"><i class="fa fa-check"></i><b>6.4</b> Imties dydis – jį privaloma pateikti ataskaitoje</a></li><li class="chapter"data-level="6.5"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#kintamojo-aprasymas"><i class="fa fa-check"></i><b>6.5</b> Kaip statistiškai aprašyti vieno kintamojo reikšmes?</a></li><li class="chapter"data-level="6.6"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#kaip-pasirinkti-tolydiesiems-duomenims-tinkamas-suvestines"><i class="fa fa-check"></i><b>6.6</b> Kaip pasirinkti tolydiesiems duomenims tinkamas suvestines?</a></li><li class="chapter"data-level="6.7"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#kvantiliai-ir-kvartiliai"><i class="fa fa-check"></i><b>6.7</b> Kvantiliai ir kvartiliai</a></li><li class="chapter"data-level="6.8"data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#statistinis-daznis-ir-dazniu-lenteles"><i class="fa fa-check"></i><b>6.8</b> Statistinis dažnis ir dažnių lentelės</a></li><li class="chapter"data-level=""data-path="teorija-skaitines-suvestines.html"><a href="teorija-skaitines-suvestines.html#teorija-skaitines-suvestines-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="7"data-path="r-vektoriai.html"><a href="r-vektoriai.html"><i class="fa fa-check"></i><b>7</b> Darbas su duomenų sekomis</a><ul><li class="chapter"data-level="7.1"data-path="r-vektoriai.html"><a href="r-vektoriai.html#specialiosios-paskirties-zodziai"><i class="fa fa-check"></i><b>7.1</b> Specialiosios paskirties žodžiai</a></li><li class="chapter"data-level="7.2"data-path="r-vektoriai.html"><a href="r-vektoriai.html#bendrieji-darbo-su-vektoriais-principai"><i class="fa fa-check"></i><b>7.2</b> Bendrieji darbo su vektoriais principai</a><ul><li class="chapter"data-level="7.2.1"data-path="r-vektoriai.html"><a href="r-vektoriai.html#vektoriaus-kurimas"><i class="fa fa-check"></i><b>7.2.1</b> Vektoriaus kūrimas</a><ul><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#skirtingu-tipu-duomenys-vienoje-sekoje"><i class="fa fa-check"></i>Skirtingų tipų duomenys vienoje sekoje?</a></li></ul></li><li class="chapter"data-level="7.2.2"data-path="r-vektoriai.html"><a href="r-vektoriai.html#vektoriaus-savybiu-tikrinimas"><i class="fa fa-check"></i><b>7.2.2</b> Vektoriaus savybių tikrinimas</a></li><li class="chapter"data-level="7.2.3"data-path="r-vektoriai.html"><a href="r-vektoriai.html#vektoriaus-elementu-pasirinkimas"><i class="fa fa-check"></i><b>7.2.3</b> Vektoriaus elementų pasirinkimas</a><ul><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#pasirinkimas-pagal-elemento-pavadinima"><i class="fa fa-check"></i>Pasirinkimas pagal elemento pavadinimą</a></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#teigiami-skaitiniai-indeksai"><i class="fa fa-check"></i>Teigiami skaitiniai indeksai</a></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#neigiami-skaitiniai-indeksai"><i class="fa fa-check"></i>Neigiami skaitiniai indeksai</a></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#pasirinkimas-pagal-salygas-logini-indeksa"><i class="fa fa-check"></i>Pasirinkimas pagal sąlygas (loginį indeksą)</a></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#specializuotos-funkcijos-elementams-pasirinkti"><i class="fa fa-check"></i>Specializuotos funkcijos elementams pasirinkti</a></li></ul></li><li class="chapter"data-level="7.2.4"data-path="r-vektoriai.html"><a href="r-vektoriai.html#vektoriaus-elementu-reiksmiu-pakeitimas"><i class="fa fa-check"></i><b>7.2.4</b> Vektoriaus elementų reikšmių pakeitimas</a></li><li class="chapter"data-level="7.2.5"data-path="r-vektoriai.html"><a href="r-vektoriai.html#vektorizacija"><i class="fa fa-check"></i><b>7.2.5</b> Vektorizuotos operacijos</a></li></ul></li><li class="chapter"data-level="7.3"data-path="r-vektoriai.html"><a href="r-vektoriai.html#r-tekstiniai-kintamieji"><i class="fa fa-check"></i><b>7.3</b> Darbas su tekstiniais kintamaisiais</a></li><li class="chapter"data-level="7.4"data-path="r-vektoriai.html"><a href="r-vektoriai.html#r-kategoriniu-reiksmiu-sekos"><i class="fa fa-check"></i><b>7.4</b> Darbas su kategoriniais kintamaisiais</a><ul><li class="chapter"data-level="7.4.1"data-path="r-vektoriai.html"><a href="r-vektoriai.html#faktoriu-kurimas"><i class="fa fa-check"></i><b>7.4.1</b> Faktorių kūrimas</a></li><li class="chapter"data-level="7.4.2"data-path="r-vektoriai.html"><a href="r-vektoriai.html#faktoriu-analize"><i class="fa fa-check"></i><b>7.4.2</b> Faktorių pertvarkymas ir analizė</a></li></ul></li><li class="chapter"data-level="7.5"data-path="r-vektoriai.html"><a href="r-vektoriai.html#r-skaiciu-sekos"><i class="fa fa-check"></i><b>7.5</b> Darbas su skaitiniais kintamaisiais</a><ul><li class="chapter"data-level="7.5.1"data-path="r-vektoriai.html"><a href="r-vektoriai.html#skaiciu-seku-kurimas"><i class="fa fa-check"></i><b>7.5.1</b> Skaičių sekų kūrimas</a><ul><li><a href="r-vektoriai.html#operatorius">Operatorius <code>:</code></a></li><li><a href="r-vektoriai.html#funkcija-seq">Funkcija <strong><em>seq()</em></strong></a></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#atsitiktines-sekos-is-galimu-reiksmiu-aibes"><i class="fa fa-check"></i>Atsitiktinės sekos iš galimų reikšmių aibės</a></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#atsitiktiniu-skaiciu-sekos-statistiniai-desniai"><i class="fa fa-check"></i>Atsitiktinių skaičių sekos: statistiniai dėsniai</a></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#atkartojamas-atsitiktinumas"><i class="fa fa-check"></i>Atkartojamas atsitiktinumas</a></li></ul></li><li class="chapter"data-level="7.5.2"data-path="r-vektoriai.html"><a href="r-vektoriai.html#r-aritmetika"><i class="fa fa-check"></i><b>7.5.2</b> <strong><em>R</em></strong> kaip kalkuliatorius</a><ul><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#pavyzdziai-num"><i class="fa fa-check"></i>Pavyzdžiai</a></li></ul></li><li class="chapter"data-level="7.5.3"data-path="r-vektoriai.html"><a href="r-vektoriai.html#suvestines-skaiciams"><i class="fa fa-check"></i><b>7.5.3</b> Skaitinių kintamųjų suvestinės</a></li><li class="chapter"data-level="7.5.4"data-path="r-vektoriai.html"><a href="r-vektoriai.html#skaiciu-kategorizavimas"><i class="fa fa-check"></i><b>7.5.4</b> Skaitinio kintamojo reikšmių kategorizavimas</a></li><li class="chapter"data-level="7.5.5"data-path="r-vektoriai.html"><a href="r-vektoriai.html#skaiciu-formatavimas"><i class="fa fa-check"></i><b>7.5.5</b> Skaičių formatavimas</a></li></ul></li><li class="chapter"data-level="7.6"data-path="r-vektoriai.html"><a href="r-vektoriai.html#r-loginiu-reiksmiu-sekos"><i class="fa fa-check"></i><b>7.6</b> Darbas su loginiais kintamaisiais</a><ul><li class="chapter"data-level="7.6.1"data-path="r-vektoriai.html"><a href="r-vektoriai.html#palyginimas"><i class="fa fa-check"></i><b>7.6.1</b> Palyginimo operacijos</a></li><li class="chapter"data-level="7.6.2"data-path="r-vektoriai.html"><a href="r-vektoriai.html#logines-operacijos"><i class="fa fa-check"></i><b>7.6.2</b> Loginės operacijos</a></li><li class="chapter"data-level="7.6.3"data-path="r-vektoriai.html"><a href="r-vektoriai.html#lgl_to_num"><i class="fa fa-check"></i><b>7.6.3</b> Loginiai kintamieji kaip skaičiai</a></li></ul></li><li class="chapter"data-level=""data-path="r-vektoriai.html"><a href="r-vektoriai.html#r-vektoriai-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="8"data-path="teorija-grafikai.html"><a href="teorija-grafikai.html"><i class="fa fa-check"></i><b>8</b> Grafikai (teorija)</a><ul><li class="chapter"data-level="8.1"data-path="teorija-grafikai.html"><a href="teorija-grafikai.html#grafikai-vieno-kintamojo-apibendrinimui"><i class="fa fa-check"></i><b>8.1</b> Grafikai vieno kintamojo apibendrinimui</a><ul><li class="chapter"data-level="8.1.1"data-path="teorija-grafikai.html"><a href="teorija-grafikai.html#kategoriniams-duomenims"><i class="fa fa-check"></i><b>8.1.1</b> Kategoriniams duomenims</a></li><li class="chapter"data-level="8.1.2"data-path="teorija-grafikai.html"><a href="teorija-grafikai.html#tolydiesiems-duomenims"><i class="fa fa-check"></i><b>8.1.2</b> Tolydiesiems duomenims</a></li></ul></li><li class="chapter"data-level="8.2"data-path="teorija-grafikai.html"><a href="teorija-grafikai.html#diagramu-palyginimas"><i class="fa fa-check"></i><b>8.2</b> Diagramų palyginimas</a></li><li class="chapter"data-level=""data-path="teorija-grafikai.html"><a href="teorija-grafikai.html#teorija-grafikai-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="9"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html"><i class="fa fa-check"></i><b>9</b> <strong><em>R Commander</em></strong>: pagrindai ir aprašomoji statistika</a><ul><li class="chapter"data-level="9.1"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#r-commander-diegimas-ir-ijungimas"><i class="fa fa-check"></i><b>9.1</b> <strong><em>R Commander</em></strong> diegimas ir įjungimas</a></li><li class="chapter"data-level="9.2"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#r-commander-konfiguravimas"><i class="fa fa-check"></i><b>9.2</b> <strong><em>R Commander</em></strong> konfigūravimas</a></li><li class="chapter"data-level="9.3"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#duomenu-ikelimas-i-r"><i class="fa fa-check"></i><b>9.3</b> Duomenų įkėlimas į <strong><em>R</em></strong></a><ul><li class="chapter"data-level="9.3.1"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#r-objektu-pavadinimai-2"><i class="fa fa-check"></i><b>9.3.1</b> <strong><em>R</em></strong> objektų pavadinimai</a></li><li class="chapter"data-level="9.3.2"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#delim-duomenys"><i class="fa fa-check"></i><b>9.3.2</b> Skirtukais atskirtų reikšmių (SAR) formatas</a></li><li class="chapter"data-level="9.3.3"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#pastabos-apie-programos-r-formatu-duomenis"><i class="fa fa-check"></i><b>9.3.3</b> Pastabos apie programos <strong><em>R</em></strong> formatų duomenis</a></li></ul></li><li class="chapter"data-level="9.4"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#duomenu-perziura"><i class="fa fa-check"></i><b>9.4</b> Duomenų lentelės peržiūra</a><ul><li class="chapter"data-level="9.4.1"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#duomenys-kuriuos-naudosime"><i class="fa fa-check"></i><b>9.4.1</b> Duomenys, kuriuos naudosime</a></li><li class="chapter"data-level="9.4.2"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#pagrindines-perziuros-funkcijos"><i class="fa fa-check"></i><b>9.4.2</b> Pagrindinės peržiūros funkcijos</a></li><li class="chapter"data-level="9.4.3"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#kaip-atpazinti-stulpeliuose-esanciu-duomenu-klases"><i class="fa fa-check"></i><b>9.4.3</b> Kaip atpažinti stulpeliuose esančių duomenų klases?</a></li><li class="chapter"data-level="9.4.4"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#teorinis-duomenu-tipas-ir-jam-tinkama-r-klase"><i class="fa fa-check"></i><b>9.4.4</b> Teorinis duomenų tipas ir jam tinkama <strong><em>R</em></strong> klasė</a></li></ul></li><li class="chapter"data-level="9.5"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#kintamuju-klases-keitimas"><i class="fa fa-check"></i><b>9.5</b> Kintamųjų klasės keitimas</a></li><li class="chapter"data-level="9.6"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#reiksmiu-perskaiciavimas-ar-perkodavimas"><i class="fa fa-check"></i><b>9.6</b> Reikšmių perskaičiavimas ar perkodavimas</a></li><li class="chapter"data-level="9.7"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#rcmdr-grafikai"><i class="fa fa-check"></i><b>9.7</b> Grafikai</a><ul><li class="chapter"data-level="9.7.1"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#grafiku-issaugojimas-redaguojamu-formatu"><i class="fa fa-check"></i><b>9.7.1</b> Grafikų išsaugojimas redaguojamu formatu</a></li></ul></li><li class="chapter"data-level="9.8"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#programos-kodo-elementai"><i class="fa fa-check"></i><b>9.8</b> Programos kodo elementai</a><ul><li class="chapter"data-level="9.8.1"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#duomenu-lenteliu-sudarymas-is-vektoriu"><i class="fa fa-check"></i><b>9.8.1</b> Duomenų lentelių sudarymas iš vektorių</a></li><li class="chapter"data-level="9.8.2"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#duomenu-lenteles-stulpeliu-vertimas-vektoriais"><i class="fa fa-check"></i><b>9.8.2</b> Duomenų lentelės stulpelių vertimas vektoriais</a></li><li class="chapter"data-level="9.8.3"data-path="aprasomoji-nadojant-Rcmdr.html"><a href="aprasomoji-nadojant-Rcmdr.html#jungimo-operatorius"><i class="fa fa-check"></i><b>9.8.3</b> Jungimo operatorius <code>%&gt;%</code></a></li></ul></li></ul></li><li class="part"><span><b>Analizė</b></span></li><li class="chapter"data-level="10"data-path="skirstiniai.html"><a href="skirstiniai.html"><i class="fa fa-check"></i><b>10</b> Atsitiktiniai dydžiai ir skirstiniai</a><ul><li class="chapter"data-level="10.1"data-path="skirstiniai.html"><a href="skirstiniai.html#apie-pratybas"><i class="fa fa-check"></i><b>10.1</b> Apie pratybas</a></li><li class="chapter"data-level="10.2"data-path="skirstiniai.html"><a href="skirstiniai.html#tikimybiu-teorijos-elementai"><i class="fa fa-check"></i><b>10.2</b> Tikimybių teorijos elementai</a><ul><li class="chapter"data-level="10.2.1"data-path="skirstiniai.html"><a href="skirstiniai.html#tikimybiniai-eksperimentai-ir-ivykiai"><i class="fa fa-check"></i><b>10.2.1</b> Tikimybiniai eksperimentai ir įvykiai</a></li><li class="chapter"data-level="10.2.2"data-path="skirstiniai.html"><a href="skirstiniai.html#atsitiktinis-dydis"><i class="fa fa-check"></i><b>10.2.2</b> Atsitiktinis dydis</a></li><li class="chapter"data-level="10.2.3"data-path="skirstiniai.html"><a href="skirstiniai.html#tikimybe"><i class="fa fa-check"></i><b>10.2.3</b> Tikimybė</a></li><li class="chapter"data-level="10.2.4"data-path="skirstiniai.html"><a href="skirstiniai.html#skirstiniai-1"><i class="fa fa-check"></i><b>10.2.4</b> Skirstiniai</a></li></ul></li><li class="chapter"data-level="10.3"data-path="skirstiniai.html"><a href="skirstiniai.html#tikimybiniai-atsitiktiniu-dydziu-modeliai"><i class="fa fa-check"></i><b>10.3</b> Tikimybiniai atsitiktinių dydžių modeliai</a><ul><li class="chapter"data-level="10.3.1"data-path="skirstiniai.html"><a href="skirstiniai.html#binominis"><i class="fa fa-check"></i><b>10.3.1</b> Binominis skirstinys</a></li><li class="chapter"data-level="10.3.2"data-path="skirstiniai.html"><a href="skirstiniai.html#puasono"><i class="fa fa-check"></i><b>10.3.2</b> Puasono skirstinys</a></li><li class="chapter"data-level="10.3.3"data-path="skirstiniai.html"><a href="skirstiniai.html#binominio-skirstinio-aproksimacija-puasono-skirstiniu"><i class="fa fa-check"></i><b>10.3.3</b> Binominio skirstinio aproksimacija Puasono skirstiniu</a></li><li class="chapter"data-level="10.3.4"data-path="skirstiniai.html"><a href="skirstiniai.html#geometrinis"><i class="fa fa-check"></i><b>10.3.4</b> Geometrinis skirstinys</a></li><li class="chapter"data-level="10.3.5"data-path="skirstiniai.html"><a href="skirstiniai.html#neig-binominis"><i class="fa fa-check"></i><b>10.3.5</b> Neigiamas binominis skirstinys</a></li><li class="chapter"data-level="10.3.6"data-path="skirstiniai.html"><a href="skirstiniai.html#normalusis"><i class="fa fa-check"></i><b>10.3.6</b> Normalusis skirstinys</a></li><li class="chapter"data-level="10.3.7"data-path="skirstiniai.html"><a href="skirstiniai.html#log-normalusis"><i class="fa fa-check"></i><b>10.3.7</b> Log-normalusis skirstinys</a></li></ul></li><li class="chapter"data-level="10.4"data-path="skirstiniai.html"><a href="skirstiniai.html#skirstiniai-r"><i class="fa fa-check"></i><b>10.4</b> Skirstiniai programoje <em>R</em></a><ul><li class="chapter"data-level="10.4.1"data-path="skirstiniai.html"><a href="skirstiniai.html#tikimybės-rcmdr"><i class="fa fa-check"></i><b>10.4.1</b> <em>R Commander</em> tikimybių skaičiuoklės</a></li></ul></li><li class="chapter"data-level="10.5"data-path="skirstiniai.html"><a href="skirstiniai.html#tikimybes-geogebra"><i class="fa fa-check"></i><b>10.5</b> Programos <em>GeoGebra</em> tikimybių skaičiuoklė</a></li><li class="chapter"data-level="10.6"data-path="skirstiniai.html"><a href="skirstiniai.html#skirstiniai-ir-tikimybiniai-uzdaviniai"><i class="fa fa-check"></i><b>10.6</b> Skirstiniai ir tikimybiniai uždaviniai</a><ul><li class="chapter"data-level="10.6.1"data-path="skirstiniai.html"><a href="skirstiniai.html#zinome-tikimybe-kaip-rasti-kvantili"><i class="fa fa-check"></i><b>10.6.1</b> Žinome tikimybę, kaip rasti kvantilį?</a></li><li class="chapter"data-level="10.6.2"data-path="skirstiniai.html"><a href="skirstiniai.html#zinome-kvantili-kaip-rasti-tikimybe"><i class="fa fa-check"></i><b>10.6.2</b> Žinome kvantilį, kaip rasti tikimybę?</a></li><li class="chapter"data-level="10.6.3"data-path="skirstiniai.html"><a href="skirstiniai.html#zinome-reiksme-kaip-rasti-jos-igijimo-tikimybetikimybes-tanki"><i class="fa fa-check"></i><b>10.6.3</b> Žinome reikšmę, kaip rasti jos įgijimo tikimybę/tikimybės tankį?</a></li><li class="chapter"data-level="10.6.4"data-path="skirstiniai.html"><a href="skirstiniai.html#tikimybiniu-uzdaviniu-pavyzdziai"><i class="fa fa-check"></i><b>10.6.4</b> Tikimybinių uždavinių pavyzdžiai</a></li></ul></li></ul></li><li class="chapter"data-level="11"data-path="skirstinio-parinkimas.html"><a href="skirstinio-parinkimas.html"><i class="fa fa-check"></i><b>11</b> Skirstinio parinkimas duomenims</a><ul><li class="chapter"data-level="11.1"data-path="skirstinio-parinkimas.html"><a href="skirstinio-parinkimas.html#gof-statistikos"><i class="fa fa-check"></i><b>11.1</b> Skaitiniai būdai modelio ir duomenų suderinamumui vertinti</a></li><li class="chapter"data-level="11.2"data-path="skirstinio-parinkimas.html"><a href="skirstinio-parinkimas.html#paketas-fitdistrplus-teoriniam-modeliui-parinkti"><i class="fa fa-check"></i><b>11.2</b> Paketas <strong><em>fitdistrplus</em></strong> teoriniam modeliui parinkti</a></li><li class="chapter"data-level="11.3"data-path="skirstinio-parinkimas.html"><a href="skirstinio-parinkimas.html#keliu-modeliu-palyginimas-paketas-fitdistrplus"><i class="fa fa-check"></i><b>11.3</b> Kelių modelių palyginimas (paketas <strong><em>fitdistrplus</em></strong>)</a><ul><li class="chapter"data-level=""data-path="skirstinio-parinkimas.html"><a href="skirstinio-parinkimas.html#palyginimas-grafiskai"><i class="fa fa-check"></i>Palyginimas grafiškai</a></li><li class="chapter"data-level=""data-path="skirstinio-parinkimas.html"><a href="skirstinio-parinkimas.html#gofstat"><i class="fa fa-check"></i>Palyginimas naudojant skaitines statistikas</a></li></ul></li><li class="chapter"data-level="11.4"data-path="skirstinio-parinkimas.html"><a href="skirstinio-parinkimas.html#jei-dazniu-lentele-fitdistrplus"><i class="fa fa-check"></i><b>11.4</b> Jei duomenys pateikti kaip dažnių lentelė (<strong><em>fitdistrplus</em></strong>)</a></li></ul></li><li class="chapter"data-level="12"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html"><i class="fa fa-check"></i><b>12</b> Pasikliautinieji intervalai (PI) klasikiniais metodais</a><ul><li class="chapter"data-level="12.1"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#paketas-desctools"><i class="fa fa-check"></i><b>12.1</b> Paketas <strong><em>DescTools</em></strong></a></li><li class="chapter"data-level="12.2"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#pi-braizymas"><i class="fa fa-check"></i><b>12.2</b> Nubraižyti lentele pateiktus PI</a></li><li class="chapter"data-level="12.3"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#klasikiniai-metodai-pi-skaiciuoti"><i class="fa fa-check"></i><b>12.3</b> Klasikiniai metodai PI skaičiuoti</a></li><li class="chapter"data-level="12.4"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#vidurkio-pi"><i class="fa fa-check"></i><b>12.4</b> Vidurkio PI</a><ul><li class="chapter"data-level="12.4.1"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#z-formule"><i class="fa fa-check"></i><b>12.4.1</b> Vidurkio PI, kai GA dispersija žinoma</a></li><li class="chapter"data-level="12.4.2"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#t-formule"><i class="fa fa-check"></i><b>12.4.2</b> Vidurkio PI, kai GA dispersija nežinoma</a><ul><li><a href="pi-klasikiniai.html#rcmdr-vidurkio-pi-skaiciavimui"><strong><em>Rcmdr</em></strong> vidurkio PI skaičiavimui</a></li></ul></li><li class="chapter"data-level="12.4.3"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#n-from-z-formula"><i class="fa fa-check"></i><b>12.4.3</b> Imties dydžio skaičiavimas norimam vidurkio PI ilgiui</a></li></ul></li><li class="chapter"data-level="12.5"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#pi-proporcijai"><i class="fa fa-check"></i><b>12.5</b> Proporcijos PI</a><ul><li class="chapter"data-level="12.5.1"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#pavyzdys-1-triusiai"><i class="fa fa-check"></i><b>12.5.1</b> Pavyzdys 1: triušiai</a></li><li class="chapter"data-level="12.5.2"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#pavyzdys-2-rasine-ivairove"><i class="fa fa-check"></i><b>12.5.2</b> Pavyzdys 2: rasinė įvairovė</a></li><li class="chapter"data-level="12.5.3"data-path="pi-klasikiniai.html"><a href="pi-klasikiniai.html#pavyzdys-3-grupes-pagal-ugi"><i class="fa fa-check"></i><b>12.5.3</b> Pavyzdys 3: grupės pagal ūgį</a></li></ul></li></ul></li><li class="chapter"data-level="13"data-path="pi-saviranka.html"><a href="pi-saviranka.html"><i class="fa fa-check"></i><b>13</b> Pasikliautinieji intervalai savirankos metodais</a><ul><li class="chapter"data-level="13.1"data-path="pi-saviranka.html"><a href="pi-saviranka.html#paketas-desctools-1"><i class="fa fa-check"></i><b>13.1</b> Paketas <strong><em>DescTools</em></strong></a></li><li class="chapter"data-level="13.2"data-path="pi-saviranka.html"><a href="pi-saviranka.html#savirankos-metodai"><i class="fa fa-check"></i><b>13.2</b> Savirankos metodai</a></li><li class="chapter"data-level="13.3"data-path="pi-saviranka.html"><a href="pi-saviranka.html#teorine-medziaga"><i class="fa fa-check"></i><b>13.3</b> Teorinė medžiaga</a></li><li class="chapter"data-level="13.4"data-path="pi-saviranka.html"><a href="pi-saviranka.html#savirankos-metodai-ir-imties-dydis"><i class="fa fa-check"></i><b>13.4</b> Savirankos metodai ir imties dydis</a></li><li class="chapter"data-level="13.5"data-path="pi-saviranka.html"><a href="pi-saviranka.html#baziniai-principai"><i class="fa fa-check"></i><b>13.5</b> Baziniai principai</a><ul><li class="chapter"data-level="13.5.1"data-path="pi-saviranka.html"><a href="pi-saviranka.html#analize-i-etapas"><i class="fa fa-check"></i><b>13.5.1</b> Analizė: I etapas</a></li><li class="chapter"data-level="13.5.2"data-path="pi-saviranka.html"><a href="pi-saviranka.html#analize-ii-etapas"><i class="fa fa-check"></i><b>13.5.2</b> Analizė: II etapas</a></li><li class="chapter"data-level="13.5.3"data-path="pi-saviranka.html"><a href="pi-saviranka.html#analize-iii-etapas"><i class="fa fa-check"></i><b>13.5.3</b> Analizė: III etapas</a></li></ul></li><li class="chapter"data-level="13.6"data-path="pi-saviranka.html"><a href="pi-saviranka.html#paketas-boot"><i class="fa fa-check"></i><b>13.6</b> Paketas „<strong>boot</strong>“</a><ul><li class="chapter"data-level="13.6.1"data-path="pi-saviranka.html"><a href="pi-saviranka.html#pavyzdys-vidurkio-pi"><i class="fa fa-check"></i><b>13.6.1</b> Pavyzdys: vidurkio PI</a></li><li class="chapter"data-level="13.6.2"data-path="pi-saviranka.html"><a href="pi-saviranka.html#pavyzdys-medianos-pi"><i class="fa fa-check"></i><b>13.6.2</b> Pavyzdys: medianos PI</a></li><li class="chapter"data-level="13.6.3"data-path="pi-saviranka.html"><a href="pi-saviranka.html#pavyzdys-koreliacijos-koeficiento-pi"><i class="fa fa-check"></i><b>13.6.3</b> Pavyzdys: koreliacijos koeficiento PI</a></li></ul></li></ul></li><li class="chapter"data-level="14"data-path="ht-ivadas.html"><a href="ht-ivadas.html"><i class="fa fa-check"></i><b>14</b> Hipotezių tikrinimas: įvadas</a><ul><li class="chapter"data-level="14.1"data-path="ht-ivadas.html"><a href="ht-ivadas.html#svarbiausios-savokos"><i class="fa fa-check"></i><b>14.1</b> Svarbiausios sąvokos</a></li><li class="chapter"data-level="14.2"data-path="ht-ivadas.html"><a href="ht-ivadas.html#prielaidos-ir-reikalavimai"><i class="fa fa-check"></i><b>14.2</b> Prielaidos ir reikalavimai</a></li><li class="chapter"data-level="14.3"data-path="ht-ivadas.html"><a href="ht-ivadas.html#parametriniai-vs-neparametriniai"><i class="fa fa-check"></i><b>14.3</b> Parametriniai ir neparametriniai kriterijai</a></li><li class="chapter"data-level="14.4"data-path="ht-ivadas.html"><a href="ht-ivadas.html#rekomendacija-kaip-atlikti-statistiniu-hipoteziu-tikrinima"><i class="fa fa-check"></i><b>14.4</b> Rekomendacija, kaip atlikti statistinių hipotezių tikrinimą</a></li><li class="chapter"data-level="14.5"data-path="ht-ivadas.html"><a href="ht-ivadas.html#schemos-metodams-pasirinkti"><i class="fa fa-check"></i><b>14.5</b> Schemos metodams pasirinkti</a></li><li class="chapter"data-level="14.6"data-path="ht-ivadas.html"><a href="ht-ivadas.html#praktiniai-patarimai"><i class="fa fa-check"></i><b>14.6</b> Praktiniai patarimai</a><ul><li class="chapter"data-level="14.6.1"data-path="ht-ivadas.html"><a href="ht-ivadas.html#teisingas-duomenu-nuskaitymas"><i class="fa fa-check"></i><b>14.6.1</b> Teisingas duomenų nuskaitymas</a></li></ul></li></ul></li><li class="chapter"data-level="15"data-path="ht-suderinamumas-ir-proporcijos.html"><a href="ht-suderinamumas-ir-proporcijos.html"><i class="fa fa-check"></i><b>15</b> Suderinamumo ir proporcijų homogeniškumo tikrinimas</a><ul><li class="chapter"data-level="15.1"data-path="ht-suderinamumas-ir-proporcijos.html"><a href="ht-suderinamumas-ir-proporcijos.html#suderinamumo-uzdavinys"><i class="fa fa-check"></i><b>15.1</b> Suderinamumo uždavinys</a></li><li class="chapter"data-level="15.2"data-path="ht-suderinamumas-ir-proporcijos.html"><a href="ht-suderinamumas-ir-proporcijos.html#proporciju-homogeniskumo-tikrinimas"><i class="fa fa-check"></i><b>15.2</b> Proporcijų homogeniškumo tikrinimas</a></li></ul></li><li class="chapter"data-level="16"data-path="ht-normalumas.html"><a href="ht-normalumas.html"><i class="fa fa-check"></i><b>16</b> Normalumo tikrinimas</a><ul><li class="chapter"data-level="16.1"data-path="ht-normalumas.html"><a href="ht-normalumas.html#normalumo-tikrinimas"><i class="fa fa-check"></i><b>16.1</b> Pasirinkimų schema</a></li><li class="chapter"data-level="16.2"data-path="ht-normalumas.html"><a href="ht-normalumas.html#statistiniai-kriterijai-normalumui-tikrinti"><i class="fa fa-check"></i><b>16.2</b> Statistiniai kriterijai normalumui tikrinti</a><ul><li class="chapter"data-level="16.2.1"data-path="ht-normalumas.html"><a href="ht-normalumas.html#statistines-hipotezes-tikrinant-normaluma"><i class="fa fa-check"></i><b>16.2.1</b> Statistinės hipotezės tikrinant normalumą</a></li></ul></li><li class="chapter"data-level="16.3"data-path="ht-normalumas.html"><a href="ht-normalumas.html#gof-grafikai"><i class="fa fa-check"></i><b>16.3</b> Grafiniai būdai normalumui tikrinti</a><ul><li class="chapter"data-level="16.3.1"data-path="ht-normalumas.html"><a href="ht-normalumas.html#qq-diagrama"><i class="fa fa-check"></i><b>16.3.1</b> Kvantilių palyginimo (qq) diagrama</a></li><li class="chapter"data-level="16.3.2"data-path="ht-normalumas.html"><a href="ht-normalumas.html#tikimybiu-palyginimo-pp-diagrama"><i class="fa fa-check"></i><b>16.3.2</b> Tikimybių palyginimo (pp) diagrama</a></li><li class="chapter"data-level="16.3.3"data-path="ht-normalumas.html"><a href="ht-normalumas.html#kitu-tipu-grafikai"><i class="fa fa-check"></i><b>16.3.3</b> Kitų tipų grafikai</a></li></ul></li><li class="chapter"data-level="16.4"data-path="ht-normalumas.html"><a href="ht-normalumas.html#kaip-tai-atlikti-kompiuteriu"><i class="fa fa-check"></i><b>16.4</b> Kaip tai atlikti kompiuteriu?</a><ul><li class="chapter"data-level="16.4.1"data-path="ht-normalumas.html"><a href="ht-normalumas.html#programos-kodas"><i class="fa fa-check"></i><b>16.4.1</b> Programos kodas</a></li><li class="chapter"data-level="16.4.2"data-path="ht-normalumas.html"><a href="ht-normalumas.html#rcmdr-normalumui-tikrinti"><i class="fa fa-check"></i><b>16.4.2</b> <strong><em>Rcmdr</em></strong> normalumui tikrinti</a></li><li class="chapter"data-level="16.4.3"data-path="ht-normalumas.html"><a href="ht-normalumas.html#rcmdrplugin.biostat-normalumui-tikrinti"><i class="fa fa-check"></i><b>16.4.3</b> <strong><em>RcmdrPlugin.biostat</em></strong> normalumui tikrinti</a></li></ul></li></ul></li><li class="chapter"data-level="17"data-path="ht-sklaida.html"><a href="ht-sklaida.html"><i class="fa fa-check"></i><b>17</b> Sklaidos lyginimas</a><ul><li class="chapter"data-level="17.1"data-path="ht-sklaida.html"><a href="ht-sklaida.html#dispersiju-lyginimas"><i class="fa fa-check"></i><b>17.1</b> Dispersijų lyginimas</a></li><li class="chapter"data-level="17.2"data-path="ht-sklaida.html"><a href="ht-sklaida.html#dispersiju-lyginimas"><i class="fa fa-check"></i><b>17.2</b> Kriterijai dispersijoms lyginti</a></li><li class="chapter"data-level="17.3"data-path="ht-sklaida.html"><a href="ht-sklaida.html#pasirinkimu-schema"><i class="fa fa-check"></i><b>17.3</b> Pasirinkimų schema</a></li><li class="chapter"data-level="17.4"data-path="ht-sklaida.html"><a href="ht-sklaida.html#statistines-hipotezes"><i class="fa fa-check"></i><b>17.4</b> Statistinės hipotezės</a></li><li class="chapter"data-level="17.5"data-path="ht-sklaida.html"><a href="ht-sklaida.html#kaip-atlikti"><i class="fa fa-check"></i><b>17.5</b> Kaip atlikti?</a></li></ul></li><li class="chapter"data-level="18"data-path="ht-padetis.html"><a href="ht-padetis.html"><i class="fa fa-check"></i><b>18</b> Skirstinių padėties lyginimas (1-2 imtims)</a><ul><li class="chapter"data-level="18.1"data-path="ht-padetis.html"><a href="ht-padetis.html#centro-padeties-lyginimas-1"><i class="fa fa-check"></i><b>18.1</b> Kriterijai (centro) padėčiai lyginti</a></li><li class="chapter"data-level="18.2"data-path="ht-padetis.html"><a href="ht-padetis.html#statistines-hipotezes-parametriniai-kriterijai"><i class="fa fa-check"></i><b>18.2</b> Statistinės hipotezės: parametriniai kriterijai</a></li><li class="chapter"data-level="18.3"data-path="ht-padetis.html"><a href="ht-padetis.html#statistines-hipotezes-neparametriniai-kriterijai"><i class="fa fa-check"></i><b>18.3</b> Statistinės hipotezės: neparametriniai kriterijai</a></li><li class="chapter"data-level="18.4"data-path="ht-padetis.html"><a href="ht-padetis.html#pasirinkimu-schema-1"><i class="fa fa-check"></i><b>18.4</b> Pasirinkimų schema</a></li><li class="chapter"data-level="18.5"data-path="ht-padetis.html"><a href="ht-padetis.html#kaip-atlikti-1"><i class="fa fa-check"></i><b>18.5</b> Kaip atlikti?</a></li><li class="chapter"data-level="18.6"data-path="ht-padetis.html"><a href="ht-padetis.html#kaip-aprasyti-rezultatus"><i class="fa fa-check"></i><b>18.6</b> Kaip aprašyti rezultatus?</a></li></ul></li><li class="chapter"data-level="19"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html"><i class="fa fa-check"></i><b>19</b> ANOVA ir jos analogai</a><ul><li class="chapter"data-level="19.1"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#kas-yra-anova"><i class="fa fa-check"></i><b>19.1</b> Kas yra ANOVA?</a><ul><li class="chapter"data-level="19.1.1"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#ANOVA-ir-analogai"><i class="fa fa-check"></i><b>19.1.1</b> Kurį vienfaktorės ANOVA variantą ar analogą pasirinkti?</a></li></ul></li><li class="chapter"data-level="19.2"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#issamios-ANOVA-aspektai"><i class="fa fa-check"></i><b>19.2</b> Išsamios ANOVA analizės aspektai</a><ul><li class="chapter"data-level="19.2.1"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#eiga"><i class="fa fa-check"></i><b>19.2.1</b> Eiga</a></li><li class="chapter"data-level="19.2.2"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#klausimas"><i class="fa fa-check"></i><b>19.2.2</b> Klausimas</a></li><li class="chapter"data-level="19.2.3"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#duomenys"><i class="fa fa-check"></i><b>19.2.3</b> Duomenys</a></li><li class="chapter"data-level="19.2.4"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#duomenu-suvestines"><i class="fa fa-check"></i><b>19.2.4</b> Duomenų suvestinės</a></li><li class="chapter"data-level="19.2.5"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#duomenu-formatas-ilgasis"><i class="fa fa-check"></i><b>19.2.5</b> Duomenų formatas: ilgasis</a></li><li class="chapter"data-level="19.2.6"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#modelio-formule"><i class="fa fa-check"></i><b>19.2.6</b> Modelio formulė</a></li><li class="chapter"data-level="19.2.7"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#grafikai"><i class="fa fa-check"></i><b>19.2.7</b> Grafikai</a></li><li class="chapter"data-level="19.2.8"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#duomenu-pasiskirstymo-normalumo-tikrinimas-grupems"><i class="fa fa-check"></i><b>19.2.8</b> Duomenų pasiskirstymo normalumo tikrinimas grupėms</a></li><li class="chapter"data-level="19.2.9"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#dispersiju-homogeniskumo-tikrinimas"><i class="fa fa-check"></i><b>19.2.9</b> Dispersijų homogeniškumo tikrinimas</a></li><li class="chapter"data-level="19.2.10"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#tinkamo-anova-varianto-ar-analogo-pasirinkimas"><i class="fa fa-check"></i><b>19.2.10</b> Tinkamo ANOVA varianto ar analogo pasirinkimas</a></li><li class="chapter"data-level="19.2.11"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#cld"><i class="fa fa-check"></i><b>19.2.11</b> Kompaktiškas raidinis žymėjimas (<em>cld</em>)</a></li><li class="chapter"data-level="19.2.12"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#ANOVA-rezultatu-aprasymas"><i class="fa fa-check"></i><b>19.2.12</b> Rezultatų aprašymas</a><ul><li class="chapter"data-level=""data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#anova-rezultatai"><i class="fa fa-check"></i>ANOVA rezultatai</a></li><li class="chapter"data-level=""data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#welch-anova-rezultatai"><i class="fa fa-check"></i>Welch ANOVA rezultatai</a></li><li class="chapter"data-level=""data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#kruskal-wallis-analizes-rezultatai"><i class="fa fa-check"></i>Kruskal-Wallis analizės rezultatai</a></li><li><a href="ht-anova-ir-analogai.html#post-hoc-analizes-rezultatai"><em>Post-hoc</em> analizės rezultatai</a></li></ul></li></ul></li><li class="chapter"data-level="19.3"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#programos-kodai-analizei"><i class="fa fa-check"></i><b>19.3</b> Programos kodai analizei</a><ul><li class="chapter"data-level="19.3.1"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#anova"><i class="fa fa-check"></i><b>19.3.1</b> ANOVA</a></li><li class="chapter"data-level="19.3.2"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#Welch-F-pvz"><i class="fa fa-check"></i><b>19.3.2</b> Welch ANOVA (Welch F kriterijus)</a></li><li class="chapter"data-level="19.3.3"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#kruskal-wallis-kriterijus"><i class="fa fa-check"></i><b>19.3.3</b> Kruskal-Wallis kriterijus</a></li><li class="chapter"data-level="19.3.4"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#post-hoc-tukey-hsd-kriterijus"><i class="fa fa-check"></i><b>19.3.4</b> <em>Post-hoc:</em> Tukey HSD kriterijus</a></li><li class="chapter"data-level="19.3.5"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#post-hoc-games-howell-kriterijus"><i class="fa fa-check"></i><b>19.3.5</b> <em>Post-hoc:</em> Games-Howell kriterijus</a></li><li class="chapter"data-level="19.3.6"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#post-hoc-conover-iman-kriterijus"><i class="fa fa-check"></i><b>19.3.6</b> <em>Post-hoc:</em> Conover-Iman kriterijus</a></li></ul></li><li class="chapter"data-level="19.4"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#pavyzdys-1-kai-duomenys-normalieji-ir-dispersijos-lygios"><i class="fa fa-check"></i><b>19.4</b> Pavyzdys 1: kai duomenys normalieji ir dispersijos lygios</a><ul><li class="chapter"data-level="19.4.1"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#ANOVA-pvz"><i class="fa fa-check"></i><b>19.4.1</b> ANOVA (pagrindinė analizė)</a></li><li class="chapter"data-level="19.4.2"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#tukey-hsd-1"><i class="fa fa-check"></i><b>19.4.2</b> Tukey kriterijus (<em>post-hoc</em> analizė)</a></li></ul></li><li class="chapter"data-level="19.5"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#pavyzdys-2-kai-duomenys-normalieji-bet-dispersijos-nera-lygios"><i class="fa fa-check"></i><b>19.5</b> Pavyzdys 2: kai duomenys normalieji, bet dispersijos nėra lygios</a><ul><li class="chapter"data-level="19.5.1"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#welch-anova-pagrindine-analize"><i class="fa fa-check"></i><b>19.5.1</b> Welch ANOVA (pagrindinė analizė)</a></li><li class="chapter"data-level="19.5.2"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#games-howell-kriterijus-post-hoc-analize"><i class="fa fa-check"></i><b>19.5.2</b> Games-Howell kriterijus (<em>post-hoc</em> analizė)</a></li></ul></li><li class="chapter"data-level="19.6"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#pavyzdys-3-neparametrinis-kriterijus-2-ir-daugiau-grupems-lyginti"><i class="fa fa-check"></i><b>19.6</b> Pavyzdys 3: neparametrinis kriterijus 2 ir daugiau grupėms lyginti</a><ul><li class="chapter"data-level="19.6.1"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#kw-pvz"><i class="fa fa-check"></i><b>19.6.1</b> Kruskal-Wallis kriterijus (pagrindinė analizė)</a></li><li class="chapter"data-level="19.6.2"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#conover-iman-kriterijus-post-hoc-analize"><i class="fa fa-check"></i><b>19.6.2</b> Conover-Iman kriterijus (<em>post-hoc</em> analizė)</a></li></ul></li><li class="chapter"data-level="19.7"data-path="ht-anova-ir-analogai.html"><a href="ht-anova-ir-analogai.html#ANOVA-tipo-analize"><i class="fa fa-check"></i><b>19.7</b> Video pavyzdys</a></li></ul></li><li class="chapter"data-level="20"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html"><i class="fa fa-check"></i><b>20</b> Ryšys tarp kintamųjų</a><ul><li class="chapter"data-level="20.1"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#bendrieji-principai"><i class="fa fa-check"></i><b>20.1</b> Bendrieji principai</a><ul><li class="chapter"data-level="20.1.1"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#sasaja-neparodo-priezastingumo"><i class="fa fa-check"></i><b>20.1.1</b> Sąsaja neparodo priežastingumo</a></li><li class="chapter"data-level="20.1.2"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#statistinis-sasajos-reiksmingumas"><i class="fa fa-check"></i><b>20.1.2</b> Statistinis sąsajos reikšmingumas</a></li><li class="chapter"data-level="20.1.3"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#sasajos-stiprumas"><i class="fa fa-check"></i><b>20.1.3</b> Sąsajos stiprumas</a></li></ul></li><li class="chapter"data-level="20.2"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#koreliacine-analize"><i class="fa fa-check"></i><b>20.2</b> Koreliacinė analizė</a><ul><li class="chapter"data-level="20.2.1"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#kuri-koreliacijos-varianta-pasirinkti"><i class="fa fa-check"></i><b>20.2.1</b> Kurį koreliacijos variantą pasirinkti?</a></li><li class="chapter"data-level="20.2.2"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#prielaidu-ir-kitu-reikalavimu-tikrinimas"><i class="fa fa-check"></i><b>20.2.2</b> Prielaidų ir kitų reikalavimų tikrinimas</a><ul><li class="chapter"data-level=""data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#tiesiskumo-prielaida"><i class="fa fa-check"></i>Tiesiškumo prielaida</a></li><li class="chapter"data-level="20.2.2.1"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#isskirtys"><i class="fa fa-check"></i><b>20.2.2.1</b> Išskirtys</a></li><li class="chapter"data-level=""data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#kor--normalumo-tikrinimas"><i class="fa fa-check"></i>Normaliojo pasiskirstymo prielaida</a></li></ul></li><li class="chapter"data-level="20.2.3"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#rezultatu-aprasymas-koreliacine-analize"><i class="fa fa-check"></i><b>20.2.3</b> Rezultatų aprašymas: koreliacinė analizė</a></li><li class="chapter"data-level="20.2.4"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#simuliacija-pirsono-koreliacija"><i class="fa fa-check"></i><b>20.2.4</b> Simuliacija: Pirsono koreliacijos koeficientas</a></li><li class="chapter"data-level="20.2.5"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#koreliacija-pvz"><i class="fa fa-check"></i><b>20.2.5</b> Pavyzdžiai</a><ul><li class="chapter"data-level=""data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#pavyzdys-1"><i class="fa fa-check"></i>Pavyzdys 1</a></li><li class="chapter"data-level=""data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#pavyzdys-2"><i class="fa fa-check"></i>Pavyzdys 2</a></li></ul></li><li class="chapter"data-level="20.2.6"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#rekomenduojami-informacijos-saltiniai"><i class="fa fa-check"></i><b>20.2.6</b> Rekomenduojami informacijos šaltiniai</a></li></ul></li><li class="chapter"data-level="20.3"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#sasaja-tarp-kategoriniu-kintamuju-reiksmiu"><i class="fa fa-check"></i><b>20.3</b> Sąsaja tarp kategorinių kintamųjų reikšmių</a><ul><li class="chapter"data-level="20.3.1"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#pozymiu-nepriklausomumo-tikrinimas"><i class="fa fa-check"></i><b>20.3.1</b> Požymių nepriklausomumo tikrinimas</a></li><li class="chapter"data-level="20.3.2"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#kategoriniu-kintamuju-rysio-stiprumas"><i class="fa fa-check"></i><b>20.3.2</b> Kategorinių kintamųjų ryšio stiprumas</a></li><li class="chapter"data-level="20.3.3"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#programos-kodai"><i class="fa fa-check"></i><b>20.3.3</b> Programos kodai</a></li><li class="chapter"data-level="20.3.4"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#rekomenduojami-informacijos-saltiniai-1"><i class="fa fa-check"></i><b>20.3.4</b> Rekomenduojami informacijos šaltiniai</a></li></ul></li><li class="chapter"data-level="20.4"data-path="rysys-tarp-kintamuju.html"><a href="rysys-tarp-kintamuju.html#rysio-tarp-kintamuju-analize-naudojant-r-commander"><i class="fa fa-check"></i><b>20.4</b> Ryšio tarp kintamųjų analizė naudojant <strong><em>R Commander</em></strong></a></li></ul></li><li class="chapter"data-level="21"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html"><i class="fa fa-check"></i><b>21</b> Tiesinė regresija</a><ul><li class="chapter"data-level="21.1"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#regresija"><i class="fa fa-check"></i><b>21.1</b> Regresinė analizė</a><ul><li class="chapter"data-level="21.1.1"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#regresines-analizes-eiga"><i class="fa fa-check"></i><b>21.1.1</b> Regresinės analizės eiga</a></li><li class="chapter"data-level="21.1.2"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#tinkamos-ties-regr-redikliai"><i class="fa fa-check"></i><b>21.1.2</b> Tinkamo tiesinės regresijos modelio rodikliai</a></li><li class="chapter"data-level="21.1.3"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#regresijos-modelio-grafikas-ggplot2-sistema"><i class="fa fa-check"></i><b>21.1.3</b> Regresijos modelio grafikas <em>ggplot2</em> sistema</a></li><li class="chapter"data-level="21.1.4"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#rezultatu-aprasymas-regresija"><i class="fa fa-check"></i><b>21.1.4</b> Rezultatų aprašymas: tiesinė regresinė analizė</a></li></ul></li><li class="chapter"data-level="21.2"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#saltiniai-regresija"><i class="fa fa-check"></i><b>21.2</b> Informacijos šaltiniai</a></li><li class="chapter"data-level="21.3"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#regresine-analize-naudojant-r-commander"><i class="fa fa-check"></i><b>21.3</b> Regresinė analizė naudojant <em>R Commander</em></a><ul><li class="chapter"data-level="21.3.1"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#ties-regr-paprastoji-rcmdr"><i class="fa fa-check"></i><b>21.3.1</b> Paprastoji tiesinė regresija</a><ul><li class="chapter"data-level=""data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#klaibracijos-uzdavinys"><i class="fa fa-check"></i>Kalibracijos uždavinio sprendimas</a></li></ul></li><li class="chapter"data-level="21.3.2"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#ties-regr-daugialype-rcmdr"><i class="fa fa-check"></i><b>21.3.2</b> Daugialypė tiesinė regresija</a></li><li class="chapter"data-level="21.3.3"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#modelio-tobulinimas"><i class="fa fa-check"></i><b>21.3.3</b> Modelio tobulinimas</a></li></ul></li><li class="chapter"data-level="21.4"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#regresijos-pvz-R"><i class="fa fa-check"></i><b>21.4</b> Išsamios tiesinės regresinės analizės pavyzdys</a><ul><li class="chapter"data-level="21.4.1"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#klausimas-problema"><i class="fa fa-check"></i><b>21.4.1</b> Klausimas / Problema</a></li><li class="chapter"data-level="21.4.2"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#duomenys-1"><i class="fa fa-check"></i><b>21.4.2</b> Duomenys</a></li><li class="chapter"data-level="21.4.3"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#nusibraizome-kintamuosius"><i class="fa fa-check"></i><b>21.4.3</b> Nusibraižome kintamuosius</a></li><li class="chapter"data-level="21.4.4"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#ivertiname-koreliacija-tarp-kintamuju"><i class="fa fa-check"></i><b>21.4.4</b> Įvertiname koreliaciją tarp kintamųjų</a></li><li class="chapter"data-level="21.4.5"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#regresijos-lygties-sudarymas"><i class="fa fa-check"></i><b>21.4.5</b> Regresijos lygties sudarymas</a></li><li class="chapter"data-level="21.4.6"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#modelio-suvestine"><i class="fa fa-check"></i><b>21.4.6</b> Modelio suvestinė</a></li><li class="chapter"data-level="21.4.7"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#standartizuotieji-koeficientai"><i class="fa fa-check"></i><b>21.4.7</b> Standartizuotieji koeficientai</a></li><li class="chapter"data-level="21.4.8"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#liekamuju-paklaidu-analize"><i class="fa fa-check"></i><b>21.4.8</b> Liekamųjų paklaidų analizė</a><ul><li class="chapter"data-level=""data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#isskirciu-paieska"><i class="fa fa-check"></i>1. Išskirčių paieška</a></li><li class="chapter"data-level=""data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#paklaidu-normalumo-prielaidos-tikrinimas"><i class="fa fa-check"></i>2. Paklaidų normalumo prielaidos tikrinimas</a></li><li class="chapter"data-level=""data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#prielaidos-kad-paklaidu-vidurkis-lygus-nuliui-tikrinimas"><i class="fa fa-check"></i>3. Prielaidos, kad paklaidų vidurkis lygus nuliui, tikrinimas</a></li><li class="chapter"data-level=""data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#homoskedastiskumo-prielaidos-tikrinimas"><i class="fa fa-check"></i>4. Homoskedastiškumo prielaidos tikrinimas</a></li></ul></li><li class="chapter"data-level="21.4.9"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#tikrinimas-del-multikolinearumo"><i class="fa fa-check"></i><b>21.4.9</b> Tikrinimas dėl multikolinearumo</a></li><li class="chapter"data-level="21.4.10"data-path="tiesine-regresija.html"><a href="tiesine-regresija.html#prognozavimas"><i class="fa fa-check"></i><b>21.4.10</b> Prognozavimas</a></li></ul></li></ul></li><li class="appendix"><span><b>Priedai</b></span></li><li class="chapter"data-level="A"data-path="zodynai.html"><a href="zodynai.html"><i class="fa fa-check"></i><b>A</b> Žodynėliai</a><ul><li class="chapter"data-level="A.1"data-path="zodynai.html"><a href="zodynai.html#terminai-komp"><i class="fa fa-check"></i><b>A.1</b> Kompiuterijos terminai</a></li><li class="chapter"data-level="A.2"data-path="zodynai.html"><a href="zodynai.html#terminai-komp-mat"><i class="fa fa-check"></i><b>A.2</b> Programavimo ir matematikos terminai (anglų-lietuvių)</a></li><li class="chapter"data-level="A.3"data-path="zodynai.html"><a href="zodynai.html#terminai-simbpliai"><i class="fa fa-check"></i><b>A.3</b> Simbolių pavadinimai (anglų-lietuvių)</a></li><li class="chapter"data-level="A.4"data-path="zodynai.html"><a href="zodynai.html#terminai-stat"><i class="fa fa-check"></i><b>A.4</b> Statistikos terminai (aiškinamasis žodynas)</a></li><li class="chapter"data-level="A.5"data-path="zodynai.html"><a href="zodynai.html#terminai-stat-en-lt"><i class="fa fa-check"></i><b>A.5</b> Statistikos terminai (anglų-lietuvių)</a></li><li class="chapter"data-level=""data-path="zodynai.html"><a href="zodynai.html#zodynai-diskusija"><i class="fa fa-check"></i>Klausimai ir komentarai</a></li></ul></li><li class="chapter"data-level="B"data-path="priedas-r-sesijos-info.html"><a href="priedas-r-sesijos-info.html"><i class="fa fa-check"></i><b>B</b> <strong><em>R</em></strong> sesijos informacija</a></li><li class="chapter"data-level=""data-path="saltiniai.html"><a href="saltiniai.html"><i class="fa fa-check"></i>Informacijos šaltiniai</a></li></ul></nav></div><div class="book-body"><div class="body-inner"><div class="book-header"role="navigation"><h1><i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Biostatistika</a></h1></div><div class="page-wrapper"tabindex="-1"role="main"><div class="page-inner"><section class="normal"id="section-"><div id="pi-klasikiniai"class="section level1"><h1><span class="header-section-number">12. </span>Pasikliautinieji intervalai (PI) klasikiniais metodais</h1><p><br></p><div class="avoid"><p><br><br><font color="red"size="5">Šio skyriaus medžiaga vis dar rengiama arba neatnaujinta šių metų kursui, todėl kol kas jos <b>nenagrinėkite</b>.</font></p><p><br><br></p></div><p><br></p><p><strong>Statistinės išvados</strong> yra pagal imties (kuri yra mažesnė už generalinę aibę) duomenis padarytos išvados apie visą generalinę aibę (GA). Tam, kad išvados būtų teisingos, – pirmiausia, imtis privalo būti <strong>reprezentatyvi</strong>: sudaryta tinkamu būdu taip, kad atspindėtų esmines generalinės aibės savybes. Tada pagal duomenis ir iškeltą klausimą reikia pasirinkti tinkamą analizės metodą. Atkreipkite dėmesį, kad daugelis statistikos metodų sukurti darant prielaidą, kad GA yra be galo didelė. Tad mūsų GA turi būti pakankamai didelė, kad ši prielaida galiotų.</p><p>Statistinės išvados daromos:</p><ol style="list-style-type:lower-alpha"><li>tikrinant statistines hipotezes (taikant statistinius kriterijus);</li><li>sudarant įverčius (taškinius įverčius ir pasikliauties intervalus).</li></ol><p>Pasikliauties intervalai dar vadinami pasikliautinaisiais intervalais. Šio užsiėmimo metu nagrinėsime pasikliauties intervalų (<strong>PI</strong>) sudarymo metodus.</p><br><div class="info"><p>Darbui reikalingi <em>R</em> paketai: <strong>data.table</strong>, <strong>DescTools</strong>, <strong>pander</strong>, <strong>ggplot2</strong>, <strong>tidyverse</strong>.</p></div><div class="ok"><p style="font-size:20px"><font color="#21810B"><strong>Korektiško</strong> vidurkio pasikliauties intervalo <strong>skaičiavimo žingsniai</strong>:</font></p><ol style="list-style-type:decimal"><li><strong>Nusibraižome</strong> duomenis, įsitikiname, kad vidurkis yra prasmingas;</li><li><strong>Patikriname</strong>, ar nepažeidžiamos <strong>prielaidos</strong> (pvz., ar duomenys skirstosi <strong><em>normaliai</em></strong>, ar jų pakankamai daug ir kt.), kuriomis grindžiamas statistinis modelis (intervalo skaičiavimo būdas);</li><li><strong>Skaičiuojame</strong> pasikliauties intervalą.</li></ol></div><p><br>Šie žingsniai pritaikomi ir kitų, ne tik vidurkio, pasikliauties intervalų skaičiavimui. Svarbu nusibraižyti duomenis, patikrinti prielaidas ir tik po to atlikti skaičiavimus.</p><div id="paketas-desctools"class="section level2"><h2><span class="header-section-number">12.1</span> Paketas <strong><em>DescTools</em></strong></h2><p>Šis skyrelis skirtas tam, kad sužinotumėte, kad daugelio parametrų (vidurkio, proporcijos ir t.t.) pasikliautiniesiems intervalams (klasikiniais ir savirankos būdais) skaičiuoti skirtas funkcijas galite rasti pakete <strong>DescTools</strong>. Funkcijų pavyzdžiai:</p><pre class="sourceCode r"><code class="sourceCode r">DescTools<span class="op">::</span><span class="kw">MeanCI</span>(x)
DescTools<span class="op">::</span><span class="kw">MeanDiffCI</span>(x, y)
DescTools<span class="op">::</span><span class="kw">MedianCI</span>(x)
DescTools<span class="op">::</span><span class="kw">PoissonCI</span>(x)
DescTools<span class="op">::</span><span class="kw">VarCI</span>(x)
DescTools<span class="op">::</span><span class="kw">Gmean</span>(x, <span class="dt">conf.level =</span> <span class="fl">0.95</span>)
DescTools<span class="op">::</span><span class="kw">Hmean</span>(x, <span class="dt">conf.level =</span> <span class="fl">0.95</span>)
DescTools<span class="op">::</span><span class="kw">BinomCI</span>(x, n)
DescTools<span class="op">::</span><span class="kw">BinomDiffCI</span>(x1, x2, n1, n2)
DescTools<span class="op">::</span><span class="kw">MultinomCI</span>(x)</code></pre><p>Apžvelkime detaliau.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">20190401</span>)
x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">50</span>, <span class="dt">mean =</span> <span class="dv">180</span>, <span class="dt">sd =</span> <span class="dv">20</span>)
y &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">50</span>, <span class="dt">mean =</span> <span class="dv">165</span>, <span class="dt">sd =</span> <span class="dv">30</span>)</code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">20190401</span>)
gr_names &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Didelis&quot;</span>, <span class="st">&quot;Mažas&quot;)</span>
<span class="st">gr_1 &lt;- sample(gr_names, size = 50, replace = TRUE, prob = c(0.2, 0.8))</span>
<span class="st">gr_2 &lt;- sample(gr_names, size = 50, replace = TRUE, prob = c(0.3, 0.7))</span>

<span class="st">gr_names_2 &lt;- c(&quot;</span>Žalios<span class="st">&quot;, &quot;</span>Rudos<span class="st">&quot;, &quot;</span>Mėlynos<span class="st">&quot;, &quot;</span>Pilkos<span class="st">&quot;)</span>
<span class="st">gr_spalvos &lt;- sample(gr_names_2, size = 50, replace = TRUE)</span>
<span class="st">table(gr_spalvos)</span>
<span class="st">## gr_spalvos</span>
<span class="st">## Mėlynos  Pilkos   Rudos  Žalios </span>
<span class="st">##       8      11      10      21</span></code></pre><p>Funkcijų, skirtų kiekybiniams duomenims, pavyzdžiai:</p><pre class="sourceCode r"><code class="sourceCode r">DescTools<span class="op">::</span><span class="kw">MeanCI</span>(x)        <span class="co"># Vidurkio PI</span>
DescTools<span class="op">::</span><span class="kw">MeanDiffCI</span>(x, y) <span class="co"># Skirtumo tarp dviejų vidurkių PI</span>
DescTools<span class="op">::</span><span class="kw">MedianCI</span>(x)      <span class="co"># Medianos PI</span>
DescTools<span class="op">::</span><span class="kw">VarCI</span>(x)         <span class="co"># Dispersijos PI</span>
DescTools<span class="op">::</span><span class="kw">Gmean</span>(x, <span class="dt">conf.level =</span> <span class="fl">0.95</span>) <span class="co"># Geometrinio vidurkio PI</span>
DescTools<span class="op">::</span><span class="kw">Hmean</span>(x, <span class="dt">conf.level =</span> <span class="fl">0.95</span>) <span class="co"># Harmoninio vidurkio PI</span></code></pre><p>Čia <code>x</code> ir <code>y</code> – skaitinių reikšmių vektoriai.</p><p>Funkcijų, skirtų nominaliesiems duomenims, pavyzdžiai:</p><pre class="sourceCode r"><code class="sourceCode r">DescTools<span class="op">::</span><span class="kw">BinomCI</span>(x, n)                <span class="co"># Dvireikšmės proporcijos PI</span>
DescTools<span class="op">::</span><span class="kw">BinomDiffCI</span>(x1, x2, n1, n2)  <span class="co"># Skirtumo tarp dvireikšmių proporcijų PI</span>
DescTools<span class="op">::</span><span class="kw">BinomRatioCI</span>(x1, x2, n1, n2) <span class="co"># Santykio tarp dvireikšmių proporcijų PI</span></code></pre><p>Čia <code>x</code> (<code>x1</code>, <code>x2</code>) – mus dominančių įvykių arba dominančios kategorijos narių skaičius (pirmoje ir antroje grupėse); <code>n</code> (<code>n1</code>, <code>n2</code>) – įvykių (pirmoje ir antroje grupėse) skaičius iš viso arba (pirmosios ir antrosios) imties dydis. Tiek <code>x</code> tiek <code>n</code> dažniausiai yra vienas skaičius. Šie skaičiai įprastai gaunami susidarius dažnių lentelę.</p><pre class="sourceCode r"><code class="sourceCode r">DescTools<span class="op">::</span><span class="kw">MultinomCI</span>(x, <span class="dt">method =</span> <span class="st">&quot;goodman&quot;</span>) <span class="co"># Daugiareikšmės proporcijos PI</span></code></pre><p>Čia <code>x</code> – vektorius su kiekvienos kategorijos dydžiu. Pvz.: <code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">30</span>, <span class="dv">22</span>, <span class="dv">39</span>)</code> arba <code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;juodas&quot;</span> =<span class="st"> </span><span class="dv">30</span>, <span class="st">&quot;rudas&quot;</span> =<span class="st"> </span><span class="dv">22</span>, <span class="st">&quot;žalias&quot;</span> =<span class="st"> </span><span class="dv">39</span>)</code></p></div><div id="pi-braizymas"class="section level2"><h2><span class="header-section-number">12.2</span> Nubraižyti lentele pateiktus PI</h2><p>Dažna užduotis analizuojant duomenis – vizualizuoti pasikliauties intervalus. Sakykime, kad duota lentelė, kurioje taškinis vidurkio įvertis ir jo pasikliauties intervalas. Šiuos duomenis reikia įsikelti į „R“ ir nubraižyti.</p><table><caption><strong><span id="tab:pi-plot-01">Lentelė 12.1: </span></strong>Duomenys, kuriuos norime nubraižyti (1).</caption><thead><tr class="header"><th align="center">Vidurkis</th><th align="center">PI<sub>viršutinis</sub></th><th align="center">PI<sub>apatinis</sub></th></tr></thead><tbody><tr class="odd"><td align="center">162.0</td><td align="center">122.3</td><td align="center">182.8</td></tr></tbody></table><p>Lentelė pateikta tinklapyje, tad ją patogu nukopijuoti ir nuskaityti naudojant funkciją <code class="sourceCode r"><span class="kw">fread</span>()</code> iš paketo <strong><em>data.table</em></strong>. Užkraukime reikiamus paketus.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(data.table)
<span class="kw">library</span>(tidyverse)

<span class="kw">Sys.setlocale</span>(<span class="dt">locale =</span> <span class="st">&quot;Lithuanian&quot;</span>)</code></pre><p>Po to parašykime komandą <code class="sourceCode r"><span class="kw">fread</span>(<span class="st">&quot;&quot;</span>)</code>, jos skliaustuose padėkime kabutes. Tada pele pažymėkite visą lentelės <a href="pi-klasikiniai.html#tab:pi-plot-01">12.1</a> turinį, jį nukopijuokite ir įklijuokite į dokumentą tarp kabučių kaip rodoma pavyzdyje žemiau. Galime pridėti papildomų tarpų, kad sulygiuotume stulpelius, bet tai nėra būtina. Įvykdykime komandą ir patikrinkime, ar duomenys nuskaityti teisingai.</p><pre class="sourceCode r"><code class="sourceCode r">duomenys1 &lt;-<span class="st"> </span><span class="kw">fread</span>(
<span class="st">&quot;Vidurkis   PIviršutinis    PIapatinis</span>
<span class="st">162.0       122.3           182.8&quot;</span>)

<span class="kw">glimpse</span>(duomenys1)
<span>## Observations: 1</span>
<span>## Variables: 3</span>
<span>## $ Vidurkis     &lt;dbl&gt; 162</span>
<span>## $ PIviršutinis &lt;dbl&gt; 122.3</span>
<span>## $ PIapatinis   &lt;dbl&gt; 182.8</span>

duomenys1
<span>##    Vidurkis PIviršutinis PIapatinis</span>
<span>## 1:      162        122.3      182.8</span></code></pre><p>Kopijuojant lentelę iš tinklapio, stulpelių skirtukai yra tabuliacijos, kurias <code class="sourceCode r"><span class="kw">fread</span>()</code> atpažįsta automatiškai. Todėl lentelę nuskaito teisingai.</p><p>Dabar šiuos duomenis atvaizduokime naudodami <strong><em>ggplot2</em></strong>. Paklaidų ir intervalų braižymui naudinga funkcija <code class="sourceCode r"><span class="kw">geom_errorbar</span>()</code>, kuriai reikia nurodyti apatinę ir viršutinę ribas, kurios surašytos atskirame duomenų lentelės stulpelyje. Turime tik vieną grupę, todėl x’ui suteikiame bet kokį pavadinimą kabutėse.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(duomenys1, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="st">&quot;duomenys&quot;</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Vidurkis)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> PIviršutinis, <span class="dt">ymax =</span> PIapatinis))</code></pre><p><img src="08--01--pi-klasikiniai_files/figure-html/unnamed-chunk-16-1.png"width="288"style="display:block;margin:auto"></p><p>Šiek tiek padailinkime grafiką:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(duomenys1, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="st">&quot;duomenys&quot;</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Vidurkis), <span class="dt">size =</span> <span class="dv">4</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> PIviršutinis, <span class="dt">ymax =</span> PIapatinis), 
                  <span class="dt">width =</span> <span class="fl">.1</span>,
                   <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">lims</span>(<span class="dt">y =</span> <span class="kw">c</span>(<span class="dv">100</span>, <span class="dv">200</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;&quot;</span>)</code></pre><p><img src="08--01--pi-klasikiniai_files/figure-html/unnamed-chunk-17-1.png"width="288"style="display:block;margin:auto"></p><br><div class="ok"><p>Apibendrinančias statistikas, tokias kaip <strong>vidurkis ar mediana</strong>, duomenų vizualizavimo ekspertai rekomenduoja <strong>atvaizduoti taškais</strong> ar linijomis, bet ne stulpeliais.</p></div><div class="avoid"><p>Vidurkius ir medianas <strong>stulpeliais</strong> atvaizduoti <strong>nekorektiška</strong>, nes taip akcentuojama apatinė matavimo skalės dalis, kur duomenų galbūt nėra, ir ignoruojama viršutinė dalis, kur duomenys yra. Deja, centro padėties suvestinų atvaizdavimo būdas stulpeliais plačiai paplitęs.</p></div><p><br></p><table><caption><strong><span id="tab:pi-plot-02">Lentelė 12.2: </span></strong>Duomenys, kuriuos norime nubraižyti (2): vidurkis ir jo pasikliautinasis intervalas. Sveikosios ir dešimtosios skaičiaus dalies skirtukas – kablelis.</caption><thead><tr class="header"><th align="center">Vidurkis</th><th align="center">PI<sub>virš</sub></th><th align="center">PI<sub>apat</sub></th></tr></thead><tbody><tr class="odd"><td align="center">42,53</td><td align="center">41,02</td><td align="center">44,01</td></tr></tbody></table><p>Jei sveikosios ir dešimtosios dalies skirtukas yra kablelis (pavyzdys – lentelė <a href="pi-klasikiniai.html#tab:pi-plot-02">12.2</a>), programa automatiškai jo neatpažįsta, tad tai reikia nurodyti naudojant parametrą <code>dec</code>:</p><pre class="sourceCode r"><code class="sourceCode r">duomenys2 &lt;-<span class="st"> </span><span class="kw">fread</span>(<span class="dt">dec =</span> <span class="st">&quot;,&quot;</span>,
<span class="st">&quot;Vidurkis   PIvirš  PIapat</span>
<span class="st">42,53       41,02   44,01&quot;</span>)

<span class="kw">glimpse</span>(duomenys2)
<span>## Observations: 1</span>
<span>## Variables: 3</span>
<span>## $ Vidurkis &lt;dbl&gt; 42.53</span>
<span>## $ PIvirš   &lt;dbl&gt; 41.02</span>
<span>## $ PIapat   &lt;dbl&gt; 44.01</span>

duomenys2
<span>##    Vidurkis PIvirš PIapat</span>
<span>## 1:    42.53  41.02  44.01</span></code></pre><div class="exercise"><span id="exr:pi-01"class="exercise"><strong>Užduotis 12.1 </strong></span>Ką tik nuskaitytus duomenis „duomenys2“ atvaizduokite grafiškai.</div><p><br></p><table><caption><strong><span id="tab:pi-plot-03">Lentelė 12.3: </span></strong>Duomenys, kuriuos norime nubraižyti (3): vidurkis ir jo pasikliautinasis intervalas grupėms.</caption><thead><tr class="header"><th align="center">Grupė</th><th align="center">Vidurkis</th><th align="center">PI<sub>viršutinis</sub></th><th align="center">PI<sub>apatinis</sub></th></tr></thead><tbody><tr class="odd"><td align="center">Balti</td><td align="center">25</td><td align="center">22</td><td align="center">28</td></tr><tr class="even"><td align="center">Žali</td><td align="center">19</td><td align="center">17</td><td align="center">24</td></tr><tr class="odd"><td align="center">Raudoni</td><td align="center">45</td><td align="center">30</td><td align="center">52</td></tr><tr class="even"><td align="center">Geltoni</td><td align="center">33</td><td align="center">30</td><td align="center">36</td></tr></tbody></table><p>Jei norime, kad <code class="sourceCode r"><span class="kw">fread</span>()</code> tekstinius kintamuosius nuskaitytų kaip kategorinius, reikia naudoti parametrą <code>stringsAsFactors = TRUE</code>:</p><pre class="sourceCode r"><code class="sourceCode r">duomenys3 &lt;-<span class="st"> </span><span class="kw">fread</span>(<span class="dt">stringsAsFactors =</span> <span class="ot">TRUE</span>,
<span class="st">&quot;Grupė  Vidurkis    PIviršutinis    PIapatinis</span>
<span class="st">Balti   25  22  28</span>
<span class="st">Žali    19  17  24</span>
<span class="st">Raudoni 45  30  52</span>
<span class="st">Geltoni 33  30  36&quot;</span>)

<span class="kw">glimpse</span>(duomenys3)
<span>## Observations: 4</span>
<span>## Variables: 4</span>
<span>## $ Grupė        &lt;fct&gt; Balti, Žali, Raudoni, Geltoni</span>
<span>## $ Vidurkis     &lt;int&gt; 25, 19, 45, 33</span>
<span>## $ PIviršutinis &lt;int&gt; 22, 17, 30, 30</span>
<span>## $ PIapatinis   &lt;int&gt; 28, 24, 52, 36</span>

duomenys3
<span>##      Grupė Vidurkis PIviršutinis PIapatinis</span>
<span>## 1:   Balti       25           22         28</span>
<span>## 2:    Žali       19           17         24</span>
<span>## 3: Raudoni       45           30         52</span>
<span>## 4: Geltoni       33           30         36</span></code></pre><div class="exercise"><span id="exr:pi-02"class="exercise"><strong>Užduotis 12.2 </strong></span>Ką tik nuskaitytus duomenis nuskaitykite dar kartą naudodami <code class="sourceCode r">stringsAsFactors =<span class="st"> </span><span class="ot">FALSE</span></code>, rezultatą pavadinkite „duomenys3chr“. Palyginkite, kuo skiriasi „duomenys3“ ir „duomenys3chr“.</div><p><br></p><p>Bazinis kodas atvaizduoti duomenis. Pastebėkite, kad x ašyje išdėstytos stulpelio <code>Grupė</code> reikšmės, todėl šio stulpelio pavadinimas rašomas <strong>ne kabutėse</strong>.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(duomenys3, <span class="kw">aes</span>(<span class="dt">x =</span> Grupė)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Vidurkis)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> PIviršutinis, <span class="dt">ymax =</span> PIapatinis))</code></pre><p><img src="08--01--pi-klasikiniai_files/figure-html/unnamed-chunk-22-1.png"width="480"style="display:block;margin:auto"></p><p>Pagražintas grafikas:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(duomenys3, <span class="kw">aes</span>(<span class="dt">x =</span> Grupė, <span class="dt">color =</span> Grupė)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> PIviršutinis, <span class="dt">ymax =</span> PIapatinis),
                  <span class="dt">width =</span> <span class="fl">0.2</span>,
                  <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Vidurkis), <span class="dt">fill =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">shape =</span> <span class="dv">23</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Vidurkis ir jo 95% pasikliauties intervalas&quot;</span>)</code></pre><p><img src="08--01--pi-klasikiniai_files/figure-html/unnamed-chunk-23-1.png"width="480"style="display:block;margin:auto"></p><br><div class="exercise"><p><span id="exr:pi-plot-03"class="exercise"><strong>Užduotis 12.3</strong></span></p><ol style="list-style-type:decimal"><li>Lentelė <a href="pi-klasikiniai.html#tab:pi-plot-04">12.4</a>:<ol style="list-style-type:lower-alpha"><li>Nuskaitykite ir vizualizuokite duomenis.</li></ol></li><li>Lentelė <a href="pi-klasikiniai.html#tab:pi-plot-05">12.5</a>:<ol style="list-style-type:lower-alpha"><li>Nuskaitykite duomenis.</li><li>Proporcijas ir jų pasikliauties intervalus atvaizduokite stulpeliais (<em>geom_col()</em>). Stulpelio spalva turi būti parinkta pagal medžio rūšį (<em>Tree</em>), o stulpelio apvadas privalo būti juodas.</li><li>Įvardinkite, trūkumus, kuriuos pastebite šioje lentelėje.</li></ol></li></ol></div><br><table><caption><strong><span id="tab:pi-plot-04">Lentelė 12.4: </span></strong>Plauko ilgio pasiskirstymas pagal spalvas.</caption><thead><tr class="header"><th align="center">Spalva</th><th align="center">Vidurkis</th><th align="center">PI_viršutinis</th><th align="center">PI_apatinis</th></tr></thead><tbody><tr class="odd"><td align="center">Juoda</td><td align="center">5,9</td><td align="center">5,7</td><td align="center">6,4</td></tr><tr class="even"><td align="center">Ruda</td><td align="center">5,5</td><td align="center">5,2</td><td align="center">5,8</td></tr><tr class="odd"><td align="center">Gelsva</td><td align="center">5,3</td><td align="center">4,9</td><td align="center">5,6</td></tr></tbody></table><p><br></p><table><caption><strong><span id="tab:pi-plot-05">Lentelė 12.5: </span></strong>Rūšinis medžių pasiskirstymas miške.</caption><thead><tr class="header"><th></th><th align="center">Tree</th><th align="center">Count</th><th align="center">Total</th><th align="center">Proportion</th><th align="center">lower_ci</th><th align="center">upper_ci</th></tr></thead><tbody><tr class="odd"><td>1</td><td align="center">Douglas fir</td><td align="center">70</td><td align="center">156</td><td align="center">0.4487</td><td align="center">0.369115906</td><td align="center">0.53030534</td></tr><tr class="even"><td>2</td><td align="center">Ponderosa pine</td><td align="center">79</td><td align="center">156</td><td align="center">0.5064</td><td align="center">0.425290653</td><td align="center">0.58728175</td></tr><tr class="odd"><td>3</td><td align="center">Grand fir</td><td align="center">3</td><td align="center">156</td><td align="center">0.0192</td><td align="center">0.003983542</td><td align="center">0.05516994</td></tr><tr class="even"><td>4</td><td align="center">Western larch</td><td align="center">4</td><td align="center">156</td><td align="center">0.0256</td><td align="center">0.007029546</td><td align="center">0.06434776</td></tr></tbody></table><p>Jei lentelė <a href="pi-klasikiniai.html#tab:pi-plot-05">12.5</a> būtų pateikta tokiu pavidalu, kokį matote žemiau (be tabuliacijų), tada stulpelių, kuriuose yra keli žodžiai atskirti tarpu, reikšmes privalėtumėte rašyti kabutėse, pvz., <code class="sourceCode r"><span class="st">&quot;Douglas fir&quot;</span></code> arba <code class="sourceCode r">\<span class="st">&quot;Douglas fir</span><span class="ch">\&quot;</span></code>. Kitu atveju duomenys būtų nuskaityti neteisingai arba apskritai nebūtų nuskaityti.</p><pre><code>##    V1           Tree Count Total Proportion    lower_ci   upper_ci
## 1:  1    Douglas fir    70   156     0.4487 0.369115906 0.53030534
## 2:  2 Ponderosa pine    79   156     0.5064 0.425290653 0.58728175
## 3:  3      Grand fir     3   156     0.0192 0.003983542 0.05516994
## 4:  4  Western larch     4   156     0.0256 0.007029546 0.06434776</code></pre><p>Jei stulpelyje yra keli žodžiai, juos reikia įterpti į papildomas dvigubas kabutes. Jei neįterpiama – nuskaitoma neteisingai:</p><pre class="sourceCode r"><code class="sourceCode r">neteisingai &lt;-<span class="st"> </span><span class="kw">fread</span>(
<span class="st">&quot;Pavadinimas   Reikšmė</span>
<span class="st">Pirmas         1</span>
<span class="st">Du žodžiai     2</span>
<span class="st">Keli žodžiai   3</span>
<span class="st">&quot;</span>)
<span>## Warning in fread(&quot;Pavadinimas Reikšmė\nPirmas 1\nDu žodžiai 2\nKeli žodžiai</span>
<span>## 3\n&quot;): Stopped early on line 3. Expected 2 fields but found 3. Consider</span>
<span>## fill=TRUE and comment.char=. First discarded non-empty line: &lt;&lt;Du žodžiai</span>
<span>## 2&gt;&gt;</span>

neteisingai
<span>##    Pavadinimas Reikšmė</span>
<span>## 1:      Pirmas       1</span></code></pre><p>Keli variantai, kaip nuskaitymą atlikti teisingai:</p><ol style="list-style-type:decimal"><li>Visą tekstą dėti į viengubas kabutes, o reikiamų stulpelių reikšmes – į dvigubas:</li></ol><pre class="sourceCode r"><code class="sourceCode r">teisingai1 &lt;-<span class="st"> </span><span class="kw">fread</span>(
<span class="st">&#39;Pavadinimas   Reikšmė</span>
<span class="st">Pirmas         1</span>
<span class="st">&quot;Du žodžiai&quot;   2</span>
<span class="st">&quot;Keli žodžiai&quot; 3</span>
<span class="st">&#39;</span>)

teisingai1
<span>##     Pavadinimas Reikšmė</span>
<span>## 1:       Pirmas       1</span>
<span>## 2:   Du žodžiai       2</span>
<span>## 3: Keli žodžiai       3</span></code></pre><ol start="2"style="list-style-type:decimal"><li>Visą tekstą dėti į dvigubas kabutes, o prieš stulpeliuose esančias dvigubas kabutes pridėti atgal pasvirusį brūkšnį (<code>\</code>), kaip parodyta šiame pavyzdyje:</li></ol><pre class="sourceCode r"><code class="sourceCode r">teisingai2 &lt;-<span class="st"> </span><span class="kw">fread</span>(
<span class="st">&quot;Pavadinimas     Reikšmė</span>
<span class="st">Pirmas           1</span>
<span class="ch">\&quot;</span><span class="st">Du žodžiai\&quot;</span>   <span class="dv">2</span>
\<span class="st">&quot;Keli žodžiai\&quot;</span> <span class="dv">3</span>
<span class="st">&quot;)</span>

<span class="st">teisingai2</span>
<span class="st">##     Pavadinimas Reikšmė</span>
<span class="st">## 1:       Pirmas       1</span>
<span class="st">## 2:   Du žodžiai       2</span>
<span class="st">## 3: Keli žodžiai       3</span></code></pre></div><div id="klasikiniai-metodai-pi-skaiciuoti"class="section level2"><h2><span class="header-section-number">12.3</span> Klasikiniai metodai PI skaičiuoti</h2></div><div id="vidurkio-pi"class="section level2"><h2><span class="header-section-number">12.4</span> Vidurkio PI</h2><p>Klasikiniai PI sudarymo metodai įprastai grindžiami prielaida, kad duomenys yra normalieji. Tokiems duomenis puikiai tinka įvairūs teoriniai modeliai, išvedamos formulės.</p><p><em>Pliusai.</em> Turint formulę, galima ją pertvarkyti taip, kad būtų galima apskaičiuoti bet kurį jos narį. Skaičiavimai atliekami greitai.</p><p><em>Minusai.</em> Reikia tenkinti normalumo ir kitas prielaidas. Tinka tik kai kurioms statistikoms, tokioms kaip vidurkis. Tačiau kvartiliams ir panašioms neparametrinėms statistikoms – tokių formulių nėra.</p><p>Panagrinėkime pirmą pavyzdį. Iš normaliojo skirstinio su vidurkiu 50 ir standartiniu nuokrypiu 10 sugeneruoti duomenys:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">98</span>)
x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">50</span>, <span class="dt">mean =</span> <span class="dv">50</span>, <span class="dt">sd =</span> <span class="dv">10</span>)</code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(pander)

<span class="kw">panderOptions</span>(<span class="st">&quot;keep.trailing.zeros&quot;</span>,  <span class="ot">TRUE</span>)</code></pre><pre class="sourceCode r"><code class="sourceCode r">RcmdrMisc<span class="op">::</span><span class="kw">normalityTest</span>(x, <span class="dt">test =</span> <span class="st">&quot;shapiro.test&quot;</span>)
<span>## </span>
<span>##  Shapiro-Wilk normality test</span>
<span>## </span>
<span>## data:  x</span>
<span>## W = 0.9601, p-value = 0.08974</span></code></pre><p>Shapiro-Wilk kriterijumi testuojamas pasiskirstymo normalumas. Jei <span class="math inline">\(p \ge 0.05\)</span>, tai skaitoma, kad nuokrypis nuo normalumo nėra statistiškai reikšmingas ir normalumo prielaida galioja.</p><p>Jei turėtume labai dideles imtis, net maži nuokrypiai būtų pripažįstami statistiškai reikšmingais (t.y., nuokrypiai, stebimi duomenyse, tikėtina, egzistuoja ir visoje generalinėje aibėje). Tokiu atveju normalumas papildomai testuojamas grafiškai naudojant kvantilių-kvantilių diagramą (qq-grafiką), norint patikrinti, ar tas nuokrypis ne tik statistiškai, bet ir praktiškai reikšmingas.</p><pre class="sourceCode r"><code class="sourceCode r">car<span class="op">::</span><span class="kw">qqPlot</span>(x)</code></pre><p><img src="08--01--pi-klasikiniai_files/figure-html/unnamed-chunk-32-1.png"width="384"style="display:block;margin:auto"></p><pre><code>## [1] 42 36
qplot(x, geom = &quot;histogram&quot;, bins = 6, color = I(&quot;black&quot;))</code></pre><p><img src="08--01--pi-klasikiniai_files/figure-html/unnamed-chunk-32-2.png"width="384"style="display:block;margin:auto"> Visiškai normalieji duomenys išsidėsto į vieną tiesę. Nukrypimai nuo jos rodo nuokrypius nuo normaliojo pasiskirstymo. Natūralu, jei grafiko galuose atsiras vienas kitas šiek tiek nuo tiesės nukrypęs taškas. Ypač svarbu, kad tarp 1 ir 3 kvartilio esantys taškai išsidėstytų daugmaž vienoje tiesėje. (Apie šį grafiką rekomenduoju daugiau informacijos susirasti savarankiškai, naudingos nuorodos: <a href="http://desktop.arcgis.com/en/arcmap/latest/extensions/geostatistical-analyst/normal-qq-plot-and-general-qq-plot.htm">nuoroda 1</a>, <a href="http://data.library.virginia.edu/understanding-q-q-plots/">nuoroda 2</a>)</p><p>Turint tik duomenų imtį (duomenis)ir jokios kitos papildomos informacijos), vidurkio PI skaičiavimas pagal Stjudento t-skirstiniu pagrįstą formulę yra universaliausias, jei duomenys normalieji:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 95% vidurkio pasikliauties intervalas</span>
DescTools<span class="op">::</span><span class="kw">MeanCI</span>(<span class="dt">x =</span> x)
<span>##     mean   lwr.ci   upr.ci </span>
<span>## 47.21401 44.38835 50.03966</span></code></pre><p>Savirankos <span class="math inline">\(BC_a\)</span> metodu vidurkio CI gali būti apskaičiuotas paketo <strong>DescTools</strong> funkcijas:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">123456</span>)
DescTools<span class="op">::</span><span class="kw">MeanCI</span>(<span class="dt">x =</span> x, <span class="dt">method =</span> <span class="st">&quot;boot&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;bca&quot;</span>, <span class="dt">R =</span> <span class="dv">2000</span>)
<span>##     mean   lwr.ci   upr.ci </span>
<span>## 47.21401 44.48821 49.85862</span></code></pre><p>Apie savirankos metodus ir čia naudotus parametrus bus daugiau aprašyta kitose šios pamokos skyriuose.</p><div id="z-formule"class="section level3"><h3><span class="header-section-number">12.4.1</span> Vidurkio PI, kai GA dispersija žinoma</h3><p>Kai generalinės aibės dispersija žinoma, vidurkio PI galima skaičiuoti pagal formulę <a href="pi-klasikiniai.html#eq:z-formula">(12.1)</a>. Situacija, kai tikrasis vidurkis nežinomas, o išsisklaidymas aplink jį – dispersija – žinoma, yra tik hipotetinė. Tačiau formulė ganėtinai paprasta ir mokymosi tikslais iliustruoti, kaip konstruojamas PI, tinkama. Ši formulė taip pat naudojama, kai imties dydis pakankamai didelis.</p><p><span class="math display"id="eq:z-formula">\[\begin{equation} \hat{\mu}_{1,2} = \overline{X} \mp z_{\left(\frac{1-Q}{2}\right)}{\sigma \over \sqrt{n}} \tag{12.1} \end{equation}\]</span></p><p>Formulėje:<br><span class="math inline">\(\hat{\mu}_{1}\)</span> – apatinė vidurkio pasikliauties intervalo riba (mažesnis skaičius);<br><span class="math inline">\(\hat{\mu}_{2}\)</span> – viršutinė vidurkio pasikliauties intervalo riba (didesnis skaičius);<br><span class="math inline">\(\overline{X}\)</span> – imties vidurkis;<br><span class="math inline">\(\sigma\)</span> – <em>generalinės aibės</em> standartinis nuokrypis (arba imties standartinis nuokrypis, jei <em>duomenų pakankamai daug</em>);<br><span class="math inline">\(n\)</span> – imties dydis;<br><span class="math inline">\(Q\)</span> – pasikliovimo lygmuo (tikimybė);<br><span class="math inline">\({\left(\frac{1-Q}{2}\right)}\)</span> – galime pažymėti kaip tikimybę <span class="math inline">\(\alpha\)</span>;<br><span class="math inline">\(z_{\alpha}\)</span> – <span class="math inline">\(z\)</span> koeficientas – daugiklis, dar vadinamas standartinio normaliojo skirstinio <span class="math inline">\(1-\alpha\)</span> lygmens kvantiliu (skaičius, priklausantis nuo norimo pasikliovimo lygmens). Jis imamas iš lentelių arba apskaičiuojamas programomis <em>R</em>, <em>GeoGebra</em> ar kitomis.</p><p>Ši formulė tinka <strong>normaliai pasiskirsčiusiems</strong> duomenims, arba duomenims, kurių yra tiek daug, kad galioja centrinė ribinė teorema.</p><br><div class="note"><p>Formulė susideda iš 3 dalių: taškinis vidurkio įvertis, koeficientas, priklausantis nuo norimo pasikliovimo lygmens, ir standartinė vidurkio paklaida. Ar matote jas visas?</p></div><p><br>Siekiant apsiskaičiuoti reikiamą imties dydį, kad būtų pasiektas norimas tikslumas (intervalo ilgis), gali būti naudojama iš <a href="pi-klasikiniai.html#eq:z-formula">(12.1)</a> formulės išvesta lygtis <a href="pi-klasikiniai.html#eq:n-from-z-formula">(12.3)</a>.<br><br></p><div class="note">Formulė su <span class="math inline">\(z\)</span> koeficientu tinkama tada, kai žinome tikrąją generalinės aibės dispersiją <span class="math inline">\((\sigma^2)\)</span>. Arba imtyje duomenų pakankamai daug – vienų autorių teigimu <span class="math inline">\(n&gt;50\)</span>, kitų – <span class="math inline">\(n&gt;30\)</span>. Galima alternatyva, kai imtis maža, bet pasiskirsčiusi normaliai – formulė, kurioje naudojamas <span class="math inline">\(t\)</span> koeficientas.</div><p>Jei norite skaičiuoti automatiškai, štai <em>R</em> kodas:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(npk)
derlius &lt;-<span class="st"> </span>npk<span class="op">$</span>yield</code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># --- Keisti tik šias eilutes ------------------------------------------------</span>
<span class="co"># Pasirenkame duomenų vektorių `x` ir pasikliovimo lygmenį – tikimybę `Q`.</span>
<span class="co"># Jei turite suvestinę, vietoje `x` įrašykite kintamųjų</span>
<span class="co"># `n`, `st_nuokrypis` ir `vidurkis` reikšmes.</span>

x    &lt;-<span class="st"> </span>derlius
Q    &lt;-<span class="st"> </span><span class="fl">0.95</span>

<span class="co"># ----------------------------------------------------------------------------</span>
n            &lt;-<span class="st"> </span><span class="kw">length</span>(x)
st_nuokrypis &lt;-<span class="st"> </span><span class="kw">sd</span>(x)
vidurkis     &lt;-<span class="st"> </span><span class="kw">mean</span>(x)

<span class="co"># --- Toliau esančio kodo nekeisti -------------------------------------------</span>
<span class="co"># Taikome formulę su z koeficientu:</span>
z         &lt;-<span class="st"> </span><span class="kw">qnorm</span>((<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>Q) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)
paklaida  &lt;-<span class="st"> </span>z <span class="op">*</span><span class="st"> </span>st_nuokrypis<span class="op">/</span><span class="kw">sqrt</span>(n)

apatinė_riba   &lt;-<span class="st"> </span>vidurkis <span class="op">-</span><span class="st"> </span>paklaida
viršutinė_riba &lt;-<span class="st"> </span>vidurkis <span class="op">+</span><span class="st"> </span>paklaida

<span class="co"># Rezultatai:</span>
vidurkio_pi_z &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dt">vidurkis =</span> vidurkis,
                   <span class="dt">PI_apatine_riba   =</span> apatinė_riba,
                   <span class="dt">PI_virsutine_riba =</span> viršutinė_riba)
<span class="co"># ----------------------------------------------------------------------------</span></code></pre><p>Rezultatas:</p><pre class="sourceCode r"><code class="sourceCode r">vidurkio_pi_z
<span>##          vidurkis   PI_apatine_riba PI_virsutine_riba </span>
<span>##          54.87500          52.40543          57.34457</span></code></pre><p>Iki <em>vieno</em> skaičiaus po kablelio suapvalintas rezultatas:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">round</span>(vidurkio_pi_z, <span class="dt">digits =</span> <span class="dv">1</span>)
<span>##          vidurkis   PI_apatine_riba PI_virsutine_riba </span>
<span>##              54.9              52.4              57.3</span></code></pre><br><div class="task"><p><strong>Užduotis 12.4</strong></p><ol style="list-style-type:decimal"><li>Išmatuotas <span class="math inline">\(100\)</span> studentų cholesterolio kiekis kraujyje. Gautas vidurkis <span class="math inline">\(310\frac{\mu mol}{l}\)</span>. Koks cholesterolio kiekio kraujyje vidurkio <span class="math inline">\(95\%\)</span> pasikliauties intervalas, jeigu šio dydžio standartinis nuokrypis studentų populiacijoje yra <span class="math inline">\(35\frac{\mu mol}{l}\)</span>?</li></ol></div></div><div id="t-formule"class="section level3"><h3><span class="header-section-number">12.4.2</span> Vidurkio PI, kai GA dispersija nežinoma</h3><p>Kai GA dispersija nežinoma, tada vidurkio PI skaičiavimo formulėje naudojame dispersiją, apskaičiuotą iš duomenų. Tokiu atveju vietoje z koeficiento reikia naudoti t koeficientą, kurio dydis priklauso nuo imties dydžio. Tad tokia formulė kaip <a href="pi-klasikiniai.html#eq:t-formula">(12.2)</a> savo surinktiems duomenims analizuoti yra <strong>naudingesnė</strong>.</p><p><span class="math display"id="eq:t-formula">\[\begin{equation} \hat{\mu}_{1,2} = \overline{X} \mp t_{\left(\frac{1-Q}{2}\right)}(n-1) {S \over \sqrt{n}} \tag{12.2} \end{equation}\]</span></p><p>Formulėje:<br><span class="math inline">\(\hat{\mu}_{1}\)</span> – apatinė vidurkio pasikliauties intervalo riba (mažesnis skaičius);<br><span class="math inline">\(\hat{\mu}_{2}\)</span> – viršutinė vidurkio pasikliauties intervalo riba (didesnis skaičius);<br><span class="math inline">\(\overline{X}\)</span> – imties vidurkis;<br><span class="math inline">\(S\)</span> – imties standartinis nuokrypis;<br><span class="math inline">\(n\)</span> – imties dydis;<br><span class="math inline">\(Q\)</span> – pasikliovimo lygmuo (tikimybė);<br><span class="math inline">\({\left(\frac{1-Q}{2}\right)}\)</span> – galime pažymėti kaip tikimybę <span class="math inline">\(\alpha\)</span>;<br><span class="math inline">\(t_{\alpha}(n-1)\)</span> – daugiklis, dar vadinamas Stjudento koeficientu arba Stjudento skirstinio (su <span class="math inline">\(n-1\)</span> laisvės laipsnių) <span class="math inline">\(1-\alpha\)</span> lygmens kvantiliu (skaičius, priklausantis nuo norimo pasikliovimo lygmens). Jis imamas iš lentelių arba apskaičiuojamas programomis <em>R</em>, <em>GeoGebra</em> ar kitomis.</p><p>Ši formulė tinka <strong>normaliai pasiskirsčiusiems</strong> duomenims, arba duomenims, kurių yra tiek daug, kad galioja centrinė ribinė teorema.</p><br><div class="note"><p>Pamenat, formulė susideda iš 3 dalių. Ar ir šiuo atveju matote jas visas?</p></div><p><br></p><p>Štai <em>R</em> kodas, jei norite, kad <em>R</em> apskaičiuotų už jus:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(npk)
derlius &lt;-<span class="st"> </span>npk<span class="op">$</span>yield</code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># --- Keisti tik šias eilutes ------------------------------------------------</span>
<span class="co"># Pasirenkame duomenų vektorių `x` ir pasikliovimo lygmenį – tikimybę `Q`.</span>
<span class="co"># Jei turite suvestinę, vietoje `x` įrašykite kintamųjų</span>
<span class="co"># `n`, `st_nuokrypis` ir `vidurkis` reikšmes.</span>

x    &lt;-<span class="st"> </span>derlius
Q    &lt;-<span class="st"> </span><span class="fl">0.95</span>

<span class="co"># ----------------------------------------------------------------------------</span>
n            &lt;-<span class="st"> </span><span class="kw">length</span>(x)
st_nuokrypis &lt;-<span class="st"> </span><span class="kw">sd</span>(x)
vidurkis     &lt;-<span class="st"> </span><span class="kw">mean</span>(x)

<span class="co"># --- Toliau esančio kodo nekeisti -------------------------------------------</span>
<span class="co"># Taikome formulę su t koeficientu:</span>
t          &lt;-<span class="st"> </span><span class="kw">qt</span>((<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>Q) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>, <span class="dt">df =</span> (n <span class="op">-</span><span class="st"> </span><span class="dv">1</span>), <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)
paklaida   &lt;-<span class="st"> </span>t <span class="op">*</span><span class="st"> </span>st_nuokrypis<span class="op">/</span><span class="kw">sqrt</span>(n)

apatinė_riba   &lt;-<span class="st"> </span>vidurkis <span class="op">-</span><span class="st"> </span>paklaida
viršutinė_riba &lt;-<span class="st"> </span>vidurkis <span class="op">+</span><span class="st"> </span>paklaida

vidurkio_pi_t &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dt">vidurkis =</span> vidurkis,
                   <span class="dt">PI_apatine_riba   =</span> apatinė_riba,
                   <span class="dt">PI_virsutine_riba =</span> viršutinė_riba)
<span class="co"># ----------------------------------------------------------------------------</span></code></pre><p>Rezultatas:</p><pre class="sourceCode r"><code class="sourceCode r">vidurkio_pi_t
<span>##          vidurkis   PI_apatine_riba PI_virsutine_riba </span>
<span>##          54.87500          52.26848          57.48152</span></code></pre><p>Iki <em>vieno</em> skaičiaus po kablelio suapvalintas rezultatas:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">round</span>(vidurkio_pi_t, <span class="dt">digits =</span> <span class="dv">1</span>)
<span>##          vidurkis   PI_apatine_riba PI_virsutine_riba </span>
<span>##              54.9              52.3              57.5</span></code></pre><div class="note"><p>Formulė su <span class="math inline"><span class="math inline">\(t\)</span></span> koeficientu yra universalesnė, tinka, kai duomenų nedaug. Visgi, jų turi būti pakankamai, o ne vos keli taškai. Jei taškų iki 15 – pasiskirstymas privalo būti idealiai normalusis.</p></div><br><div class="task"><p><strong>Užduotis 12.5 </strong>Užsikraukite duomenis, naudodami komandą <strong><em>data(swiss)</em></strong>.</p><ol style="list-style-type:decimal"><li>Duomenų lentelė <strong><em>swiss</em></strong>:<ol style="list-style-type:lower-alpha"><li>Apskaičiuokite kintamojo <em>Fertility</em> reikšmių vidurkio 95% pasikliauties intervalą.</li><li>Ar šie duomenys tenkina prielaidas vidurkio pasikliauties intervalui skaičiuoti naudojant formulę?</li></ol></li></ol></div><div id="rcmdr-vidurkio-pi-skaiciavimui"class="section level4 unnumbered"><h4><strong><em>Rcmdr</em></strong> vidurkio PI skaičiavimui</h4><p>Vidurkio pasikliauties intervalą pagal <a href="pi-klasikiniai.html#eq:t-formula">(12.2)</a> lygtį galime skaičiuoti naudodami <strong>Rcmdr</strong> įskiepį <strong>RcmdrPlugin.EZR.as.menu</strong> (diegimo instrukcijos šios knygos prieduose). Užkrovus šį įskiepį atsiranda mygtukas pavadinimu „<em>EZR</em>“ (pav. <a href="pi-klasikiniai.html#fig:08-Rcmdr-EZR2">12.1</a>).</p><br><div class="figure"style="text-align:center"><span id="fig:08-Rcmdr-EZR2"></span> <img src="fig/pic/08/08-Rcmdr-EZR2.png"alt="**RcmdrPlugin.EZR.as.menu** meniu mygtukas *R Commander* meniu juostoje.  "width="594"><p class="caption">Pav. 12.1: <strong>RcmdrPlugin.EZR.as.menu</strong> meniu mygtukas <em>R Commander</em> meniu juostoje.</p></div><p><br></p><div class="figure"style="text-align:center"><span id="fig:08-EZR-mean-ci-t"></span> <img src="fig/pic/08/08-EZR-mean-ci-t.png"alt="Vidurkio pasikliauties intervalo skaičiavimas pagal \@ref(eq:t-formula) formulę naudojant *Rcmdr*. Atsidariusioje lentelėje įrašome reikiamus skaičius: vidurkį, standartinį nuokrypį ir imties dydį. Sveikąją ir dešimtąją skaičiaus dalį reikia atskirti **tašku** (pvz., 10.254), o ne kableliu.  "width="862"><p class="caption">Pav. 12.2: Vidurkio pasikliauties intervalo skaičiavimas pagal <a href="pi-klasikiniai.html#eq:t-formula">(12.2)</a> formulę naudojant <em>Rcmdr</em>. Atsidariusioje lentelėje įrašome reikiamus skaičius: vidurkį, standartinį nuokrypį ir imties dydį. Sveikąją ir dešimtąją skaičiaus dalį reikia atskirti <strong>tašku</strong> (pvz., 10.254), o ne kableliu.</p></div></div></div><div id="n-from-z-formula"class="section level3"><h3><span class="header-section-number">12.4.3</span> Imties dydžio skaičiavimas norimam vidurkio PI ilgiui</h3><p>Iš formulės <a href="pi-klasikiniai.html#eq:z-formula">(12.1)</a> galima išsireikšti imties dydį, kurio reikia norimam tikslumui pasiekti. Tai aprašo lygtis <a href="pi-klasikiniai.html#eq:n-from-z-formula">(12.3)</a>:</p><p><span class="math display"id="eq:n-from-z-formula">\[\begin{equation} n = \left( {2 \cdot \sigma\cdot z_{\left(\frac{1-Q}{2}\right)} } \over \Delta\hat{\mu} \right)^2 \tag{12.3} \end{equation}\]</span></p><p>Formulėje:<br><span class="math inline">\(n\)</span> – imties dydis;<br><span class="math inline">\(\Delta\hat{\mu}\)</span> – vidurkio pasikliauties intervalo <strong>ilgis</strong>;<br><span class="math inline">\(\sigma\)</span> – (hipotetinis) standartinis nuokrypis;<br><span class="math inline">\(Q\)</span> – pasikliovimo lygmuo (tikimybė);<br><span class="math inline">\({\left(\frac{1-Q}{2}\right)}\)</span> – galime pažymėti kaip tikimybę <span class="math inline">\(\alpha\)</span>;<br><span class="math inline">\(z_{\alpha}\)</span> – <span class="math inline">\(z\)</span> koeficientas – daugiklis, dar vadinamas standartinio normaliojo skirstinio <span class="math inline">\(1-\alpha\)</span> lygmens kvantiliu (skaičius, priklausantis nuo norimo pasiliovimo lygmens).</p><p>Rezultatą apvaliname iki sveikųjų skaičių į didesniąją pusę, tarkim 60,02 → 61. Kitu atveju intervalas bus per trumpas. Šio tipo skaičiavimą galima atlikti papildiniu <em>Rcmdr</em> (pav. <a href="pi-klasikiniai.html#fig:08-EZR-mean-ci-sample-size">12.3</a>).<br></p><div class="figure"style="text-align:center"><span id="fig:08-EZR-mean-ci-sample-size"></span> <img src="fig/pic/08/08-EZR-mean-ci-sample-size.png"alt="Papildinio **RcmdrPlugin.EZR.as.menu** naudojimas reikiamo imties dydžio skaičiavimui norimam pasikliauties intervalo pločiui gauti.   "width="960"><p class="caption">Pav. 12.3: Papildinio <strong>RcmdrPlugin.EZR.as.menu</strong> naudojimas reikiamo imties dydžio skaičiavimui norimam pasikliauties intervalo pločiui gauti.</p></div><p><br></p><div class="task"><p><strong>Užduotis 12.6 </strong>Išmatuota 93 studentų cholesterolio koncentracija kraujyje. Gautas vidurkis yra <span class="math inline"><span class="math inline">\(308\frac{\mu mol}{l}\)</span></span>.</p><ol style="list-style-type:lower-alpha"><li>Koks yra cholesterino kiekio kraujyje 99% pasikliauties intervalas, jeigu imties standartinis nuokrypis – <span class="math inline"><span class="math inline">\(35\frac{\mu mol}{l}\)</span></span>?</li><li>Kokio imties dydžio reikia, kad intervalo ilgis būtų <span class="math inline"><span class="math inline">\(30\frac{\mu mol}{l}\)</span></span>?</li><li>Kokio imties dydžio reikia, kad intervalo ilgis būtų <span class="math inline"><span class="math inline">\(2\)</span></span> vienetais mažesnis, nei gautas (<strong>a</strong>) punkte?</li></ol></div></div></div><div id="pi-proporcijai"class="section level2"><h2><span class="header-section-number">12.5</span> Proporcijos PI</h2><p>Kategoriniai kintamieji gali būti skirstomi į:</p><ol style="list-style-type:lower-alpha"><li>dvireikšmius – galinčius įgyti dvi skirtingas reikšmes, pvz., gėrimas tik „šiltas“ arba „šaltas“ <span class="math inline">\((k = 2)\)</span>;</li><li>daugiareikšmius – galinčius įgyti daugiau nei 2 skirtingas reikšmes, pvz., driežas „raudonas“, „juodas“, „geltonas“, „žalias“ <span class="math inline">\((k &gt; 2)\)</span>.</li></ol><p>Čia <span class="math inline">\(k\)</span> – kategorijų skaičius. Todėl proporcijos taipogi skirstomos į dvireikšmių kintamųjų proporcijas (arba binominėmis proporcijomis, angl., <em>binomial proportion</em>) ir daugiareikšmių kintamųjų proporcijas (arba multinominėmis proporcijomis, angl., <em>binomial proportion</em>)</p>Primenu, kad norint skaičiuoti PI imtis turi būti sudaryta atsitiktinai. kitaip PI neturi prasmės.<br><div class="note"><p>Pradedantiesiems rekomenduojama tokia proporcijos PI pasirinkimo schema:</p><ul><li>kai <span class="math inline">\(k=2\)</span> rinkitės <strong>koreguotą Wilson</strong> metodą. Jis tinka ir tada, kai proporcija p maža (netoli 0) arba didelė (netoli 1).</li><li>kai <span class="math inline">\(k&gt;2\)</span> ir kai kiekvienoje grupėje bent po 6 (geriausia bent po 10) narių ir grupių skaičius ne per didelis (sakykim, <span class="math inline">\(k&lt;10\)</span>), rinkitės <strong>Goodman</strong> metodą (šis metodas tinkamas daugeliui praktiškai pasitaikančių situacijų);</li><li>kai <span class="math inline">\(k&gt;2\)</span> kiekvienoje grupėje daugmaž vienodas skaičius narių, rinkitės <strong>Sison-Glaz</strong> metodą. Metodas ypač tinka tada, kai grupėse narių mažai, o grupių labai daug. Bet jei yra bent viena pagal narių skaičių dominuojanti grupė, tada metodas duoda prastus rezultatus ir jo reiktų nesirinkti.</li></ul></div><br>Šie metodai pasiekiami naudojant paketo <strong>DescTools</strong> funkcijas. Norint naudoti binominės proporcijos metodus, reikia žinoti, kiek mūsų imtyje yra narių iš viso (<em>n</em>), ir kiek iš jų turi mums dominančią savybę (<em>x</em>).<pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">30</span> <span class="co"># Imtyje pasitaikiusių šaltų gėrimų skaičius</span>
n &lt;-<span class="st"> </span><span class="dv">66</span> <span class="co"># Imties dydis</span>
<span class="co"># Wilson metodas:</span>
DescTools<span class="op">::</span><span class="kw">BinomCI</span>(x, n, <span class="dt">method =</span> <span class="st">&quot;wilson&quot;</span>) 
<span>##            est    lwr.ci    upr.ci</span>
<span>## [1,] 0.4545455 0.3402413 0.5738499</span>
<span class="co"># Koreguotas Wilson metodas:</span>
DescTools<span class="op">::</span><span class="kw">BinomCI</span>(x, n, <span class="dt">method =</span> <span class="st">&quot;modified wilson&quot;</span>)
<span>##            est    lwr.ci    upr.ci</span>
<span>## [1,] 0.4545455 0.3402413 0.5738499</span></code></pre><p>Rezultatas yra matrica (todėl vėliau ją versime į duomenų lentelę), kurios stulpeliai: <em>est</em> – proporcijos taškinis įvertis, <em>lwr.ci</em> ir <em>upr.ci</em> – proporcijos pasikliauties intervalo apatinė ir viršutinė ribos.</p><p>Multinominių proporcijų skaičiavimui reikia žinoti, kiek kurios grupės narių pasitaikė.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Imtyje pasitaikė 24 juodi, 52 raudoni, 26 žali ir 43 geltoni driežiukai</span>
x_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">24</span>, <span class="dv">52</span>, <span class="dv">26</span>, <span class="dv">43</span>)
DescTools<span class="op">::</span><span class="kw">MultinomCI</span>(x_<span class="dv">2</span>, <span class="dt">method =</span> <span class="st">&quot;goodman&quot;</span>)
<span>##            est     lwr.ci    upr.ci</span>
<span>## [1,] 0.1655172 0.09685563 0.2683888</span>
<span>## [2,] 0.3586207 0.25715494 0.4745463</span>
<span>## [3,] 0.1793103 0.10742403 0.2839959</span>
<span>## [4,] 0.2965517 0.20314729 0.4107643</span></code></pre><p>Kiekvienai grupei (juodi, raudoni, žali, geltoni) skirta atskira eilutė.</p><pre class="sourceCode r"><code class="sourceCode r">
<span class="co"># Imtyje pasitaikė 24 juodi, 22 raudoni, 26 žali ir 23 geltoni driežiukai</span>
x_<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">24</span>, <span class="dv">22</span>, <span class="dv">26</span>, <span class="dv">23</span>)
DescTools<span class="op">::</span><span class="kw">MultinomCI</span>(x_<span class="dv">3</span>, <span class="dt">method =</span> <span class="st">&quot;sisonglaz&quot;</span>)
<span>##            est    lwr.ci    upr.ci</span>
<span>## [1,] 0.2526316 0.1578947 0.3661081</span>
<span>## [2,] 0.2315789 0.1368421 0.3450555</span>
<span>## [3,] 0.2736842 0.1789474 0.3871608</span>
<span>## [4,] 0.2421053 0.1473684 0.3555818</span></code></pre><div id="pavyzdys-1-triusiai"class="section level3"><h3><span class="header-section-number">12.5.1</span> Pavyzdys 1: triušiai</h3><p>Sakykime, visiškai atsitiktinai sudarytoje imtyje 150 triušių ir 50 iš jų yra margi. Tad margų triušių dalies generalinėje aibėje 95% pasikliauties intervalas yra 0,26-0,41:</p><pre class="sourceCode r"><code class="sourceCode r">(prop_pi &lt;-<span class="st"> </span>DescTools<span class="op">::</span><span class="kw">BinomCI</span>(<span class="dt">x =</span> <span class="dv">50</span>, <span class="dt">n =</span> <span class="dv">150</span>, <span class="dt">method =</span> <span class="st">&quot;wilson&quot;</span>))
<span>##            est    lwr.ci    upr.ci</span>
<span>## [1,] 0.3333333 0.2628876 0.4121024</span></code></pre><pre class="sourceCode r"><code class="sourceCode r">prop_pi_df &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(prop_pi)

<span class="kw">ggplot</span>(prop_pi_df, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="st">&quot;Margi triušiai&quot;</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_col</span>(<span class="kw">aes</span>(<span class="dt">y =</span> est), <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;skyblue1&quot;</span>, <span class="dt">width =</span> <span class="fl">0.5</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> lwr.ci, <span class="dt">ymax =</span> upr.ci), <span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">width =</span> <span class="fl">0.1</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;&quot;</span>,
         <span class="dt">y =</span> <span class="st">&quot;Dalis&quot;</span>,
         <span class="dt">title =</span> <span class="st">&quot;Margų triušių dalis populiacijoje&quot;</span>,
         <span class="dt">subtitle =</span> <span class="st">&quot;Įvertis ir 95% pasikliauties intervalas&quot;</span>)</code></pre><p><img src="08--01--pi-klasikiniai_files/figure-html/unnamed-chunk-58-1.png"width="384"style="display:block;margin:auto"></p></div><div id="pavyzdys-2-rasine-ivairove"class="section level3"><h3><span class="header-section-number">12.5.2</span> Pavyzdys 2: rasinė įvairovė</h3><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(DescTools)</code></pre><p>Įsikeliame duomenis.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(birthwt, <span class="dt">package =</span> <span class="st">&quot;MASS&quot;</span>)</code></pre><p>Sudarome norimo požymio (rasės) dažnių lentelę.</p><pre class="sourceCode r"><code class="sourceCode r">birthwt <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(race)
<span>## # A tibble: 3 x 2</span>
<span>##    race     n</span>
<span>##   &lt;int&gt; &lt;int&gt;</span>
<span>## 1     1    96</span>
<span>## 2     2    26</span>
<span>## 3     3    67</span></code></pre><p>Rasių atžvilgiu duomenys buvo surinkti <strong>visiškai atsitiktinai</strong>, todėl pagal imtį galime spręsti apie pasiskirstymą generalinėje aibėje – sudaryti pasikliautinuosius intervalus. Rasių kodų reikšmės: 1 – baltoji rasė, 2 – juodoji rasė, 3 – kitos rasės. Norėdami išlaikyti grupių pavadinimus, duomenis pateikiame tokiu formatu – <code>"pavadinimas" = skaičius</code>:</p><pre class="sourceCode r"><code class="sourceCode r">rasiu_pi_matrica &lt;-<span class="st"> </span>
<span class="st">    </span>DescTools<span class="op">::</span><span class="kw">MultinomCI</span>(
        <span class="dt">x =</span> <span class="kw">c</span>(<span class="st">&quot;baltoji&quot;</span> =<span class="st"> </span><span class="dv">96</span>,
              <span class="st">&quot;juodoji&quot;</span> =<span class="st"> </span><span class="dv">26</span>,
              <span class="st">&quot;kitos&quot;</span>   =<span class="st"> </span><span class="dv">67</span>),
        <span class="dt">method =</span> <span class="st">&quot;goodman&quot;</span>)

rasiu_pi_matrica
<span>##               est     lwr.ci    upr.ci</span>
<span>## baltoji 0.5079365 0.42005803 0.5953273</span>
<span>## juodoji 0.1375661 0.08730632 0.2100988</span>
<span>## kitos   0.3544974 0.27499693 0.4429394</span></code></pre><p>Duomenų matricą paverčiame į duomenų lentelę, eilučių pavadinimus perkeliame į stulpelį „rasė“.</p><pre class="sourceCode r"><code class="sourceCode r">rasiu_pi_lentele &lt;-<span class="st"> </span>
<span class="st">    </span><span class="kw">as.data.frame</span>(rasiu_pi_matrica) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">rownames_to_column</span>(<span class="st">&quot;rasė&quot;</span>)
rasiu_pi_lentele
<span>##      rasė       est     lwr.ci    upr.ci</span>
<span>## 1 baltoji 0.5079365 0.42005803 0.5953273</span>
<span>## 2 juodoji 0.1375661 0.08730632 0.2100988</span>
<span>## 3   kitos 0.3544974 0.27499693 0.4429394</span></code></pre><p>Duomenis atvaizduojame.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(rasiu_pi_lentele, <span class="kw">aes</span>(<span class="dt">x =</span> rasė, <span class="dt">color =</span> rasė)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> lwr.ci, <span class="dt">ymax =</span> upr.ci), <span class="dt">width =</span> <span class="fl">0.2</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> est), <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Proporcija ir jos 95% pasikliauties intervalas&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">ylim</span>(<span class="dv">0</span>, <span class="fl">0.7</span>)</code></pre><p><img src="08--01--pi-klasikiniai_files/figure-html/unnamed-chunk-64-1.png"width="480"style="display:block;margin:auto"></p></div><div id="pavyzdys-3-grupes-pagal-ugi"class="section level3"><h3><span class="header-section-number">12.5.3</span> Pavyzdys 3: grupės pagal ūgį</h3><p>Šiek tiek įdomesnis pavyzdys, kaip apsiskaičiuoti multinominės proporcijos pasikliauties intervalą iš duomenų.</p><p>Kad būtų aiškiau, duomenis susigeneruokime.</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">100</span>)
ugiu_pogrupiai &lt;-<span class="st"> </span><span class="kw">data.frame</span>(
    <span class="dt">ugiai =</span> <span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;Aukštas&quot;</span>, <span class="dv">80</span>), <span class="kw">rep</span>(<span class="st">&quot;Vidutinis&quot;</span>, <span class="dv">120</span>), <span class="kw">rep</span>(<span class="st">&quot;Žemas&quot;</span>, <span class="dv">100</span>)),
    <span class="dt">x =</span> <span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">300</span>, <span class="dt">mean =</span> <span class="dv">90</span>,  <span class="dt">sd =</span> <span class="dv">5</span>),
    <span class="dt">y =</span> <span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">300</span>, <span class="dt">mean =</span> <span class="dv">110</span>, <span class="dt">sd =</span> <span class="dv">6</span>))</code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">glimpse</span>(ugiu_pogrupiai)
<span>## Observations: 300</span>
<span>## Variables: 3</span>
<span>## $ ugiai &lt;fct&gt; Aukštas, Aukštas, Aukštas, Aukštas, Aukštas, Aukštas, Au...</span>
<span>## $ x     &lt;dbl&gt; 87.48904, 90.65766, 89.60541, 94.43392, 90.58486, 91.593...</span>
<span>## $ y     &lt;dbl&gt; 98.86733, 103.88861, 103.72933, 106.09227, 112.29610, 11...</span></code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(ugiu_pogrupiai)
<span>##     ugiai        x         y</span>
<span>## 1 Aukštas 87.48904  98.86733</span>
<span>## 2 Aukštas 90.65766 103.88861</span>
<span>## 3 Aukštas 89.60541 103.72933</span>
<span>## 4 Aukštas 94.43392 106.09227</span>
<span>## 5 Aukštas 90.58486 112.29610</span>
<span>## 6 Aukštas 91.59315 116.19140</span></code></pre><pre class="sourceCode r"><code class="sourceCode r">dazniu_lentele &lt;-<span class="st"> </span>ugiu_pogrupiai <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">group_by</span>(ugiai) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">count</span>()  <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">mutate</span>(<span class="dt">is_viso =</span> <span class="kw">sum</span>(n)) </code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pander</span>(dazniu_lentele)</code></pre><table style="width:39%"><colgroup><col width="16%"><col width="8%"><col width="13%"></colgroup><thead><tr class="header"><th align="center">ugiai</th><th align="center">n</th><th align="center">is_viso</th></tr></thead><tbody><tr class="odd"><td align="center">Aukštas</td><td align="center">80</td><td align="center">300</td></tr><tr class="even"><td align="center">Vidutinis</td><td align="center">120</td><td align="center">300</td></tr><tr class="odd"><td align="center">Žemas</td><td align="center">100</td><td align="center">300</td></tr></tbody></table><p>Dabartinė <strong>pander</strong> versija turi problemų su tarptautinių (t.p. ir lietuviškų) simbolių dekodavimu.</p><pre class="sourceCode r"><code class="sourceCode r">rez &lt;-<span class="st"> </span><span class="kw">data.frame</span>(DescTools<span class="op">::</span><span class="kw">MultinomCI</span>(<span class="dt">x =</span> dazniu_lentele<span class="op">$</span>n, <span class="dt">method =</span> <span class="st">&quot;goodman&quot;</span>)) 
<span class="kw">pander</span>(rez)</code></pre><table style="width:38%"><colgroup><col width="12%"><col width="12%"><col width="12%"></colgroup><thead><tr class="header"><th align="center">est</th><th align="center">lwr.ci</th><th align="center">upr.ci</th></tr></thead><tbody><tr class="odd"><td align="center">0.2667</td><td align="center">0.2092</td><td align="center">0.3333</td></tr><tr class="even"><td align="center">0.4000</td><td align="center">0.3334</td><td align="center">0.4705</td></tr><tr class="odd"><td align="center">0.3333</td><td align="center">0.2706</td><td align="center">0.4026</td></tr></tbody></table><p>Skaičių formatavimas gali būti vykdomas funkcija <strong><em>sprintf</em></strong>. Formatas <code>%.2f</code>:</p><ul><li><strong><em>%</em></strong> reiškia, kad bus formato aprašymas</li><li><strong><em>.2</em></strong> – du skaičiai po kablelio</li><li><strong><em>f</em></strong> – fiksuotas skaičių formatas (mūsų atveju, visą laiką 2 skaičiai po kablelio).</li></ul><pre class="sourceCode r"><code class="sourceCode r">rez <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">transmute</span>(<span class="dt">pi_graziau =</span> <span class="kw">sprintf</span>(<span class="st">&quot;%.2f (%.2f–%.2f)&quot;</span>, est, lwr.ci, upr.ci))
<span>##         pi_graziau</span>
<span>## 1 0.27 (0.21–0.33)</span>
<span>## 2 0.40 (0.33–0.47)</span>
<span>## 3 0.33 (0.27–0.40)</span></code></pre><p>Dabar visą analizę sujunkime į vieną grandinę. Joje yra funkcija <strong><em>do()</em></strong> kuri naudojama vietoje <strong><em>summarize()</em></strong>, kai vienu metu reikia apskaičiuoti daugiau nei vieną skaičių (šiuo atveju, proporcijos įvertį ir pasikliauties intervalą).</p><pre class="sourceCode r"><code class="sourceCode r">prop_pi &lt;-<span class="st"> </span>ugiu_pogrupiai <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">group_by</span>(ugiai) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">mutate</span>(<span class="dt">is_viso =</span> <span class="kw">sum</span>(n)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">do</span>(<span class="kw">data.frame</span>(<span class="dt">ugiai =</span> .<span class="op">$</span>ugiai, 
                  <span class="dt">n =</span> .<span class="op">$</span>n,
                  DescTools<span class="op">::</span><span class="kw">MultinomCI</span>(<span class="dt">x =</span> .<span class="op">$</span>n, <span class="dt">method =</span> <span class="st">&quot;goodman&quot;</span>))
       ) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">mutate</span>(<span class="dt">ivertis_graziau  =</span> <span class="kw">sprintf</span>(<span class="st">&quot;%.1f%%&quot;</span>, <span class="dv">100</span><span class="op">*</span>est),
           <span class="dt">pi_graziau       =</span> <span class="kw">sprintf</span>(<span class="st">&quot;(%.1f–%.1f)&quot;</span>, <span class="dv">100</span><span class="op">*</span>lwr.ci, <span class="dv">100</span><span class="op">*</span>upr.ci))</code></pre><p>Rezultatas:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">glimpse</span>(prop_pi)
<span>## Observations: 3</span>
<span>## Variables: 7</span>
<span>## $ ugiai           &lt;fct&gt; Aukštas, Vidutinis, Žemas</span>
<span>## $ n               &lt;int&gt; 80, 120, 100</span>
<span>## $ est             &lt;dbl&gt; 0.2666667, 0.4000000, 0.3333333</span>
<span>## $ lwr.ci          &lt;dbl&gt; 0.2091875, 0.3333785, 0.2705523</span>
<span>## $ upr.ci          &lt;dbl&gt; 0.3332834, 0.4705376, 0.4026412</span>
<span>## $ ivertis_graziau &lt;chr&gt; &quot;26.7%&quot;, &quot;40.0%&quot;, &quot;33.3%&quot;</span>
<span>## $ pi_graziau      &lt;chr&gt; &quot;(20.9–33.3)&quot;, &quot;(33.3–47.1)&quot;, &quot;(27.1–40.3)&quot;</span></code></pre><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(prop_pi)
<span>##       ugiai   n       est    lwr.ci    upr.ci ivertis_graziau  pi_graziau</span>
<span>## 1   Aukštas  80 0.2666667 0.2091875 0.3332834           26.7% (20.9–33.3)</span>
<span>## 2 Vidutinis 120 0.4000000 0.3333785 0.4705376           40.0% (33.3–47.1)</span>
<span>## 3     Žemas 100 0.3333333 0.2705523 0.4026412           33.3% (27.1–40.3)</span></code></pre><p>Pasikliauties intervalus nusibraižykime:</p><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(prop_pi, <span class="kw">aes</span>(<span class="dt">x =</span> ugiai, <span class="dt">fill =</span> ugiai)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_col</span>(<span class="kw">aes</span>(<span class="dt">y =</span> est),
             <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>,
             <span class="dt">width =</span> <span class="fl">0.5</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> lwr.ci, <span class="dt">ymax =</span> upr.ci),
                  <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>,
                  <span class="dt">size  =</span> <span class="dv">1</span>,
                  <span class="dt">width =</span> <span class="fl">0.2</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">y =</span> <span class="fl">-0.02</span>, <span class="dt">label =</span> ivertis_graziau),
              <span class="dt">fontface =</span> <span class="st">&quot;bold&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">y =</span> <span class="fl">-0.06</span>, <span class="dt">label =</span> pi_graziau)) <span class="op">+</span>
<span class="st">    </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.06</span>, <span class="fl">0.55</span>), <span class="dt">expand =</span> <span class="ot">TRUE</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">linetype =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(    <span class="dt">x =</span> <span class="st">&quot;Ūgio grupė&quot;</span>,
          <span class="dt">fill =</span> <span class="st">&quot;Ūgio grupė&quot;</span>,
             <span class="dt">y =</span> <span class="st">&quot;Procentinė dalis&quot;</span>,
         <span class="dt">title =</span> <span class="st">&quot;Pasiskirstymas pagal ūgį&quot;</span>,
         <span class="dt">subtitle =</span> <span class="st">&quot;Pasikliauties intervalai apskaičiuoti Goodman metodu&quot;</span>
         ) <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> <span class="cf">function</span>(x){ <span class="kw">paste0</span>(<span class="dv">100</span> <span class="op">*</span><span class="st"> </span>x, <span class="st">&quot;%&quot;</span>) }) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme_bw</span>()</code></pre><p><img src="08--01--pi-klasikiniai_files/figure-html/unnamed-chunk-77-1.png"width="672"style="display:block;margin:auto"></p><div class="ok"><p>Proporcijas vaizduoti stulpeliu yra korektiška.</p></div><div class="avoid"><p>Bet vidurkį, medianą ir pan. – didelė klaida, nes atsiranda dviprasmybė. Jiems vietoje stulpelio rinkitės tašką.</p></div></div></div></div></section></div></div></div><a href="skirstinio-parinkimas.html"class="navigation navigation-prev"aria-label="Previous page"><i class="fa fa-angle-left"></i></a> <a href="pi-saviranka.html"class="navigation navigation-next"aria-label="Next page"><i class="fa fa-angle-right"></i></a></div></div><script src="libs/gitbook-2.6.7/js/app.min.js"></script><script src="libs/gitbook-2.6.7/js/lunr.js"></script><script src="libs/gitbook-2.6.7/js/plugin-search.js"></script><script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script><script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script><script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script><script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script><script>gitbook.require(["gitbook"],function(t){t.start({sharing:!1,fontsettings:{theme:"sepia",family:"sans",size:2},edit:null,history:{link:null,text:null},download:null,toc:{collapse:"section",scroll_highlight:!0},toolbar:{position:"static"},search:!0})})</script><script>!function(){var t=document.createElement("script");t.type="text/javascript";var e="true";""!==e&&"true"!==e||(e="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML"),"file:"!==location.protocol&&/^https?:/.test(e)&&(e=e.replace(/^https?:/,"")),t.src=e,document.getElementsByTagName("head")[0].appendChild(t)}()</script></body></html>